### ISSUE TITLE
Update pyjwt to the latest version

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1048]
We are currently using pyjwt 1.7, which is very outdated. Update to the latest version.

pjwt is a requirement of flask-jwt-extended.

See also #960.

##  Tasks
- [x] Review the [release notes between flask-jwt-extended v3 and v4](https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/) and identify any potential issues. (0d) @mssalvatore 
- [ ] Upgrade flask-jwt-extended to v4.2.3 (latest version). (0.5d) @mssalvatore 
  - [x] Update Pipfile and Pipfile.lock (remove pyjwt from Pipfile)
  - [ ] Run tests (test all authenticated endpoints)
  - [ ] Fix anything that broke
