### ISSUE TITLE
Resolve C901 issues

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1076]
Flake8 identifies nineteen C901 complexity warnings. Resolve these warnings by refactoring the code and remove C901 from the `extend-ignore` list in `.flake8`

![image](https://user-images.githubusercontent.com/19957806/233098957-ce833862-dcc1-47ed-b92b-afe0f4623c19.png)

## Tasks
- [x] Resolve C901 issue in the dropper (0d) @cakekoa 
- [x] Resolve C901 issue in http_client (0d) - @shreyamalviya 
- [x] Resolve C901 issue in tcp_scanner (0d) @ilija-lazoroski 
- [x] Resolve C901 issue in info.py (0d) @ilija-lazoroski 
- [x] Remove C901 from the ignore list in`.flake8` configuration file 
    - [x] Add ignore for any Zerologon warnings
