### ISSUE TITLE
Move all UT's into a dedicated directory

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1102]
**Is your feature request related to a problem? Please describe.**
Unit tests take long time to get discovered

**Describe the solution you'd like**
Move it into a dedicated directory

**Tasks (0.75d)**

- [x] Moving test into a dedicated directory. (0d) - @shreyamalviya 
- [x] Make sure pre-commit runs UT's (0d) - @shreyamalviya 
- [x] Add pytest config to pyproject.toml. Make sure pre-commit and travis picks it up. (0d) - @shreyamalviya
