### ISSUE TITLE
Automatically test MSI in nightly tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1120]
Add the ability for jenkins to run the blackbox tests against the MSI after blackbox tests are completed on the AppImage.
Pre-requisite: #1202 is done.

## Tasks:
- [x] Fix the deployment bug in MSI. #1252 (0d) -@mssalvatore
- [x] Create an MSI EtE job and configure EtE master job to also run MSI EtE job (0d) - @VakarisZ 
- [x] Create an MSI S3 upload script and trigger it (0d) - @VakarisZ 
- [x] Create an MSI island script to run the island and BB tests
     - [x] Implement the installation of the island and BB tests using [this document](https://docs.google.com/document/d/18vh-7xmo3zKnZcKLFKV2bA6nR3slKxaPXj___dYMyKY/edit?usp=sharing) (0d) - @VakarisZ 
     - [x] Figure out and implement a way to replace/uninstall the old island (quick way would be a snapshot, but look into updating as well) (0) - @VakarisZ 
- [x] Configure island to allow [powershell remoting](https://docs.google.com/document/d/18vh-7xmo3zKnZcKLFKV2bA6nR3slKxaPXj___dYMyKY/edit?usp=sharing), create and overwrite the island-windows-251 image. (0d) - @VakarisZ 
- [x] Create a Windows GCP script and trigger it in the build. This script should use powershell remoting. (0d) - @VakarisZ
