### ISSUE TITLE
Fix security of credentials in config.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1172]
## Describe the bug
Infection monkey shows/exports unencrypted credentials.

## To Reproduce
1. Enter passwords in the list
2. See the passwords
3. Export config
4. Open exported file
5. See plaintext passwords

## Expected behavior
1. On "Export config" click user get's a popup with explanation about sensitive credentials in config.
1. User can either enter password to encrypt the config or export plaintext config (similar to registration/no password)
1. On import island should detect if configuration is encrypted or plaintext. If encrypted, another pop-up for password.
1. Exported config should be encrypted based on the password provided by the user.

## Tasks
- [x] Create UI mockups for export/import (0d) - @VakarisZ 
- [x] Implement encryption of configuration, based on password (0d) - @shreyamalviya 
- [x] Create UI component for export popup and hookup backend (0d) - @VakarisZ 
- [x] Create UI component for password input and a warning for wrong password (0d) -@VakarisZ
- [x] Implement safety check (0d)
- [x] Alter backend resources to check for encryption, prompt for password and test everything (0d)
- [ ] Review and fix (0.5d)

## Mockups:
![image](https://user-images.githubusercontent.com/36815064/119801167-1d675980-bee6-11eb-93d5-ba96d3c10d9f.png)

**Comment by mssalvatore** [comment]
Monkey Island should give the users the option to enter a password to encrypt the config export. On import, it would be ideal if the island could detect an encrypted config and prompt the user for the password[

**Comment by VakarisZ** [comment]
I feel like that's maybe a V2. Also, I'm not sure if entering a password on export/import is convenient, given the fact that the user is already authenticated and we can use authentication data as a secret without a prompt.

**Comment by VakarisZ** [comment]
Me and Mike decided that it's not worth encrypting with default credentials because configs will not be compatible among different installation
