### ISSUE TITLE
Update and test new changes on MSI

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1179]
- [x] Test if permissions for newly created data directory work on a built installer (#1147). (0d) - @VakarisZ 
- [x] Update the MSI build to use the new server_config.json format (#1146). (0d) - @VakarisZ 
- [x] Test mongodb start on MSI build (#1148). (0d) - @VakarisZ
