### ISSUE TITLE
Hide passwords and other credentials in UI

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1183]
## Describe the bug
Credential inputs in the configuration are shown plain-text.

## Tasks
- [x] Create a component that would hide input by default, but would have an option to show plaintext on click (0.5d) @ilija-lazoroski 
- [x] Convert all of the sensitive inputs to use this component (0.25d) @ilija-lazoroski 
- [ ] Review and address comments (0.5d) @ilija-lazoroski
