### ISSUE TITLE
Code is running on import, resulting in undesired execution of logic

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1199]
## Describe the bug

Reporting semaphores are created when `report_generation_synchronisation` is imported. If the `--help` flag is passed to Monkey Island, the user sees a log message regading the initialization of these locks. The `--help` flag should only display help and exit.

We should avoid executing global statements like this that run on import.

**Note**: This behavior could prevent us from using multiprocessing on Windows, as Windows uses the [spawn method](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods) to start child processes.

https://github.com/guardicore/monkey/blob/4e6bb219425927f979767d9750d5317f896551eb/monkey/monkey_island/cc/services/reporting/report_generation_synchronisation.py#L1-L15

## To Reproduce
1. Run Monkey Island with the `--help` flag
2. See error

## Screenshots
![image](https://user-images.githubusercontent.com/19957806/120564874-dee80800-c3d9-11eb-8037-8a2d51c6cf62.png)

## Tasks
- [ ] Initialize a `Lock` class member and lock ReportService.get_report() (0.25d) @ilija-lazoroski 
- [x] Modify `services/infection_lifecycle.py` to not call `is_report_being_generated()` (0d) @ilija-lazoroski 
- [x] Remove report_generation_synchronization (0d) @ilija-lazoroski
