### ISSUE TITLE
Separate EtE tests job from AppImage job

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1202]
**Is your feature request related to a problem? Please describe.**
Pre-requisite for  #1120

## Tasks
- [x] Extract the appImage related logic out of EtE job into a separate job 
   - [x] Separate S3 upload script into Common, AppImage S3 upload script (0d) - @VakarisZ 
   - [x] Separate GCP run island script into Common and Linux (0d) - @VakarisZ 
   - [x] Separate the island script into Common and AppImage (0.25d) - @VakarisZ 
   - [x] Separate the EtE job and AppImage job (0.25d) - @VakarisZ
