### ISSUE TITLE
User credentials should not be stored in server_config.json

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1206]
User credentials (username and password hash) for Monkey Island are not options that the user is expected to manually configure. Rather, they represent inputs to the authentication system. Because they are stored in `server_config.json`, the `server_config.json` file must be stored in a writable location, which adds some undesired complexity:

https://github.com/guardicore/monkey/blob/cc00b85edc846f0cd0e157e350275a015ad8ec18/monkey/monkey_island/setup/config_setup.py#L10-L22

In addition, user credentials serve a markedly different purpose (access control) than other values in `server_config.json` (configuring the behavior of Monkey Island at runtime). 

Store the user credentials in a separate file within `data_dir/`. Alternatively, consider storing the user credentials in MongoDB instead of a file.

## Tasks
- [ ] Create a new component that can store and retrieve user credentials. (0.25d) @mssalvatore 
- [x] Modify the `AuthenticationService` to use the new component. Write unit tests that cover the AuthenticationService. (0d) @mssalvatore 
- [x] Remove authentication code from `Environment` and `EnvironmentConfig`. (0d) @ilija-lazoroski 
- [x] Update reset password procedure in the documentation (0.25d) @ilija-lazoroski
