### ISSUE TITLE
Ransomware Configuration UI

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1239]
# Description

As a red team member, I want a way to configure a ransomware simulation, so that I can test my network under a variety of ransomware scenarios.

# Acceptance Criteria
- A ransomware configuration screen is available from the configuration menu.
- All configurable options related to ransomware are configurable from the UI.
  - Text field allowing the user to specify a directory
     - Linux path
     - Windows path
  - Enable/disable checkbox that hides directory text field if disabled
- UI validates that paths are absolute or begin with an environment variable.
- Configuration options set in the ransomware configuration screen are passed to the monkey agents.
- Testing plan is updated to include testing this UI.

# Tasks

- [x] Add encryption enabled/disabled option to ransomware configuration (0d) - @shreyamalviya 
  - [x] Verify the checkbox appears in the UI
  - [x] Ransomware payload decides whether or not to encrypt based on this option
- [x] Make linux/windows directory fields shown or hidden based on the enable/disable configuration parameter (0d) - @VakarisZ 
  - [x] Create a custom UI widget 
  - [x] Test that Monkey Agent receives correct configuration
- [x] Add UI validators that check paths are absolute or begin with environment variables (0d) - @shreyamalviya 
  - See `monkey_island/cc/ui/src/components/configuration-components/ValidationFormats.js` and `common/common_consts/validation_formats.py`
  - Allow paths like `C:\...` or `/...`
  - Allow paths like `$VAR`
  - Allow paths like `%AppData%\...` 
  - Any others?
- [x] Add helpful descriptions to the Linux and Windows directory fields. Keep the language consistent with the documentation. (0d) @mssalvatore 
- [x] Add a short description of ransomware and a link to the documentation at the top of the configuration page. (0d) 
- [x] Update release testing plan (0d) @mssalvatore
