### ISSUE TITLE
Ransomware quickstart

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1241]
# Description

As a red team member, I want a quick and easy way to configure a ransomware simulation, so that I can easily test my network under a variety of ransomware scenarios.

# Acceptance Criteria
- A "Ransomware" button is added to the monkey island welcome screen.
- Upon clicking the ransomware button, the user is provided with a series of screens that allow them to:
    - enable/disable encryption
    - configure networking
    - configure exploits
- All post-breach actions are disabled
- All system info collectors are enabled
- Sidebar menu has a "Ransomware Simulation Configuration" item
- Testing plan is updated to include testing this UI.

# Tasks
- [x] Add API endpoint that allows the UI to set the mode (0d) - @VakarisZ 
    - A field is set in mongodb to store which mode the user chose
- [x] Add API endpoint that allows the UI to get the mode (0d) - @ilija-lazoroski 
- [x] Add a new welcome screen that is displayed when monkey first starts (0d) - @VakarisZ 
  - [x] No list items are displayed in sidebar
  - [x] A description of monkey is displayed (see current home page)
  - [x] 2 buttons allow the user to chose between Ransomware Simulation and Advanced Configuration
  - [x] When button is clicked
    - [x] Call API endpoint to set the mode
    - [x] User is brought to current home page
- [x] When the user clicks "start over", they are brought back to the ransomware/advanced configuration selection page (0d) @ilija-lazoroski @VakarisZ 
    - [x] API endpoint is called that unsets the mode
- [x] Set default configuration values when mode is set (potentially use config templates from blackbox tests) (0d) - @shreyamalviya 
    - [x] No change to behavior if mode is set to "Advanced"
    - [x] Disable post-breach actions if mode is set to "Ransomware"
- [x] Show mode at the top of the sidebar (0d) @VakarisZ 
- [x] Hide scoutsuite run option in ransomware mode (0d) @ilija-lazoroski 
- [x] Fix #1329  (0d)
- [x] Only display Exploits, Network, and Ransomware configuration tabs in Ransomware mode (0d) - @shreyamalviya 
- [x] Remove "Congratulations" message from island home page, change header to "Get started" (0d) @ilija-lazoroski
