### ISSUE TITLE
Ransomware readme feature needs configurable directories

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1287]
## Describe the bug
The directory where ransomware note is dropped is currently the same as the directory for the file encryption.

## Target UI
![image](https://user-images.githubusercontent.com/36815064/124912714-f5940700-dff6-11eb-9601-12f71c412a90.png)

## To Reproduce
1. Configure the ransomware directories
2. Disable the encryption
3. Ransomware directories can't be configured further even though readme is enable and will be dropped in the directory provided

## Expected behavior
One possible solution would be to add input fields for readme target directories. These input will be disabled upon disabling the readme the same way encryption target directories are disabled if encryption is disabled. We could also try to make these inputs have the same values as encryption target directories by default somehow.

## Tasks

- [x] Make "encryption" and "readme" boolean fields hidden in UI and enabled by default. (0d) - @ilija-lazoroski 
  - [x] Test that no README is left if no directory is provided.
- [x] Fix description to match target UI screenshot (0d) - @shreyamalviya 
  - [x] Add info box
- [x] Add readme.txt note at the bottom of the page (0d - Time boxed) @ilija-lazoroski 
  - [x] Improve the wording of the readme.txt note
