### ISSUE TITLE
Give landing page a face lift

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1349]
## Tasks
- [x] Hide whole nav bar on landing page (0d) @ilija-lazoroski 
- [x] "Powered by Guardicore" at bottom center (0d) @ilija-lazoroski 
- [x] Reword landing page (0d) @ilija-lazoroski 
    - [x] Reword "Welcome to Monkey Island Server"
    - [x] Add link to scenarios documentation (#1346)
 - [x] Make "Ransomware" and "Custom" scenario buttons the same size (0d) - @shreyamalviya
