### ISSUE TITLE
Timestomping PBA fails on Windows

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1405]
## Describe the bug
Timestomping post breach action fail on Windows machine (victim). Running the `timestomping.ps1` script passes when run from source. It was tried both with 1.10.0 and 1.11.0 agent binaries.

Issue #1419 has the same root cause as this issue.

## To Reproduce
1. Run Monkey Island
2. Configure to run just Timestomping PBA
3. Check Security report for PBA explanation

## Expected behavior
Timestomping should execute `timestomping.ps1` script which create temp file and changes the time of the file.

## Screenshots

![image](https://user-images.githubusercontent.com/15820737/128709280-9a2e5ab3-3a5e-4865-be62-962d08bc758a.png)

## Machine version (please complete the following information):
 - OS: Windows (victim)

## Tasks
- [ ] Add the powershell scripts to the list of binaries in the spec file and test. (0.25d) @mssalvatore 
  - [ ] `monkey/infection_monkey/post_breach/shell_startup_files/windows/modify_powershell_startup_file.ps1`
  - [ ] `monkey/infection_monkey/post_breach/timestomping/windows/timestomping.ps1`

**Comment by mssalvatore** [comment]
## Root cause

This is very likely caused by the requisite script being left out of the agent binary. The scripts probably needs to be added to: https://github.com/guardicore/monkey/blob/dd390ff41d22f3d85e5b135109cc097c24ff7da1/monkey/infection_monkey/monkey.spec#L21
