### ISSUE TITLE
Backdoor user is not deleted afterwards

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1410]
## Describe the bug
When using the post breach action Backdoor user, the user created it is not deleted afterwards which causes the PBA to fail.

## To Reproduce
1. Run Monkey Island
2. Configure to run just Backdoor user PBA
3. Run the monkey agents manually 

## Expected behavior
The user should be deleted after the post breach action finishes.

## Screenshots
![image](https://user-images.githubusercontent.com/15820737/128832804-07225133-517e-4d06-af01-ce2ef9a30879.png)

## Machine version (please complete the following information):
 - OS: Windows and Linux (victims)

## Tasks
- [x] Remove BackdoorUser PBA and change CommunicateAsNewUser to something else. (0d) @ilija-lazoroski 
  - [x] In the agent.
  - [x] In the island.
- [x] Fix Swimm with respect to above changes. (0d) - @shreyamalviya 
- [x] Don't use hardcoded password for CommunicateAsNewUser. See #1169. (0d) - @shreyamalviya 
- [x] Add unit test for AutoNewWindowsUser. (0d) @ilija-lazoroski, @shreyamalviya
