### ISSUE TITLE
Current user's credential re-use in powershell

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1448]
## Describe the bug
Cached credentials ( credentials that the user is being propagated with) are not working when running the PowerShellExploiter.
For this purpose we need to have Island and two windows machine both with a account that has same credentials. The island should not have access to the second machine, so only the first machine can propagated to the second.

## To Reproduce
1. Configure the Island to run PowerShell exploiter with credentials
2. Run the monkey from Island
3. See that second machine is not exploited.

## Expected behavior
The second machine should be exploited with cached credentials from the PowerShell Client.

## Machine version (please complete the following information):
 - OS: Windows

## Task
- [x] Can powershell remoting/powershell exploiter re-use the credentials of the current user to login to remote where the same user with the same credentials are present?
    - [x] Create a new setup on GCP where powershell remoting can be done without providing credentials. [Useful thread](https://social.technet.microsoft.com/forums/windowsserver/en-US/46a7ed80-78cd-4ded-84aa-accf42265571/remote-sessionscript-with-current-users-credentials). (0d) - @VakarisZ 
    - [x] Check if powershell exploiter can do it and why (AFAIK if ran from island doesn't work, if ran in another machine manually - works.) Timeboxed - (0d)
    Result - a more descriptive issue/comment explaining what we need to do to make this work or why it doesn't work.

**Comment by VakarisZ** [comment]
Created a machine (10.2.3.48) on GCP and asserted that we can log into another machine without specifying any credentials if there's a user with the same credentials on target machine. Tested from dev AND with monkey binary from windows island.
