### ISSUE TITLE
Upgrade Python dependencies to fix vulnerabilities

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1469]
# Description

Upgrade any Python dependencies that have known vulnerabilities.

## Tasks

- [x] Run snyk and trivy, fix as many of vulns as we can (0d) - @shreyamalviya 
- [x] Test the monkey with updated dependencies and verify it still runs on ubuntu 16 (0d) @ilija-lazoroski 
- [x] Open issues with suggestions for the security bugs we were unable to fix (timeboxed 0d) @ilija-lazoroski, @mssalvatore 
  - [x] Do a research on how to implement [different virtual environments ](https://stackoverflow.com/questions/48332046/does-pip-python-support-multiple-versions-of-the-same-package) and [environments markers ](https://www.python.org/dev/peps/pep-0508/#environment-markers) to help with different version of python packages for 32bit and 64bit agent.
