### ISSUE TITLE
Remove unused system info collectors

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1535]
Some system info collectors may collect data that is unused (see process list collector and netstat collector).

## Tasks
- [ ] Investigate all system info collectors. Identify code that can be removed. (0.25dd) - @VakarisZ 
- [x] Test Azure credential collector (0d)
- [x] Remove any collectors (or code within the collectors) that is unnecessary, unused, or ignored and test. (0d)
- [ ] Update the release testing plan with steps to test the remaining system info collectors. (0.25d)
