### ISSUE TITLE
Remove unused/untested options

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1537]
Infection Monkey is highly configurable. Some configuration options are untested, likely unused, and mostly unnecessary. Remove the below options from the configuration and ensure there is sufficient test coverage.

	- Send log to server
	- Delete on cleanup
	- Use file logging
	- Serialize config
	- Try to move first
	- singleton mutex name
	- Monkey's directory name
	- Maximum iterations
	- timeout between iterations

## Tasks
- [x] Always send log to server (0d) @ilija-lazoroski 
- [x] Always delete on cleanup (0d) @ilija-lazoroski 
- [x] Always use file logging (0d) @ilija-lazoroski 
- [x] Remove "serialize config" (0d) @ilija-lazoroski 
- [x] Always try to move first (0d) @ilija-lazoroski 
- [x] Use constant singleton mutex name (0d) - @shreyamalviya 
- [x] Use constant monkey directory name (0d) @ilija-lazoroski 
- [ ] Remove maximum iterations feature (0.25d) - @shreyamalviya 
  - [ ] Remove timeout between iterations
