### ISSUE TITLE
Add systemd unit file for AppImage

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1552]
# Description
The AppImage package does not run on boot. Presently, it can only be run manually. A simple systemd unit file could be added that would allow the AppImage to be installed as a service.

# Tasks
- [x] Create a systemd unit file that allows the AppImage package to be run on boot. Make sure Infection Monkey does not run as root.
- [x] Create an installation script that installs the AppImage package and systemd unit file.
- [ ] ~Document the installation process.~
- [ ] ~Update the documentation for creating Azure and AWS images.~

**Comment by mssalvatore** [comment]
Resolved by #1852. #1833 is a followup issue.
