### ISSUE TITLE
Remove "+dev" from version numbers

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1553]
Release packages are built with `+dev` in the version. Figure out why and fix it.

Development packages should be versioned like `v[VERSION]+[GIT_COMMIT_ID]`. Release packages should be versioned like `v[VERSION]`

## Tasks
- [ ] Fix artifact version numbers to be as described above (0.25d) @ilija-lazoroski 
   - [x] Fix local builds
   - [x] Fix jenkins builds
