### ISSUE TITLE
Refactor the authentication service

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1554]
A clear architectural line is missing between the authentication service and the authentication and registration resources. The responsibility of the resources is to handle details specific to the API (e.g. protocol, return codes, request parsing). The responsibility of the service is to perform the requested function.

# Tasks
- [x] Refactor the authentication service and resources to perform their assigned functions.
- [x] Simplify authentication code
  - [x] Remove user store
  - [x] Remove unnecessary "AuthUser"
  - [x] Minimize the responsibilities of the "environment" singleton and environment config
- [x] Write unit tests for resources
- [ ] Review and merge. (0.5d)

**Note:** This work has been completed on the [1554-authentication-service-refactor](/guardicore/monkey/tree/1554-authentication-service-refactor) branch. It needs to be reviewed and merged.
