### ISSUE TITLE
Simplify handling of server_config.json

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1576]
After the completion of #1206, the `server_config.json` no longer needs to be copied to a writable location. Both the code and some manual setup procedures can be simplified if Monkey Island behaves as follows.

1. If `cc/monkey_island/server_config.json` exists, read it and .override the default configuration values with values in this file (docker only).
2. If the user provided the `--server-config` option on the command line, read the user-provided `server_config.json` and override any default values with the user-provided values.

This removes the circular dependency between the `server_config.json` and the `data_dir` option. It also means that a user-provided server_config.json _only_ needs to provide settings that deviate from the default.

## Tasks
- [x] Remove logic that copies `server_config.json` to `data_dir` (0d) - @VakarisZ 
- [x] Modify the code in `config_setup.py` load defaults if `cc/monkey_island/server_config.json` does not exist, or load it if it does. (0d) - @VakarisZ 
- [x] Update `server_config.json` for each package to include only settings that deviate from defaults. (0d) @VakarisZ 
  - [x] Docker
- [x] If the user provided a custom `server_config.json` with the `--server-config` option, update the `IslandConfigOptions` object with the values from the user-provided file. (0.5d) @VakarisZ 
- [x] Simplify/correct/improve any instructions in the documentation that refer to the server_config.json. (0d)
  - [ ] https://www.guardicore.com/infectionmonkey/docs/reference/data_directory/
  - [ ] Add FAQ about log level
  - [ ] Certificate setup:
    - [ ] AppImage
    - [ ] Docker
    - [ ] MSI
- [x] Test all packages manually (0d)
  - [ ] AppImage
  - [ ] Docker
  - [ ] MSI
