### ISSUE TITLE
Implement "ControlChannel"

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1596]
Implement the `ControlChannel` class in support of the agent refactor effort <sup>[1](#594), [2](https://guardicore.atlassian.net/wiki/spaces/RES/pages/2818932869/Infection+Monkey+-+Monkey+Agent+Refactor-+Phase+1+-+PDR)</sup>.

The `ControlChannel` should provide the following 3 functions:
1. `should_agent_stop() -> bool`
2. `get_config() -> dict`
3. `get_credentials_for_propagation() -> dict`

## Tasks
- [x] Mock new endpoint on Monkey Island that allows agent to check for stop (0d) @ilija-lazoroski 
- [x] Implement `should_agent_stop()` (0d) @ilija-lazoroski 
- [x] Implement `get_config()` (0d) @ilija-lazoroski 
- [x] Mock new endpoint on Monkey Island that allows agent to get credentials for propagation (0d) @ilija-lazoroski 
- [x] Implement `get_credentials_for_propagation()` (0d) @ilija-lazoroski
