### ISSUE TITLE
Implement AutomatedMaster

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1597]
Implement a concrete `AutomatedMaster` in support of the agent refactor effort <sup>[1](#594), [2](https://guardicore.atlassian.net/wiki/spaces/RES/pages/2818932869/Infection+Monkey+-+Monkey+Agent+Refactor-+Phase+1+-+PDR)</sup>. Use the pseudocode from [the design](https://guardicore.atlassian.net/wiki/spaces/RES/pages/2818932869/Infection+Monkey+-+Monkey+Agent+Refactor-+Phase+1+-+PDR) as a starting point.

**Note**: As #1595 will already be complete when this issue gets resolved, don't forget to revisit the Windows signal handler for `CTRL_CLOSE_EVENT` signals.

## Tasks

- [x] Implement the `start()` and `terminate()` (0d) @mssalvatore 
- [x] Implement `_check_for_stop()` (0d) @mssalvatore
- [x] Implement `_run_master_thread()` that calls a bunch of stubs (0d) @mssalvatore
- [x] Implement all of the stubs:
    - [x] System info collectors thread (0d)
    - [x] PBA thread (0d)
    - [x] Propagation
        - [x] Scanning
            - [x] Ping scanning @mssalvatore 
            - [x] tcp scanning (0d) @mssalvatore 
            - [x] Target generation (0d) @VakarisZ 
            - [x] fingerprinting (0d) @mssalvatore 
            - [x] Remove unneeded options (max_victims_to_find/exploit, tcp_scan_get_banner, tcp_scan_interval) (0d) @ilija-lazoroski 
        - [x] Exploiting (0d) @mssalvatore 
   - [x] Payload (0d) @mssalvatore 
- [x] Revisit signal handler TODO (0d) @mssalvatore 
- [x] Handle ControlClient exceptions (0d) @ilija-lazoroski 
- [x] Integrate AutomatedMaster into the agent (0d) @mssalvatore
