### ISSUE TITLE
Implement a concrete Puppet

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1598]
Create a concrete `Puppet` class in support of the agent refactor effort <sup>[1](#594), [2](https://guardicore.atlassian.net/wiki/spaces/RES/pages/2818932869/Infection+Monkey+-+Monkey+Agent+Refactor-+Phase+1+-+PDR)</sup>. Copy the mock object created in #1592 and implement the `run_payload()` function.

## Tasks
- [x] Add a new `load_plugin(plugin: object, plugin_type: PluginType)` function to `IPuppet` and `MockPuppet` (0d) - @shreyamalviya 
  - [x] Add `PluginType` enum
- [x] Copy the MockPuppet and create a new Puppet class (0d) - @shreyamalviya 
- [x] Implement the `load_plugin()` function (0d) - @shreyamalviya 
  - [x] Add a new `PluginRegistry` class that implements `{load,get}_plugin(name: str, type: PluginType)` so that `run_payload()` can find the correct payload to run.
  - [x] Implement the `run_payload()` function with unit tests - @ilija-lazoroski 
- [x] Define a payload interface (0d) - @shreyamalviya 
- [x] Modify the ransomware payload and builder to adhere to the payload interface (0d)
- [x] Construct the concrete Puppet in monkey.py (0d) @mssalvatore 
  - [x] Add the ransomware payload to the concrete Puppet in `monkey.py`
