### ISSUE TITLE
Implement fingerprinting in Puppet

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1603]
Implement the `fingerprint()` function of the concrete Puppet.

## Tasks
- [x] Implement the `fingerprint()` function in the concrete Puppet  (0d) @mssalvatore
  - [x] Load the `httpfinger` plugin into the puppet (0d) @mssalvatore
  - [x] modify `httpfinger` to decouple it from the `WormConfig` and `VictimHost` @mssalvatore
    - [x] modify the `HTTPFinger` interface as necessary (return type, etc.)
    - [x] Modify the `IPuppet` interface as necessary 
  - [x] Improve the logic of `httpfinger` if possible (don't scan ports we already scanned and know are closed) (0d) @mssalvatore 
- [x] modify `elasticfinger` to decouple it from the `WormConfig` and `VictimHost`, improve logic where relevant/possible and test. (0d) @mssalvatore 
- [x] modify `mssqfinger` to decouple it from the `WormConfig` and `VictimHost`, improve logic where relevant/possible and test (0d) @ilija-lazoroski 
- [x] modify `smbfinger` to decouple it from the `WormConfig` and `VictimHost`, improve logic where relevant/possible and test (0d) @mssalvatore 
- [x] modify `sshfinger` to decouple it from the `WormConfig` and `VictimHost`, improve logic where relevant/possible and test (0d) - @VakarisZ
