### ISSUE TITLE
Implement exploitation in Puppet

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1605]
Implement the `exploit_host()` function of the concrete Puppet. Modify the Master to pass the appropriate options to the exploiters (i.e. propagation credentials). The `smb` exploit may require additional options.

**Note**
There's currently a bug where MSSQL exploiter can fail to propagate and prevent other exploiters from running. We can most likely resolve this by having each exploiter return two booleans, one to indicate whether or not the victim is vulnerable and another to indicate whether or not propagation was successful. This would also let us simplify the exploiters config, which now have a true/false field to indicate whether or not an exploiter is capable of propagating.

## Tasks

- [x] Modify config to remove boolean "propagator" field from config (0d) @ilija-lazoroski 
- [x] Add a periodic check (between hosts and/or between exploiters) to get updated credentials from the Island (0d) @mssalvatore 
- [x] Pass other WormConfig settings as options (0d) @ilija-lazoroski 
    - [x] Target dropper paths
    - [x] Pass credentials as options to exploiters (See #1721 for a starting point)
- [x] Copy commonly used functions on WormConfig to a utils/tools module and add tests (0d) @mssalvatore
    - [x] get_exploit_user_password_or_hash_product()
    - [x] get_exploit_user_ssh_key_pairs()
    - [x] get_exploit_user_password_pairs()
- [x] Modify ExploitResultData (0d) @shreyamalviya
    - [x] Add OS
    - [x] Add `exploit_successful`
    - [x] Add `propagation_successful`
    - [x] Modify mock_puppet
- [x] Remove `skip_if_exploit_file_exists` option from config (0d) @shreyamalviya
- [x] SSH (0d) @ilija-lazoroski 
    - [x] Don't modify VictimHost object
    - [x] Change attempt logging and remove credential hashes from log statements
    - [x] Return ExploitResultData
    - [x] Call new `get_exploit_user*()` functions instead of `self._config.*()`
    - [x] Accept ITelemetryMessenger in `__init__()` and use it to send telemetries
- [x] Hadoop (0d) @shreyamalviya 
    - [x] Remove code that sets architecture from web_rce.py
    - [x] Return ExploitResultData
    - [x] Accept ITelemetryMessenger in `__init__()` and use it to send telemetries
    - [x] Wrap ~Struts~Hadoop with wrapper and load into the puppet in `monkey.py`
- [x] Remove dependency on `Plugin` from `HostExploiter` (0d) @mssalvatore 
- [x] Implement `exploit_host()` in `Puppet` (0d) @mssalvatore 
    - [x] Add a wrapper around Exploiters that accepts the necessary parameters for exploitation and object construction (VictimHost, Telemetry messenger, options)
