### ISSUE TITLE
Make exploiters interruptible

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1611]
Modify long-running exploiters so that they can be interrupted/terminated at strategically chosen points in their execution. Make sure any blocking function call has a reasonable timeout.

# Tasks:
- [x] Exploiters need to accept interrupt (threading.Event) (0d) - @VakarisZ 
- [x] WMI exploiter (0d) - @VakarisZ 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] MSSQL exploiter (0d) @mssalvatore 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] Powershell exploiter (0d) - @VakarisZ 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] Zerologon exploiter (0d) @ilija-lazoroski 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] SSH exploiter (0d)- @ilija-lazoroski 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
  - [x] Open a PR for paramiko to pass a timeout so we're not forced to wait for 1h upon interrupt - @VakarisZ 
  - [x] Linux build fails on jenkins due to failure to install paramiko - @mssalvatore 
- [x] Hadoop exploiter (0d) @ilija-lazoroski 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] Log4Shell (0d) - @VakarisZ 
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
- [x] SMB exploiter (0d) @mssalvatore
  - [x] Slow loops use `interruptable_iter()`
  - [x] Identify different steps in each exploiter and decide whether or not to check for interrupt before each step
  - [x] Ensure all blocking operations have appropriate timeouts
