### ISSUE TITLE
Inspect timeouts in PBAs

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1650]
Inspect each PBA plugin for any blocking function calls. Ensure any blocking function calls have a reasonable timeout. Prevent any condition which could cause the PBA to hang indefinitely.

Many PBAs use python's `subprocess` module to run commands. Consider killing these subprocess after a timeout.

The Custom PBA is a special case. Ensure it can be killed if the stop signal is received.

The pba.py should have a failsafe to kill the subprocess if the stop signal is received.

## Tasks
All PBAs should execute in < 15 seconds

* [x] Investigate timeouts in PBAs
    * [x] PBA base class - @shreyamalviya (0d)
    * [x] Clear Command History (subprocess) @ilija-lazoroski (0d)
    * [x] Signed Script Proxy Execution (subprocess) - @shreyamalviya (0d) 
    * [x] Account Discovery - @VakarisZ (0d)
    * [x] Communicate as Backdoor User (subprocess) - @VakarisZ (0d)
    * [x] Modify Shell Startup Files (subprocess) (0d) - @VakarisZ
    * [x] Process List Collector (0d) @ilija-lazoroski 
    * [x] Job Scheduling (subprocess) (0d) @ilija-lazoroski 
    * [x] utils/{linux,windows}/users.py (0d) - @shreyamalviya
