### ISSUE TITLE
Revisit the flattening/unflattening of the Agent config.

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1662]
The Monkey Island "flattens" the agent config before sending it to the agent. In #1597, much of this config needs to be unflattened and organized into a way that groups related settings to prepare for a world where Infection Monkey supports plugins. We should consider 2 things:

1. Don't flatten the config at all
2. Define an object/dataclass in `common` that the Island can use populate the config and the Agent can use to parse the config.

## Revised Scope
For this issue, we'll just focus on unflattening the config. The config object will be handled in #1960

## Tasks

- [ ] Update any code that relies on the ConfigService to use the configuration repository/new configuration object
    - [x] resources/pba_file_upload.py (0d) @mssalvatore 
    - [x] services/database.py (0d) @mssalvatore 
    - [ ] services/configuration/utils.py (0.25d) - @shreyamalviya 
        - [ ] services/telemetry/zero_trust_checks/segmentation.py
        - [x] services/reporting/report.py (only fix the code that uses get_config_network_segments_as_subnet_groups())
    - [ ] services/reporting/report.py (0.25d) @mssalvatore 
- [ ] Remove ConfigService (0.25d) - @shreyamalviya
