### ISSUE TITLE
Remove 32-bit Agents

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1675]
Continuing to support 32-bit systems is putting a lot of drag on the development process. The 32-bit binaries increase download times, increase build times, add complexity to the logic, and are largely untested. They may be riddled with bugs and we have no way of knowing (i.e. no automated testing).

Discontinue 32-bit support by removing the 32-bit agents and any logic related to them.

## Tasks

- [x] Disable Jenkins 32bit jobs (0d) @mssalvatore 
- [x] Edit `monkey.spec` files (0d) @mssalvatore 
- [x] Modify documentation (0d) @shreyamalviya 
- [x] Modify Hadoop and supporting code to strip all 32bit reference (0d) @shreyamalviya 
- [x] Decouple exploiters from moneyfs and ControlClient (0d) @mssalvatore 
  - [x] Simplify and optimize process of downloading agents from Island
  - [x] Add IAgentRepository to exploiters
- [x] Modify SSH and supporting code to strip all 32bit reference (0d) @mssalvatore 
- [x] Remove `upgrade_to_64bit` in `monkey.py` (0d) @mssalvatore 
- [x] Remove 32bit specific settings in configuration (0d) @ilija-lazoroski 
- [x] Remove 32bit options on RunMonkeyPage (0d) @ilija-lazoroski 
- [x] Modify `build_scripts` to remove 32bit binaries 
  - [x] AppImage (0d) @mssalvatore 
  - [x] Docker (0d) @mssalvatore
  - [x] MSI (0d) @ilija-lazoroski 
- [x] Modify `deployment_scripts` to remove 32bit binaries
   - [x] Linux (0d) @mssalvatore
   - [x] Windows (0d) @mssalvatore
