### ISSUE TITLE
Remove the agent bootloader

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1676]
## Description
Infection Monkey agents are built with PyInstaller. PyInstaller includes a small binary called a bootloader that's tasked with bootstraping the binary. Infection Monkey has a custom bootloader whose goal is to provide a minimal amount of feedback in the event that it runs on a system that's so old it can't support the PyInstaller binary. This has a few drawbacks:

1. The bootloader code (written in C) is full of mismanaged memory. Sometimes these memory errors cause bugs that are difficult to diagnose.
2. We maintain a fork of PyInstaller in order to use the custom bootloader.
3. The bootloader is an extra step in agent startup that can sometimes cause delays of 1 minute or more per victim.
4. It exists only to support legacy systems, most of which are no longer supported by the manufacturer.

At this time, the effort to rebuild the bootloader to alleviate some of these issues is not worth the cost. Remove the bootloader; we can add a similar feature back in later if the need arises.

## Tasks
- [x] Change `Pipfile` to use upstream pyinstaller (0d) - @shreyamalviya 
- [x] Update documentation (0d) - @shreyamalviya 
- [x] Remove bootloader endpoints and services from Monkey Island (0d) @ilija-lazoroski, @shreyamalviya 
  - [x] Update mongo queries
  - [x] Remove bootloader server
  - [x] Remove bootloader telemetry
  - [x] Revert the changes that set the node's IP and OS from the bootloader telemetry
- [x] Modify the UI's "starting state" logic so it doesn't depend on the bootloader (0d) - @shreyamalviya 
- [x] Run lots of tests (0d) @ilija-lazoroski 
- [x] Update the release test template (0d)

## Notes
Don't waste any time worrying about the 32-bit binaries, since they will be removed in #1675

**Comment by mssalvatore** [comment]
Resolving this issue would also resolve #1039.

**Comment by acepace** [comment]
@mssalvatore if you drop this, do you want the matching feature to detect we're attacking a really old machine that obviously shouldn't be online?

**Comment by mssalvatore** [comment]
@acepace Nah. There are a couple of approaches to that, and we haven't decided exactly what we'll do yet. My main goal at the moment is to speed up the development process as much as possible, and this feature is more effort to maintain than it's worth. At some future time, we'll reevaluate our approach to supporting legacy systems.
