### ISSUE TITLE
Credential collectors

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1695]
**Is your feature request related to a problem? Please describe.**
System info collectors are being refactored into more specific components. 

**Describe the solution you'd like**
Refactor `monkey\infection_monkey\system_info\SSH_info_collector.py` and `C:\Users\vzilius\Desktop\infection_monkey\monkey\infection_monkey\system_info\windows_cred_collector` into credential collectors component.

![credential_collectors4 vpd](https://user-images.githubusercontent.com/36815064/152543467-37a33d68-da5d-4eb8-9c2d-fc5a056d8692.jpg)

### Resources
Refer to https://github.com/guardicore/monkey/issues/1672 to see iterations of the design and reasons why this is being done. Also, @mssalvatore left a good snippet there:
![image](https://user-images.githubusercontent.com/36815064/152545167-564a0cba-5a76-48bf-8040-1f9a75e8681f.png)

### Tasks

- [x] Create `ICredentialComponent`, `Credentials`, `ICredentialCollector` (0d) - @VakarisZ 
- [x] Refactor `MimikatzCollector` to use the `ICredentialCollector` interface (SSH collector can be done first instead, but do only 1). Implement required credentials to extend `ICredentialComponent` (0d) - @VakarisZ 
    - [x] Add unit tests 
- [x] Implement `CredentialTelemetry`, ??`Serializer` and `CredentialSerializer`?? objects. Make sure master sends serialized credential telemetries (0d) @mssalvatore 
- [x] Refactor island to parse `CredentialTelemetry` the same way system info credential was parsed. (0.5d) - @VakarisZ 
    - [x] Ensure special characters are properly handled by mongo https://github.com/guardicore/monkey/blob/98a2f0b88712ed5f1577f25b3ecd93addf155f5c/monkey/infection_monkey/system_info/windows_cred_collector/mimikatz_cred_collector.py#L18-L23
- [x] Refactor `SSHCollector` to use the `ICredentialCollector` interface. Implement required credentials to extend `ICredentialComponent` (0d) @ilija-lazoroski 
- [x] Resolve #1720 (0d)
- [x] Don't log sensitive credentials contents when telemetry is sent (0d)
- [x] Test UI manually (0.25d)
