### ISSUE TITLE
Refactor AWS collector

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1696]
**Is your feature request related to a problem? Please describe.**
System info collectors are being refactored.

`Agent` (`monkey.py`) should gather information about its environment. 

**Describe the solution you'd like**

For now, it's best to just send the telemetry with the required AWS info if it's running on AWS from the agent.

Pseudocode:

monkey.py:
```
    def start(self):
        ...

        should_stop = ControlChannel(WormConfiguration.current_server, GUID).should_agent_stop()
        if should_stop:
            logger.info("The Monkey Island has instructed this agent to stop")
            return

        if InfectionMonkey._is_upgrade_to_64_needed():
            self._upgrade_to_64()
            logger.info("32 bit Agent can't run on 64 bit system.")
            return



        if running_on_aws():
                report_aws_env()



        self._setup()
        self._master.start()
```

aws_environment_check.py
```
def running_on_aws():
    return AwsInstance().is_instance()

def report_aws_env():
    EnvironmentTelemetry(AwsInstance())
```

## Resources:
System info collector refactoring issue : https://github.com/guardicore/monkey/issues/1672

## Tasks:
- [x] Create an environment checking infrastructure and use it from the master. (0d) @ilija-lazoroski 
    - [x] Send a new AWSInstanceTelemetry if running on AWS
    - [x] Handle AWSInstanceTelemetry on the Island
- [x] Test AWS (0d) @ilija-lazoroski
