### ISSUE TITLE
Impacket KeyError when running WMI after Zerologon

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1774]
## Describe the bug
If the Zerologon exploiter is run before the WMI exploiter, errors occur in the the WMI exploiter when attempting to connect/disconnect to the victim using impacket. This doesn't appear to affect functionality, as the WMI exploiter is still able to authenticate to the victim when the correct credentials are used.

## To Reproduce
1. Configure a machine to be exploitable with Zerologon and WMI
2. Configure Infection Monkey to use the Zerologon and WMI exploiters
3. Run the monkey agent
4. View errors in the logs.

## Screenshots
![image](https://user-images.githubusercontent.com/19957806/157724122-3a48a596-102e-43e6-80d0-752349364152.png)

## Code that triggers errors
https://github.com/guardicore/monkey/blob/dd2168e8383edaab3b8b436437338f0f08b2368e/monkey/infection_monkey/exploit/tools/wmi_tools.py#L52-L75

## Tasks
- [x] Investigate and maybe fix 0d - @cakekoa

**Comment by mssalvatore** [comment]
This might be fixed if we resolve https://github.com/guardicore/monkey/issues/1852

**Comment by mssalvatore** [comment]
> It [threaded plugin prototype] appears to allow the plugins to run in parallel -- the log statements are all interleaved for all exploiter threads. I did see a manifestation of [this error](https://github.com/guardicore/monkey/issues/1774), with the following observations:
>  - It does not need zerologon to run at all in order to occur
>  - It only occurs when attempting to exploit the zerologon machines using WMI
>  - It only occurs when using a username other than "user"

### Goals

Investigate the possibility that this error has nothing to do with running plugins concurrently. Is this related to some configuration on the zerologon target machine?

Configure two agents on two different machines to attack the zerologon target simultaneously. One can use WMI and the other can use zerologon. Does either agent produce the error?

### Time remaining

1.25d

**Comment by cakekoa** [comment]
Notes:
- Reproduce:
    - Zerologon and WMI exploiters
        - Perhaps only needs WMI exploiter
    - Only need a single machine
    - Use large number of passwords and accounts
    - Run the agent and island and observe the agent logs
    - Note: Can’t use both linux island machines, as they have the same hardware ID
- Observations:
    - The problem seems to be two threads running dcerpc requests simultaneously
    - This problem seems to have something to do with zerologon not cleaning up after itself
- Tests:
    - [x] Investigate if it is related to configuration on the zerologon machine
    - [x] Investigate if it can be reproduced running two agents against the zerologon target simultaneously
- Procedure:
    - [x] Generate a configuration file
    - [x] Verify that we can reproduce the original issue
    - [x] Verify that it doesn’t happen serially
    - [x] Try running two agents simultaneously (different machines because of singleton)
        - [x] Using WMI
            - Result: No issues
        - [x] Using Zerologon
            - Result: No issues
    - [x] Try fiddling with zerologon machine configuration
        - [x] Try RDPing into the zerologon machine
        - [x] Check which accounts are on the machine
            - Administrator and m0nk3y are valid accounts. Both are in Administrators group. m0nk3y is also in Users group
            - user is not a valid account
        - [x] Fiddle with he registry setting
    - [x] Check if the issue can be reproduced without the user user
        - Yes, it happens a LOT
    - [x] Check if the issue can be reproduced with only the user user
        - Yes, it happens a LOT
    - [x] Check the impacket version
        - 0.10.0
    - [ ] Check if running zerologon in series causes the issue to occur (I.e., does zerologon not cleanup after itself?)
        - [x] Configure the system for zerologon
        - [ ] Update the propagator _exploit_hosts() to run the exploiter twice
        - [x] Update exploiter _run_all_exploiters() to run each exploiter twice
        - Result: No issues
    - [x] Run zerologon, WMI from two separate machines (hard-code the exploiters). Modify exploitation_config passed into infection_monkey/master/exploiter.py:exploit_hosts()
        - [x] For zerologon: set .vulnerability to (PluginConfiguration(name=“ZerologonExploiter”, options={}),)
        - [x] For WMI, set .brute_force to (PluginConfiguration(name=“WmiExploiter”, options= {'smb_download_timeout': 30}))
        - Result: No issues

**Comment by mssalvatore** [comment]
As expected, it seems that the move to plugins resolves this issue.
