### ISSUE TITLE
Fix BB tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1801]
# Summary
After the agent refactor, BB tests don't work. Fix them.

Use branch [1801-fix-blackbox-tests](https://github.com/guardicore/monkey/tree/1801-fix-blackbox-tests).

## Tunneling test
Tunnels are not quit properly, which results in long delays in the tunneling test
![image](https://user-images.githubusercontent.com/19957806/159565738-fdd29045-8bfe-4238-9913-dc319e425634.png)

## Zerologon test

There is a race condition that prevents the Zerologon test from passing consistently. The Zerologon exploiter collects credentials and sends them to the island. The master pulls credentials from the Island before each exploiter, but the results of the request are cached to prevent excessive polling of the island. If the Island hasn't finished processing Zerologon's telemetry, or the master pulls a cached result from the Island, SMBExploiter will not be able to exploit the victim.

To solve this, we can create a new `ITelemetryMessenger` decorator to intercept credentials telemetry and give them to the `AutomatedMaster`. The `AutomatedMaster` can then combine the results of `ControlChannel.get_credentials_for_propagation()` with credentials it has intercepted. See `MonkeyTunnel` and `ExploitInterceptingTelemetryMessenger` for an example.

## Remove bogus Island
A default Island IP is added to every agent.
https://github.com/guardicore/monkey/blob/ad61236ed09bf7bb63b401e6ec8f3dbf9dba0597/monkey/infection_monkey/config.py#L118-L119
During the tunneling test, this adds approximately 60 seconds to the test run while agents attempt to access this bogus server.

Remove it.

## Tasks

- [x] Remove bogus island (0d) @mssalvatore
- [x] Fix tunneling test (0d) @mssalvatore 
- [x] Remove the smb-20 machine from GCP, terraform scripts, and documentation (0d) - @VakarisZ 
- [x] Fix Zerologon race condition @ilija-lazoroski 
  - [x] Create `ICredentialsStore` that provides `get_credentials()` and `add_credentials()` (0d)
  - [x] Create a concrete credentials store that uses the ControlChannel to query the Island for credentials. (0d) 
  - [x] Inject credentials store into AutomatedMaster (0d)
  - [x] Create `CredentialsInterceptingTelemetryMessenger` that intercepts credentials and adds them to an `ICredentialsStore` (0d)
  - [x] Inject `CredentialsInterceptingTelemetryMessenger` into `ZerologonExploiter` and `AutomatedMaster` (0d)
  - [x] Run Zerologon BB test (0.25d)
- [x] Modify `ExploitInterceptingTelemetryMessenger` to only set wait on tunnel if propagation succeeded (0d) @mssalvatore 
- [x] Run 1.13.0 tests and agent-refactor tests and compare run times (0.25d)
