### ISSUE TITLE
Upgrade Node.js to v18

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1830]
## Description
Node.js v12 is end-of-life on 2022-04-30. We can no longer build our UI with v12. Upgrade Node.js to the latest supported version (v18, released 2022-04-19).

## Tasks
- [x] Update deployment scripts (0d) - @VakarisZ 
- [x] Build UI with node.js v18 (0d)
- [x] Upgrade dependencies (0d) -> @VakarisZ 
- [x] Exhaustively test the UI (0d) -> @VakarisZ 
- [x] Resolve #1857 (0.25d) -> @VakarisZ

**Comment by VakarisZ** [comment]
Updated to node 16 and closed
