### ISSUE TITLE
Telemetry overview bugs

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1850]
## Describe the bug
Telemetry overview not loading with too many telemetries and there are redundant scanning telemetries.
When scrolled up, it jumps down to the last telemetry on its own.
Telemetry overview display line counter is off:
![image](https://user-images.githubusercontent.com/36815064/161532576-e2fca977-d806-4968-8f54-19600a3e3455.png)

## To Reproduce
Display not loading: 
1. Configure the Monkey to scan local network
2. There are redundant scanning telemetries and the quantity of telemetries overwhelm the display?

Scroll jumping:
1. Scroll up and wait. It jumps down after a few seconds.

Counter off:
1. Should happen with any configuration

# Task

- [ ] Fix it (0.25d)
  - [x] Fix logic to say `22/22` when scrolled all the way down instead of `18/22`. - @shreyamalviya 
  - [ ] Fix automatic jumping to the last telemetry. It should stay where the user has scrolled. @ilija-lazoroski 
  - [x] Fix position of the counter to be inside the telemetry overview window's border. - @shreyamalviya 
  - [x] Remove redundant scanning which generates too many telemetries. - @shreyamalviya 

## Machine version (please complete the following information):
 - OS: Windows and Linux
