### ISSUE TITLE
Remove stale exploiters

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1869]
Officially remove stale/obsolete exploiters.

- Drupal - This exploiter only affects Drupal 8, which has been EOL since November 2021
- Struts - This vulnerability has been patched since March 2017
- Weblogic - This vulnerability has been patched since October 2017

## Tasks

- [x] Completely remove the Drupal exploiter code (0d) - @shreyamalviya 
    - [x] Remove any disused code
    - [x] Remove any disused dependencies
- [x] Completely remove the Struts exploiter code (0d) - @ilija-lazoroski 
    - [x] Remove any disused code
    - [x] Remove any disused dependencies
- [x] Completely remove the Weblogic exploiter code (0d) - @ilija-lazoroski 
    - [x] Remove any disused code
    - [x] Remove any disused dependencies
