### ISSUE TITLE
Integrate systemd unit installation script into AppImage package

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1883]
## Description
PR #1862 adds a deployment script that allows the AppImage package to be installed as a service and run on boot. This involves distributing both the AppImage and the installation script to the user. A better user experience would be if the AppImage package were self installing. Usage would look like:

```
$ ./InfectionMonkey-vX.Y.Z.AppImage service --install --user myuser
$ ./InfectionMonkey-vX.Y.Z.AppImage service --uninstall
```

## Tasks

- [x] Move `deployment_scripts/install-infection-monkey-service.sh` to `build_scripts/appimage/`
- [x] Modify the AppImage build script to include `install-infection-monkey-service.sh` in the AppImage
- [x] Add installation instructions to `docs/content/setup/linux.md`. (0d) - @shreyamalviya 
- [x] Update the documentation for creating Azure and AWS images. (0d) - @shreyamalviya 
- [x] Modify `AppRun` to check for the `service` argument and invoke the `install-infection-monkey-service.sh` script, passing the remaining arguments. (0d) @mssalvatore
- [x] Modify `install-infection-monkey-service.sh` to use the [`$APPIMAGE` environment variable](https://docs.appimage.org/packaging-guide/environment-variables.html) rather than accepting a `--path` parameter.

**Comment by GC-Elia** [comment]
Hey @mssalvatore , a couple questions
1. In case the AppImage is called with `service` argument, is it expected to exit immediately after installing/uninstalling, or continue execution on installation?
2. Any preferred path inside the AppImage or just `/squashfs-root/install-infection-monkey-service.sh` as it isn't related to anything in `/usr` or `/opt`

**Comment by mssalvatore** [comment]
@GC-Elia Good questions!

1. It should exit after installing/uninstalling.
2. I think `/squashfs-root/install-infection-monkey-service.sh` should be fine.
