### ISSUE TITLE
Finish implementing InnoSetup windows installer

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1911]
**Is your feature request related to a problem? Please describe.**
Finish implementing Inno Setup installer for InfectionMonkey.
Use `monkey-inno-setup` branch in labs: https://github.com/guardicore/labs/commit/6eb727ecc110417b999bf2340a591db808468b99

OR here's a link for a standalone zip: https://guardicore-infectionmonkey.s3.amazonaws.com/Files/tmp/inno.zip

## WARNING
Make a snapshot of the GCP build node before making any modifications

## Tasks
- [x] Get build/prototype working on the GCP build node (0d) @cakekoa 
- [x] Add a jenkins build to build with InnoSetup (0d) @cakekoa 
- [ ] Properly include all data files. Files like `/monkey_island/cc/setup/mongo/attack_mitigations.json` were not accessed from pyinstaller directory. The advanced installer just copied the whole project and it resulted in these files being accessible not from pyinstaller, but from copied source dirs. (https://github.com/guardicore/monkey/issues/1328) (0.25d) @ilija-lazoroski 
- [x] Find a way to only add relevant files (binaries/mongodb files could be extracted during installation or be part of pyinstaller) (i.e. fix https://github.com/guardicore/monkey/issues/1328) (0d)
- [x] Fix license and readme (0d)
- [x] Improve the "launch on startup" option (0d)
- [x] Fix the windows, icons and colors (0d)
- [x] Add shortcut to the desktop (0d) @ilija-lazoroski 
- [x] Other utility/unplanned work (like proper naming, version string, changing labs scripts) (0d)
- [x] Experiment and find the best compression algorithm to balance speed and size (0d)

**Comment by mssalvatore** [comment]
This is a follow-up issue for #1907
