### ISSUE TITLE
Fix broken ETE Tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1921]
The tunneling test is failing, 10.2.0.11 failed to call back. This is likely an issue of depth and firewall rules.

Sometimes the zerologon test still fails

Windows tests don't run at all.

## Tasks
- [x] Fix mssql test test (d) @mssalvatore 
- [x] Fix zerologon (0d) @mssalvatore 
- [x] Fix windows (log4shell .51) ete test (0d) @ilija-lazoroski, @mssalvatore 
- [x] Fix any tests that still fail (0d) @mssalvatore

**Comment by ilija-lazoroski** [comment]
Maybe #1917 is the reason for some of them.

**Comment by mssalvatore** [comment]
The log4shell tomcat test was failing because the tomcat service on Linux took a very long time to start. Commit 8ec1bb972 documents the fix for this issue.

>The jvm's `java.security.egd` variable should be set to `/dev/urandom`,
otherwise the tomcat service can take a very long time to start. Set this by
editing `/usr/share/bin/catalina.sh` and modifying the `JAVA_OPTS` vairable.
See https://jfrog.com/knowledge-base/tomcat-takes-forever-to-start-what-can-i-do/
for more details.

**Comment by mssalvatore** [comment]
Issue https://github.com/guardicore/monkey/issues/1923 was the cause of the zerologon failures/slowness. It's been resolved by modifying GPOs and disabling SMB signing. A new disk image named zerologon-25-fast has been created to incorporate these changes.

**Comment by mssalvatore** [comment]
Tomcat sessions were persisting across reboots. Details on fixing it can be found in Commit 61793d56cf46
