### ISSUE TITLE
Upgrade MongoDB

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1924]
The Linux and Windows build scripts are pulling old versions of MongoDB 4.2. Modify the scripts to pull the latest version (4.2.19).

## Tasks

- [ ] Upgrade MongoDB for AppImage build (0.25d) - @shreyamalviya 
- [ ] Upgrade MongoDB for Windows build (0.25d) - @shreyamalviya 
    - [x] Write a script similar to the Linux script for downloading MongoDB
    - [x] Strip everything except the mongod binary and the license file
