### ISSUE TITLE
Refactor aws_service

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1928]
## Summary

While fixing #1636, a new `aws_service` was added as a short-term measure. This service is not wholly necessary as written, but can be modified and combined with `RemoteRunAwsService` to provide one cohesive interface. Replace the current `aws_service` with a new `AWSService` and use the new dependency injection container to inject a fully-populated `AWSInstance` object or `AWSService` into any other service or resource that requires them.

## Tasks
- [x] Rename `AwsInstance` to `AWSInstance` (0d) @mssalvatore
- [x] Move the threading `Event` logic from `aws_service` to `AWSInstance` (0d) @mssalvatore
    - [x] Use a `Thread` in the constructor of `AWSInstance` to initialize its properties/attributes 
    - [ ] ~Modify the agent to no longer use a `Thread` to construct an AWSInstance~
- [x] Construct the `AWSInstance` in the Composition Root and add it to the DI Container (0d) @mssalvatore 
- [x] Modify `aws_service` to be stateful and: (0d) @mssalvatore
    - [x] Accept an `AWSInstance` in its constructor (0d)
    - [x] Provide an `instance` property that allows the caller to retrieve the `AWSInstance` (0d)
    - [x] Provide a `get_instances()` function that allows the caller to retrieve a list of known aws instances. Consider using a better/clearer name. (0d)
    - [x] Provide a (stub) `run_agent_on_remote_instance()` function that allows the caller to run an agent on a remote AWS instance. This will wrap the functionality currently provided by `RemoteRunAwsService` (0d)
- [x] Migrate the functionality provided by `RemoteRunAwsService` to `AWSService`  (0d) @mssalvatore, @VakarisZ 
    - [ ] ~Pass the `AWSInstance` to the constructor of `AwsCmdRunner`~
    - [ ] ~Rename `AwsCmdRunner` to `AWSCommandRunner`~
    - [ ] ~Remove `AWSCommandRunner`'s dependency on the `AwsService`~
    - [x] Replace AwsCmdRunner with a simpler solution
- [x] Modify the `RemoteRun` resource to use the new `AWSService` (0d) @mssalvatore, @VakarisZ 
    - [x] Accept the `AWSService` in the constructor
    - [x] Call `AWSService.get_instances()` in `get()`
    - [x] Call `AWSService.run_agent_on_remote_instance()` in `post()`
    - [x] Test on AWS
- [ ] Remove `ReportExporterManager` (0.75d) - @VakarisZ 
    - [ ] Add a static `initialialize()` method to `ReportService` and initialize it with the `AWSService`
    - [ ] `AWSExporter` may not need to be stateful. Either modify it to be a collection of functions that accept an `AWSInstance`/`AWSService` or modify it to be a proper class that accepts an `AWSService` in its constructor.
    - [ ] Add logic to `ReportService` to run `AWSExporter` if running on an AWS instance.
    - [ ] Test report export on AWS

## Notes
Branch off of the `1928-aws-service-refactor` branch for each subtask/PR.
