### ISSUE TITLE
Define endpoint URLs on Resource classes

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1943]
As we continue to refactor services and resources, we're able to use dependency injection and test the resources in isolation. Doing causes the endpoint URLs to be duplicated in `app.py` and the unit test. Define the endpoint URLs as class variables on the resources so they're only defined in one place.

Add a mechanism to prevent duplicate URLs from being registered.

## Tasks
- [ ] Determine the best datastructure to store the URLs. It should allow URLs to be retrieved by a meaningful name, and also allow them to easily be passed to the `add_resource()` method. (0d) - @VakarisZ 
- [ ] Create a mixin or interface to enforce that all resources have a `url` class variable (0.25d)
- [ ] Modify `app.py` and unit tests to use new url class variable (0.25d) - @VakarisZ 
- [ ] Add a mechanism to prevent duplicate URLS from being registered. (0.d) -@VakarisZ
