### ISSUE TITLE
Establish a standard for docstrings

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1952]
## Description
We'll be using sphinx to document our code. Sphinx uses docstrings to generate documentation. We need to establish a set of rules and best practices for writing our docstrings. These rules are already established by the community, but we need to summarize them and tweak them for our own usage. For example, the sphinx documentation instructs you to add types to variable descriptions, but perhaps we can use https://pypi.org/project/sphinx-autodoc-typehints/ instead.

## Resources
https://peps.python.org/pep-0257/
https://www.sphinx-doc.org/en/master/

## Tasks
- [ ] Research docstring formats and chose one that is compatible with sphinx. Document this format in the developer standards and practices guide (0.25d) @ilija-lazoroski 
- [ ] Add sphinx to the project (0.25d) @ilija-lazoroski 
  - [x] Add or modify any files (pipfiles, pyproject.toml, etc) to enable sphinx
  - [x] Configure sphinx to generate documentation from our docstrings
  - [x] Update README.md with instructions on how to run sphinx.
