### ISSUE TITLE
Migrate Windows build to GCP

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1959]
A new instance has been added to GCP for Windows builds. Use it!

## Tasks
- [x] Document how to access the actual machine (0d)
- [x] Agent
  - [x] Configure windows agent build job in jenkins to use the GCP node -> @??????
  - [x] Verify that agent builds successfully -> @VakarisZ 
- [x] Island (0d) - @VakarisZ 
  - [x] Configure the Windows Island build job in jenkins to use the GCP node
  - [x] Modify AdvancedInstaller to skip the signing step
  - [x] Add a new job to sign the windows MSI on the old, signing node
  - [x] Run windows ETE tests and fix any issues
- [x] Inspect docker Island build and make sure it cleans up stale containers and images (0d) @ilija-lazoroski 
- [x] Remove `squashfs-root/` directory after appimage build (0d) @ilija-lazoroski
