### ISSUE TITLE
Decouple credentials and configuration

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1965]
## Description

Managing propagation credentials presents an interesting challenge. Some credentials are configured, while others are stolen. Currently, configured credentials are part of the configuration, and stolen credentials get added to the configuration. This introduces complexity, since the island has to keep track of per-agent configurations and initial configs vs. the config that gets modified during runtime.

Configuration should be static while agents are running! As part of the agent refactor project, the agent now ignores the credentials in the configuration and requests propagation credentials from a separate endpoint. From the agent's point of view, it doesn't care if credentials were stolen or configured; it just needs to use them.

Decouple credentials and configuration. Allow the user to configure credentials as always, but the UI should submit them to a separate endpoint from configuration. Implement the `ICredentialsRepository` to store collected credentials in MongoDB. The `ICredentialsRepository` should make it simple for the caller to retrieve all credentials, just those credentials that were stolen (for example, by mimikatz), or just those credentials that the user configured. Modify the existing telemetry processor and retrieval endpoint to store and retrieve credentials from the `ICredentialsRepository`. Modify configuration import/export to have a new format containing the "config" and configured credentials.

## Tasks
- [x] Modify `IStolenCredentialsRepository` (0d) @ilija-lazoroski 
    - [x] Rename to `ICredentialsRepository`
    - [x] Add `{get,save}_configured_credentials()`
    - [x] Add `get_all_credentials()`
    - [x] Add docstrings
        - [x] Return appropriate `{Retrieval,Storage,Removal}Errors`
    - [x] Add `remove_{configured,stolen,all}_credentials()`
- [x] Credential serialization (0d) - @mssalvatore 
- [x] Implement a `MongoCredentialsRepository` that stores credentials (0d) @ilija-lazoroski 
    - [x] Modify the interface to accept a sequence of credentials when storing
- [x] Encrypt/decrypt the secrets in the `MongoCredentialsRepository (0d) @mssalvatore 
- [x] Add `/api/propagation-credentials/stolen` (0d) @VakarisZ 
    - [x] Define GET
    - [x] Define POST
    - [x] Define DELETE
- [x] Add `/api/propagation-credentials/configured` (0d) @VakarisZ 
    - [x] Define GET
    - [x] Define POST
    - [x] Define DELETE
- [x] Add `GET /api/propagation-credentials` that returns all types of credentials ie two collections (0d) @VakarisZ 
- [x] Add `DELETE /api/propagation-credentials` that removes two sub-collections: stolen and configured credentials (0d) @VakarisZ 
- [x] Modify credentials telemetry processor to use `ICredentialsRepository` (0d) @ilija-lazoroski 
- [x] Modify the UI to submit usernames, passwords, NTLM hashes, and SSH keys to `/api/propagation-credentials/configured` (0.25d) @VakarisZ 
    - [x] Add a new form that allows the user to add the above credentials
    - [x] Add the form to the "Propagation" tab, or a new tab, whichever seems better
- [x] Modify reports to get credentials from `GET /api/propagation-credentials` (0d) - @ilija-lazoroski 
    - [x] Modify the backend report to not include credentials
    - [x] Modify the UI to get credentials from the API and add them to the report
- [x] Modify `/api/clear-simulation-data` to clear stolen credentials (0d) - @shreyamalviya 
- [x] ~Add `/api/reset-configured-propagation-credentials` (0.0d) - @shreyamalviya~
    - [x] ~Call from the UI when configuration is reset~
- [x] Use DELETE /api/propagation-credentials/configured in the UI when configuration is reset (0d) - @shreyamalviya
