### ISSUE TITLE
Refactor MonkeyDownload resource

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1974]
# Refactor

## Component(s) to be refactored

- `monkey_island.cc.resources.monkey_download.MonkeyDownload`

## Explanation
There's too much business logic in the `MonkeyDownload` resource. Additionally, it's not defined according to our REST guidelines. The resource should simply retrieve the binaries from a repository with a simple interface.
## Tasks
- [x] Rename `MonkeyDownload` to have a proper collection resource name like `AgentBinaries` (0d) - @shreyamalviya 
- [x] Change the URL for the `AgentBinaries` resource to be consistent with our REST guidelines (`/api/agent-binaries/<string:os/>`) (0d) - @shreyamalviya 
    - [x] Modify Island
    - [x] Modify Agent
    - [x] Test
- [x] Export `AgentBinaries` from the `resources` package (0d) @ilija-lazoroski 
    - [x] Edit `app.py` to use the shorter import
- [x] Create an `IAgentBinaryRepository` that allows the caller to get the Linux or Windows binary. It should have functions like `get_linux_binary() -> typing.BinaryIO`. (0d)
- [x] Construct a concrete `AgentBinaryRepository` that utilizes an `IFileRepository`. (0d) @ilija-lazoroski 
    - [x] Construct an `LocalStorageFileRepository` just for the `AgentBinaryRepository` to use. Do not add the `LocalStorageFileRepository` to the DI container
    - [x] Construct the `AgentBinaryRepository` with the`LocalStorageFileRepository` in the composition root.
    - [x] Add the `AgentBinaryRepository` to the DI container
- [x] Log the executible hashes when the `AgentBinaryRepository` is constructed. This should be done when the system is initialized, not the resource or repository. (0d) @ilija-lazoroski 
- [ ] Refactor the `AgentBinaries` resource to use the concrete `AgentBinaryRepository` (0.5d) @ilija-lazoroski
