### ISSUE TITLE
Remove `current_server` from the configuration

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1996]
# Refactor

## Component(s) to be refactored

- configuration

## Explanation
The agent's configuration includes an option called "current_server". This is not configuration information, but state.

## Tasks
- [ ] Remove the "current_server" option from the configuration. (0.25d) @ilija-lazoroski 
  - [ ] Fix any agent code that relies on it
- [ ] If any Island code relies on this value (attack report), find another way to get it. Perhaps add it to the agent model instead of the configuration. (0.25d)
