### ISSUE TITLE
Move config import/export encryption to the UI

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2002]
# Refactor

## Component(s) to be refactored

- UI

## Explanation
New endpoints have been added in #2000 to allow configuration to me modified. When a configuration is retrieved from the Island, encrypting it is a matter of formatting/presentation, not the responsibility of the backend. Move the encryption/decryption of configuration during import/export to the UI. Use the new endpoints added in #2000.

### Tasks

- [ ] Re-implement the monkey/monkey_island/cc/server_utils/encryption/password_based_string_encryptor.py functionality on the front end (1.25d) - @VakarisZ 
  - [ ] Select a javascript encryption library
  - [ ] Implement the encryption feature
  - [ ] Implement the decryption feature
- [ ] Refactor the UI to encrypt/decrypt on export/import (0.75d)
- [ ] Remove backend encryption/decryption infrastructure and unit tests (0.5d)
    - [ ] Remove the disused python encryption classes
    - [ ] Remove disused python dependencies
- [ ] Remove the old configuration import/export endpoints (0.25d)
