### ISSUE TITLE
Retrieve/Submit config to new endpoints

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2003]
# Refactor

## Component(s) to be refactored

- UI

## Explanation
New endpoints have been added in #2000 to allow configuration to be retrieved and modified. Modify the UI to use these endpoints when retrieving a config from the island or submitting a modified one.

## Tasks
- [x] Define a new JSON schema in the UI layer (0d) @ilija-lazoroski 
    - [x] Don't forget to define "unsafe options" in the schema
    - [x] Make the new configuration UI look pretty
- [x] Remove the old schema (0d) - @shreyamalviya 
  - [x] Modify ATT&CK report to use the marshmallow schema or `AgentConfiguration` object
- [ ] Modify the UI to use the new `/api/agent-configuration` endpoints (0.25d) - @VakarisZ 
    - [x] export/import
    - [ ] reset/submit
- [ ] Remove any disused configuration endpoints (0.25d)
