### ISSUE TITLE
Configuration validation

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2004]
# Refactor

## Component(s) to be refactored

- Configuration

## Explanation

Document the configuration schema somewhere.
Add validation to the marshmallow schema and add this validation to the construction of the `Configuration` object (#1960)
The API should reject any submitted configuration that fails the validation checks.

## Tasks
- [x] Rename `common.configuration` to `common.agent_configuration` - @VakarisZ 
- [x] Figure out how to parse json arrays to tuples - @VakarisZ 
- [x] CustomPBAConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema (maybe verify the filenames)
- [x] PluginConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
- [x] ScanTargetConfiguration (0.25d) - @VakarisZ 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
    - [x] Change lists to Tuples
- [x] ICMPScanConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
- [x] TCPScanConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
    - [x] Change lists to Tuples
- [x] NetworkScanConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Change lists to Tuples
- [x] ExploitationOptionsConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
    - [x] Change lists to Tuples
- [x] ExploitationConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Change lists to Tuples
- [x] PropagationConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
- [x] AgentConfiguration - @shreyamalviya 
    - [x] Modify the docstrings
    - [x] Enforce constraints via schema
    - [x] Change lists to Tuples
