### ISSUE TITLE
Add system reset RPC endpoints

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2036]
# Refactor

## Component(s) to be refactored

- UI, API

## Explanation

Add RPC endpoints for resetting the data (map, reports) and resetting the whole system (data + configuration).

## Tasks
- [x] Add a method to `IAgentConfigurationRepository` to reset the config to default (0d) @mssalvatore 
- [x] Add three RPC endpoints for handling reset (0d) @mssalvatore 
    - [x] `/api/reset-agent-configuration`
    - [x] `/api/clear-simulation-data`
    - [x] `/api/reset-island-mode`
- [ ] Modify the default configs (ransomware and custom) to fit the new schema (0.25d) @mssalvatore 
- [x] Modify the UI to use the new reset endpoints (0d) @mssalvatore 
- [ ] Remove the old reset endpoints (0.25d) - @shreyamalviya 

## Notes
Remember to make appropriate changes to the configuration based on the Island mode.
