### ISSUE TITLE
Fix BB Tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2092]
Since we've altered the configuration schema and a number of other things, BB tests won't work. Fix them.

## Tasks
- [x] Change config templates into object and push credentials. (0d) @mssalvatore, @shreyamalviya 
  - [x] Modify configuration templates to contain config object and credentials list (watch out for #2072)
  - [x] Island client needs to send relevant data to relevant endpoints
  - [x] Remove `single_tests` @mssalvatore 
  - [x] Remove `config_templates`
- [x] Fix the tests that fail (0d) @ilija-lazoroski 
  - [x] Fix `ZerologonAnalyzer` TODO
