### ISSUE TITLE
Refactor authentication endpoints

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2105]
# Refactor

## Component(s) to be refactored

- `monkey_island.cc.resources.auth.auth.Authenticate`
- `monkey_island.cc.resources.auth.registation.Registration`
- `monkey_island.cc.services.AuthenticationService`

## Tasks
- [x] Rename endpoints (0d) - @shreyamalviya 
  - [x] Rename `/api/auth` to `/api/authenticate`
  - [x] Rename `resources/auth/auth.py` to `resources/auth/authenticate.py`
  - [x] Rename `/api/registration` to `/api/register`
  - [x] Rename `resources/auth/registration.py` to `resources/auth/register.py`
- [x] Remove unneccesary "error" in `/api/authenticate` response (0d) - @shreyamalviya 
- [x] Add `/api/user-registration-status` to check whether or not registration is needed (0d) - @shreyamalviya 
  - [x] Remove `GET /api/registration`
- [x] Add docstrings (0d) - @shreyamalviya 
  - [x] `AuthenticationService`
  - [x] `/api/authenticate`
  - [x] `/api/register`
