### ISSUE TITLE
Refactor `/api/island-mode`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2106]
# Refactor

## Component(s) to be refactored

- `/api/island-mode`

## Tasks
- [x] Rename to `/api/island/mode` (0d) @ilija-lazoroski 
- [x] Change `POST` to `PUT` (0d) @ilija-lazoroski 
- [x] Use `HTTPStatus` enum for return codes (0d) @ilija-lazoroski 
  - [x] See if you can just return the status with no body
  - [x] Use 204 instead of 200 for `PUT`
- [ ] Get rid of `['mode']` in `api/island/mode` and all uses. (0.25d) @ilija-lazoroski 
    - [ ] Add `IslandMode` to `resources/__init__.py` and shorten all imports
