### ISSUE TITLE
Refactor `/api/log/island/download`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2107]
# Refactor

## Component(s) to be refactored

- `/api/log/island/download

## Tasks
- [x] Rename `/api/log/island/download` to `/api/island/log` (0d) - @shreyamalviya 
- [x] Use DI to register a convention and inject the log file path into the resource's constructor (0d) - @shreyamalviya 
- [ ] Remove `IslandLogService` (0.25d) - @shreyamalviya
