### ISSUE TITLE
Refactor `/api/island/ip-addresses`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2108]
# Refactor

## Component(s) to be refactored

- `/api/island/ip-addresses`

## Tasks
- [x] Use DI to register a convention and inject the addresses into the resource's constructor
- [x] Return a list of IPs
- [x] Update the docstring
- [x] Inject the addresses into `LocalMonkeyRunService`'s constructor
    - [x] Add `IPAddresses` to `resources/__init__.py` and shorten all imports
- [x] Address comments and fix UTs (0.5d)
