### ISSUE TITLE
Island Version checking

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2109]
# Refactor

## Component(s) to be refactored

- monkey_island.cc.resources.version_update
- monkey_island.cc.services.version_update

## Tasks
- [x] Add a new object called `Version` with attributes: (0d) @ilija-lazoroski 
  - [x] `version_number` - Passed in to `Version()` constructor
  - [x] `latest_version` - A property that is populated asynchronously upon construction
  - [x] `download_url`- A property that is populated asynchronously upon construction
- [x] Construct `Version()` at Island startup (0d) @ilija-lazoroski 
- [x] Rename VersionUpdate to Version (0d) @ilija-lazoroski 
  - [x] Rename `/api/version-update` to `/api/island/version`
  - [x] Rename `VersionUpdate` to `Version`
  - [x] Rename `resources/version_update.py` to `resources/version.py`
- [x] Use `Version` object in `/api/island/version` endpoint (0d) @ilija-lazoroski 
  - [x] Add `Version` object to DIContainer
  - [x] Rename `newer_version` to `latest_version`
  - [x] Rename `current_version` to `version_number`
  - [x] Modify the UI to compare `version_number` to `latest_version`
  - [x] Add `Version` to `resources/__init__.py` and shorten all imports
- [x] Remove `services/version_update.py` (0d) @ilija-lazoroski 
- [x] Add authentication to `/api/island/version`. There are comments stating that the UI needs to know the version number before authentication, but I don't know why that's the case. (0d)
