### ISSUE TITLE
Parallelize Island builds

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2120]
## Summary

Currently, Island builds in Jenkins are performed in series. We could cut a few minutes off our build/test time if they were performed in parallel.

## Current flow
```
     Linux Agent    Windows Agent
             \     /
              \   /
               \ /
                |
                V
----------------------------------
             AppImage
                |
                V
          AppImage Tests
                |
                V
             Docker
                |
                V
           Docker Tests
                |
                V
               MSI
                |
                V
             MSI Tests
```

## Desired flow

```
    Linux Agent    Windows Agent
             \     /
              \   /
               \ /
                |
                V
----------------------------------
        AppImage    MSI
           |         |
           V         |
        Docker       | 
            \       /
             \     /   
              \   /
               \ /
                |
                V
----------------------------------
          AppImage Tests
                |
                V
           Docker Tests
                |
                V
             MSI Tests

```

## Tasks

- [x] Build Islands in parallel according to the above diagram (0d)
  - [x] Modify docker config to build on GCP node
  - [x] Verify that AppImage and docker builds run serially
  - [x] Pass correct parametars to `build_island` job

**Comment by cakekoa** [comment]
Island builds are now parallelized:
![Screen Shot 2022-11-22 at 2 05 50 PM](https://user-images.githubusercontent.com/11077625/203399982-ae82a403-0263-40b0-81c0-e7e2d6924712.jpg)

**Comment by VakarisZ** [comment]
The islands are getting build twice, once part of "build_islands" and once for each "EtE" test
