### ISSUE TITLE
Select new authentication token mechanism

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2130]
# Spike

## Objective
JWTs cannot be revoked. Up until now, this hasn't been a problem, but it will be an issue when implementing #2049. Select a new authentication token (e.g. OAuth) to replace JWTs.

## Requirements
- Tokens must have an expiration time
- Tokens must be revokable
- Tokens must be renewable/refreshable
  - The UI shouldn't log you out while you're using it
  - Ideally, some third-party library handles refreshing the tokens so we don't have to.
- It would be nice if the token can be configured/used as a One-Time Password (OTP)

## Output
- [x] A comparison of different authentication tokens/mechanisms
- [x] A new mechanism to use and an explanation of why it was selected
- [x] A plan for how it will be implemented
  - [x] How will it integrate with flask?
  - [x] What changes need to be made? API? UI?

Time remaining: 0d - @VakarisZ

**Comment by VakarisZ** [comment]
It's possible to rewoke JWT tokens by creating a black-list: https://flask-jwt-extended.readthedocs.io/en/stable/blocklist_and_token_revoking/
ATM we're missing refresh tokens, that's why the token expires mid-usage.

**Comment by VakarisZ** [comment]
The main libraries for session-based authentication are [Flask-Login](https://flask-login.readthedocs.io/en/latest/#login-example) and more robust version of it [Flask-Security](https://github.com/Flask-Middleware/flask-security/).
Although, based on [this article](https://blog.devgenius.io/flask-how-to-create-authentication-system-without-flask-login-cf804c8152a8) setting up flask-login is not trivial for a setup such as ours and the author just ended up with JWT + blocklist approach.
All things considered, I lean towards session-based approach, because it seems like a better fit for the use case of the project. 

## Tasks for session based token
- [ ] Move user to database
  - [ ] Create database user repository. We'll need to implement all methods or somehow return an object inheriting `UserMixin` (
  - [ ] Remove file user repository
  - [ ]

**Comment by VakarisZ** [comment]
Output: https://github.com/guardicore/monkey/issues/2157
