### ISSUE TITLE
Switch to token-based authentication

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2157]
Follow up to #2130 

### By-reference vs by-value tokens
The main libraries for session-based authentication are [Flask-Login](https://flask-login.readthedocs.io/en/latest/#login-example) and more robust version of it [Flask-Security](https://github.com/Flask-Middleware/flask-security/).
Although, based on [this article](https://blog.devgenius.io/flask-how-to-create-authentication-system-without-flask-login-cf804c8152a8) setting up flask-login is not trivial for a setup such as ours and the author just ended up with JWT + blocklist approach.
All things considered, I lean towards session-based approach, because it seems like a better fit for the use case of the project. 
Managing JWT blocklist could become a pain and a bottleneck, because for each agent **run** we'll have to create a JWT blocklist entry. Those entries will then have to be removed after the original JWT is outdated? 
[example implementations](https://testdriven.io/blog/flask-spa-auth/)

### Token in authorization header

Another option to strongly consider is moving the session token to authorization header: https://flask-login.readthedocs.io/en/latest/#custom-login-using-request-loader
This would provide unified interface for the UI and the agents. Also, this would[ prevent CSRF](https://security.stackexchange.com/questions/172637/will-authorization-bearer-in-request-header-fix-csrf-attacks#172648). The downside is the manual token handling (which we already do with JWT).

There are a couple of possible ways to handle this:

1. Add authorization header:
  \+ Requests remain stateless
  \+ Faster, no need to keep fetching CSRF token
  \- More custom code is required on the client side. We need to store the token in local storage and include it in requests

2. Include CSRF token in all requests:
  \+ Less custom code, only hook all requests to fetch and include CSRF
  \- Requests become stateful. This has potential to make unit/bb tests and agent communication harder

3. Add custom header and use only json content type:
  \+ Easy
  \- Stateful
  \- [Good enough?](https://security.stackexchange.com/questions/23371/csrf-protection-with-custom-headers-and-without-validating-token)

All things considered I think **solution 3** is the easiest. If we enforce the content type and custom header on the island side, it should be enough protection.

Edit: after discussion with @mssalvatore we decided to go with 1, because stateless API is easier to document and use for third parties and it's more orthodox solution.

### More on CSRF protection
CSRF protection [(add custom request headers](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#use-of-custom-request-headers). The CSRF is also irrelevant as long as [we use `application/json` content type](https://www.playframework.com/documentation/2.2.x/JavaCsrf))
Here's what Flask-security has to say about it: https://flask-security-too.readthedocs.io/en/stable/patterns.html#csrf

### Prototype location

Working example with key changes are [here](https://github.com/guardicore/monkey/compare/develop...PROTECTED_token_test). Registration/login/logout are working. 

Main branch: [2157-switch-to-token-based-auth](https://github.com/guardicore/monkey/tree/2157-switch-to-token-based-auth)

## Tasks for session based token
- [x] Move user to database (0d) @ilija-lazoroski 
  - [x] Define user model (inherits `UserMixin` [example model](https://pythonhosted.org/Flask-Security/quickstart.html#mongoengine-application))
  - [x] Define a single role model (inherits [role mixin](https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.RoleMixin))
  - [x] Remove `IUserRepository`
- [x] Change authentication service on the island
  - [x] Setup flask-security (add MongoEngine connection, [example here](https://github.com/guardicore/monkey/commit/c7b212d3b6fc12d2390dc353a8a6476355c7699a)) (0d) @ilija-lazoroski 
  - [x] Implement registration (Allow only single user to register) (0d) - @shreyamalviya @ilija-lazoroski 
      - [x] Emit `CLEAR_SIMULATION_DATA`, `RESET_AGENT_CONFIGURATION`, SET_ISLAND_MODE - UNSET` on registration 
      - [x] Reset repository encryptor on registration
  - [x] Implement login. Try using [verify_and_update_password](https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.UserMixin.verify_and_update_password). Make sure `verify_and_update_password` is using salt correctly (basically make sure it does `bcrypt.checkpw` behind the scenes). Make sure login creates a user with the "user" role. (0d) - @shreyamalviya 
- [x]  Change `monkey/monkey_island/cc/ui/src/services/AuthService.js` component. It needs to include `Authentication-token` header. Login and registration requests will also need specific query param to retrieve an authentication token. (0d) @VakarisZ 
    - [x] Implement logout
- [x] Show the new format of login/registration/logout errors (0d) @cakekoa 
- [x] Secure all presently secured endpoints with [auth_token_required](https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.auth_token_required) (0d) - @shreyamalviya 
- [x] Secure all presently secured endpoints with [roles_accepted](https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.roles_accepted) decorator. Roles will allow us to segregate endpoints that are agent-only, user-only or both (0d) - @shreyamalviya @ilija-lazoroski 
- [x] Unlock repository encryptor on on login (0d)
- [x] Update blackbox tests to use new auth mechanism (0d) @ilija-lazoroski 
- [x] Research do we actually need `SECRET_KEY` and password salt (0d) @ilija-lazoroski 
- [ ] Consolidate all login-related functionality under an "AuthenticationService" (0.5d) - @ilija-lazoroski 
- [ ] Investigate the API, make sure we are CSRF protected, make sure that other configuration options set for the app are adequate (maybe we need to change more defaults) (0.25d) @ilija-lazoroski 
- [x] Change the docs for resetting the credentials (0d) @cakekoa 
- [ ] Remove vulture entries related to this issue

Note: These tasks will take more than expected because we won't resist the temptations to refactor the services and front end, which could use improvements.

**Comment by mssalvatore** [comment]
![image](https://user-images.githubusercontent.com/19957806/182603729-3b3c162b-5485-452d-abce-a205ba449110.png)

@VakarisZ What are your thoughts on doing a spike for this? Do we have enough information at this point to plan this as a task, or would further investigation be helpful?

**Comment by ilija-lazoroski** [comment]
Thoughts on `SECRET_KEY` field: Anything that uses any kind of encryption in any of the flask extensions also uses the value of the `SECRET_KEY` field. As we know encryption relies on secrets, so if we don't set a server-side secret for the encryption to use we are not secure at all. We set this field and use it along with the data-to-sign to create a signature string, a hard-to-recreate value using a cryptographic hashing algorithm, so only if we have the exact same secret and the original data we can recreate this value which lets Flask detect if anything has been altered without permission. We keep this secret key locally because in that case an attacker will need to have access to our machine in order to do some tampering and if it has access to your machine then things are pretty bad already. 
The confusion happens because it is though that this field is only used to sign the session cookies which is not true. As we said it is used by flask extensions for any encryption that is done.  
We can't randomize this value on each run of the Island because we lose the value and Flask would not be able to decrypt anything that was already decrypted in the previous run. So all in all we need this field.


`SECURITY_PASSWORD_SALT` this field IMO is optional. By definition, it says: `Specifies the HMAC salt. This is required for all schemes that are configured for double hashing. ` Flask-Security-Too by default sets any schemas that are not plaintext to be doubled hashed. Why? Because more security is probably better 🤔  Another bit is that if you use `bcrypt` which is the default for `SECURITY_PASSWORD_HASH` double hashing is required. We can use `argon2` instead of `bcrypt` but the first choice in Flask-Security-Too is `bycript` so I say let's go with it.
