### ISSUE TITLE
Host documentation on Linode

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2163]
## Description
The Hugo documentation needs to be hosted on Linode instead of Guardicore's server.

## Tasks
- [x] Work with IT to get Linode an infection monkey account and accounts/roles for everyone on the team to access the infection monkey Linode resources. (0d) @ilija-lazoroski  
- [x] Configure an Object Storage ?bucket? to serve our documentation [as a static site](https://www.linode.com/docs/guides/host-static-site-object-storage/)  (0d) @ilija-lazoroski 
    - [x] Ensure all members of the team have write access
- [x] Update the documentation deployment scrips to push documentation to Linode (0d)
- [x] Upload the 1.13.0 documentation to Linode object storage (0d)
- [x] Update the README that describes how to push updated documentation (0d)
