### ISSUE TITLE
Refactor latest version check

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2165]
# Refactor

## Component(s) to be refactored

- AWS version lambda

## Explanation

The AWS lambda is violating the single responsibility principle by doing at least 3 different things:
1. Comparing versions to see if there's a newer version
2. Calculating download URLs
3. Collecting data for analytics

This lambda needs to stay in place for a while in order to support v1.13.0. On `develop`, we can begin to replace it with more cohesive components.

Use serverless compute, FaaS, or similar Linode services to serve the latest version and download link. It should accept a deployment type and respond with the latest available version and a link to the download. 

## Update

Linode doesn't offer any service similar to AWS Lambda. We'll just build a new lambda with a single focus. The tasks have been updated accordingly.

## Tasks
- [x] Identify the appropriate Linode service to serve the latest version and download link (0d)
- [x] Implement a new AWS Lambda that accepts a deployment and responds with the latest version and a download link (0d) -@VakarisZ
- [ ] Modify the `Version` object to query the new AWS lambda (0.25d)
- [ ] Add an asynchronous call to the old lambda on Island boot so that analytics continue to be collected (0.25d)
- [ ] Update the FAQ (0.25d)
