### ISSUE TITLE
Rename ICredentialsStore to IPropagationCredentialsRepository

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2169]
# Refactor

## Component(s) to be refactored

- infection_monkey.credentials_store

## Explanation

To keep terminology consistent, the `ICredentialsStore` and `AggregatingCredentialsStore` on the agent should be renamed using the term `Repository` instead of `Store`.

## Tasks
- [ ] Rename `Store` to `Repository` (0.25d) - @VakarisZ 
    - [ ] Rename `infection_monkey.credentials_store` to `propagation_credentials_repository`
    - [ ] Rename `infection_monkey.credentials_store.i_credentials_store` to `i_propagation_credentials_repository`
    - [ ] Rename `AggregatingCredentialsStore` to `AggregatingPropagationCredentialsRepository`
    - [ ] Rename any unit test files
- [ ] Add docstrings (0.25d) - @VakarisZ 
    - [ ] `IPropagationCredentialsRepository`
    - [ ] `AggregatingPropagationCredentialsRepository`
