### ISSUE TITLE
Integrate the EventQueue into the Agent

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2176]
# Refactor

## Component(s) to be refactored

- Agent
- infection_monkey.credential_collectors
- infection_monkey.telemetry.messengers.CredentialsInterceptingTelemetryMessenger

## Explanation

Use the EventQueue in the agent to handle `CredentialsStolenEvent` events. Register for these events and add stolen credentials to the `IPropagationCredentialsRepository`.

## Tasks
- [x] Define `CredentialsStolenEvent` in `common.events` (0d) @ilija-lazoroski 
- [x] Initialize the `IEventQueue` in the Agent (0d) @ilija-lazoroski 
- [x] Create a subscriber that subscribes to `CredentialsStolenEvents` and adds them to the `IPropagationCredentialsRepository` (0d) @ilija-lazoroski 
- [x] Modify the mimikatz collector to publish `CredentialsStolenEvents` (0.25d) - @shreyamalviya 
    - [x] Accept the `EventQueue` in the collector's constructor
    - [x] Generate `CredentialsStolenEvents`
    - [x] Publish `CredentialsStolenEvents`
    - [x] Add a tag for the collector
    - [x] Add tags for any mitre techniques
- [x] Modify the SSH collector to publish `CredentialsStolenEvents` (0d) - @ilija-lazoroski 
    - [x] Accept the EventQueue in the collector's constructor
    - [x] Generate `CredentialsStolenEvents`
    - [x] Publish `CredentialsStolenEvents`
    - [x] Add a tag for the collector
    - [x] Add tags for any mitre techniques
- [x] Modify zerologon to publish `CredentialsStolenEvents` (0d) - @ilija-lazoroski 
- [x] Remove `CredentialsInterceptingTelemetryMessenger` (0d) - @ilija-lazoroski 
- [ ] Remove Vulture entries that are no longer relevant (0.25d) - @shreyamalviya
