### ISSUE TITLE
Push Events from Agent to Island

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2177]
## Description

Write a subscriber in the agent that subscribes to all events and pushes them to the `/api/events` endpoint on the Island. The subscriber should receive events and push them to the Island asynchronously. To achieve this, the subscriber can push all events onto a queue and have a separate thread that waits on the queue and sends a sequence of events to the endpoint.

## Tasks
- [x] Create a subscriber that adds events to an internal queue (0d) - @shreyamalviya 
    - [x] Subscribe for all events
    - [x] Consider whether [this](https://github.com/guardicore/monkey/pull/2182#discussion_r941134053) is needed
- [ ] Add a thread to the subscriber that reads from the queue and sends a sequence of events to the endpoint. This should try to batch events using some strategy. (0.25d) - @shreyamalviya
