### ISSUE TITLE
Replace `CredentialsTelem`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2181]
# Refactor

## Component(s) to be refactored

- `CredentialsTelem`
- Island
- Agent

## Explanation

Telemetry is being replaced by events. Specifically, `CredentialsTelem` is being replaced by `CredentialsStolenEvent`.

## Tasks

- [x] Implement a subscriber in the island that subscribes to`CredentialsStolenEvents` and stores them in the `ICredentialsRepository` (0d) @mssalvatore 
- [x] Remove any code in the agent that publishes `CredentialsTelem` (0d) - @shreyamalviya 
- [x] Remove any code in the island that processes `CredentialsTelem` (0d) - @shreyamalviya 
- [x] Remove `CredentialsTelem` (0d) - @shreyamalviya 
- [ ] Run manual and ETE tests to verify that stolen credentials are properly stored and transmitted to all agents for reuse. Add a new BB tests if the current tests are not sufficient to test this functionality. (0.25d) - @shreyamalviya @ilija-lazoroski
