### ISSUE TITLE
Switch from marshmallow to pydantic

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2217]
# Refactor

## Component(s) to be refactored

- common.agent_configuration
- common.credentials
- monkey_island.cc.models.Simulation

## Explanation

For our use case, `pydantic` offers more features, less boilerplate, and simpler code than `marshmallow`. For example, validating an object's attributes when they are set is very cumbersome with `marshmallow`. With `pydantic` all that's required is to set a flag. `marshmallow` requires us to write schemas, where as `pydantic` works with type hints.

## Tasks

- [x] Refactor the `AgentConfiguration` to use `pydantic` (make it mutable) (0d)- @shreyamalviya 
    - [x] Since the `pydantic` model can be mutable, refactor the code that builds configurations for ETE tests
    - [x] Simplify any unit test code that was overcomplicated by `AgentConfiguration` being immutable
- [x] Refactor `Credentials` and all `ICredentialsComponent` to use `pydantic` (still immutable) (0d) - @VakarisZ 
    - [x] Consider using ["descriminated unions"](https://pydantic-docs.helpmanual.io/usage/types/#discriminated-unions-aka-tagged-unions) to serialize/deserialize the different `ICredentialsComponents`
- [x] Refactor `Simulation` to use `pydantic` (0d)
- [x] Remove `marshmallow` and `marshmallow-enum` dependencies from Island and Agent (0.d) @ilija-lazoroski 
- [x] Remove unneeded `IJSONSerializble` interface. (0d) @VakarisZ
