### ISSUE TITLE
Add `get_network_interfaces() -> IPv4Interface

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2218]
# Refactor

## Component(s) to be refactored

- infection_monkey.network.info

## Explanation

There are a number of functions in `infection_monkey.network.info` that deal with networking. They have some drawbacks:

1. Naming - One function is named `get_local_network_interfaces()`, but we also would want to get interfaces for public/routable IPs
2. Reinventing the wheel - Python provides the [`ipaddress.IPv4Interface`](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Interface) class, which we should use instead of our own custom `NamedTuples`.

Add a new function called `get_network_interfaces()` that returns `IPv4Interface` objects.

We will remove the old functions during a later refactoring.

## Tasks
- [x] Address comments on #2222 (0.25d)
- [x] Test `get_network_interfaces()` on Windows (0.25d)
- [x] Call `get_network_interfaces()` from `ControlChannel.register_agent()` (0.25d)

**Comment by cakekoa** [comment]
This is related to #2135
See [the PR](https://github.com/guardicore/monkey/pull/2222)
