### ISSUE TITLE
Implement IslandEventQueue

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2233]
## Description
The Island needs an internal pub/sub event queue to drive data processing and other server-side activities. Create and implement `IIslandEventQueue` (interface shown below) using `pypubsub`.

```python
from abc import ABC, abstractmethod
from enum import Enum, auto
from typing import Any, Callable, Optional


class IslandEventTopics(Enum):
    AGENT_CONNECTED = auto()
    CLEAR_SIMULATION_DATA = auto()
    RESET_AGENT_CONFIGURATION = auto()

class IIslandEventQueue(ABC):
    @abstractmethod
    def publish(self, topic: IslandEventTopics, event: Optional[Any] = None):
        pass

    @abstractmethod
    def subscribe(self, topic: IslandEventTopics, subscriber: Callable[[...], None]):
        pass
```

## Tasks

- [ ] Create `IIslandEventQueue` interface (0.25d) - @shreyamalviya 
    - [x] Create `IslandEventTopics` Enum
    - [x] Add docstrings
- [ ] Implement `PyPubSubIslandEventQueue` (0.25d) - @shreyamalviya 
- [x] Add `PyPubSubEventQueue` to DIContainer (0d) - @shreyamalviya 
- [x] Rename `IEventQueue` and `PyPubSubEventQueue` with `Agent` to disambiguate (0d) - @shreyamalviya
