### ISSUE TITLE
Remove RepositoryService

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2234]
# Refactor

## Component(s) to be refactored

- monkey_island.cc.services.RepositoryService

## Explanation

After #2233, the island will have an internal pub/sub queue that can be used to drive actions within the Island. `RepositoryService` is no longer required. Instead, create callable classes that take the place of `reset_agent_configuration()` and `clear_simulation_data()`. Create instances of those classes with the required dependencies and subscribe them to the appropriate topics.

## Tasks
- [x]  Refactor `reset_agent_configuration()` (0d) @ilija-lazoroski 
    - [x] Create a callable class or use `functools.partial` that will reset agent configuration 
    - [x] Subscribe the callable class to the RESET_AGENT_CONFIGURATION topic
- [x] Refactor `clear_simulation_data()` (0d) @mssalvatore 
    - [x] Subscribe `ICredentialsRepository.remove_stolen_credentials()` to the CLEAR_SIMULATION_DATA topic
    - [x] Subscribe `Database.reset_db()` to the RESET_AGENT_CONFIGURATION topic (use `itertools.partial` to set the `reset_config` argument)
- [x] Modify `ClearSimulationData` endpoint to publish a CLEAR_SIMULATION_DATA event instead of calling `RepositoryService` (0d) @mssalvatore 
- [x] Modify `ResetAgentConfiguration` endpoint to publish a RESET_AGENT_CONFIGURATION event instead of calling `RepositoryService` (0d) @ilija-lazoroski 
- [ ] Remove `RepositoryService` (0.25d)
