### ISSUE TITLE
Publish AgentRegistration in the Island

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2256]
## Description
When new agents register with the Island, events need to be published through the `IIslandEventQueue` and handled by some subscriber. For now, we need a subscriber that creates agents in the `IAgentRepository`, upserts `Machines` in the `IMachineRepository`, and upserts a node into `INodeRepository`.

The logic will look something like:

1. Find a machine based on the `machine_hardware_id`
    a. If the machine does not exist, find a machine based on the `network_interfaces`
    b. If a machine with a matching network interface exists, set its `hardware_id`
    c. If a machine does not exist, create a new machine in the repository.
1. Create an `Agent` in `IAgentRepository`
1. Use the `cc_server` field in `AgentRegistrationData` to update `INodeRepository`

## Tasks
- [x] Add a machine representing the island to the `IMachineRepository` on start if one doesn't already exist (0d) @mssalvatore 
    - [x] Add an `island` boolean to `monkey_island.cc.models.Machine`
- [ ] Publish a `IslandEventTopic.AGENT_CONNECTED` event and pass `AgentRegistrationData` in `resources.agents.Agent.post()` (0.25d) @mssalvatore 
- [ ] Implement a component that subscribes to `AgentConnected` events and updates the repositories as described above (0.25d) @mssalvatore
