### ISSUE TITLE
Replace IslandModeService with event

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2266]
# Refactor

## Component(s) to be refactored

- monkey_island.cc.services.island_mode_service
- monkey_island.cc.resources.island_mode

## Explanation

The Island is becoming more and more event-driven. The `IslandModeService` can be replaced by a subscriber that listens for a `SET_MODE` event.

## Tasks
- [x] Add `SET_MODE` to `IslandEventTopic` (0d) - @shreyamalviya 
- [x] Create a subscriber (callable class) that will subscribe to `SET_MODE` events and update the `IAgentConfigurationRepository` (0d) - @shreyamalviya 
- [x] Create a subscriber (callable class) that will update the mode in the `ISimulationRepository`. (Note: Perhaps you can just subscribe the `ISimulationRepository` directly to the event) (0d) - @shreyamalviya 
- [x] Modify the `IslandMode` resource to publish a `SET_MODE` event in `POST` (0d) - @shreyamalviya 
- [x] Modify the island to get the mode directly from `ISimulationRepository` in `GET` (0d) - @shreyamalviya 
- [ ] Remove `IslandModeService` (0.25d) - @shreyamalviya
