### ISSUE TITLE
Create and handle TCP scan events

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2267]
## Description

The TCP scanner should create and publish TCP scan events. Both the Agent and Island should use these events instead of `ScanTelem`.

## Tasks
- [x] Define a new `TCPScanEvent` in `common.events` (0d) - @ilija-lazoroski 
- [x] Modify the tcp scanner to accept an `IAgentEventQueue` (0d) @mssalvatore 
- [x] Modify the tcp scanner to generate and publish `TCPScanEvent` (0d) - @shreyamalviya  @ilija-lazoroski 
- [ ] Modify the Island to handle `TCPScanEvent` 
    - [x] Update nodes (0d) @ilija-lazoroski 
    - [x] Update report generation, or update reports to use `IEvenRepository` instead of `ScanTelem` or `VictimHost` or whatever they're using (0d) - Note: Move/copy/common the logic to translate ports to services from the agent to reports @VakarisZ 
- [x] Remove `ScanTelem` (0d) @VakarisZ 
- [x] Avoid race conditions between ping and tcp scan events (0d) @mssalvatore

**Comment by mssalvatore** [comment]
We'll use `agent-{START_TIME}-{IP}.log` for agent log names.

"agent" is added to distinguish agent from island logs.

Having the start time in the log could be useful during debugging. It will also allow log files to be sorted by name and appear in chronological order.

The IP is enough to uniquely identify machines for our test suite.
