### ISSUE TITLE
Create and handle ping scan events

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2268]
## Description

The ping scanner should create and publish ping scan events. Both the Agent and Island should use these events instead of `ScanTelem`.

## Tasks
- [x] Define a new `PingScanEvent` in `common.events` (0d) @cakekoa 
- [x] Modify the ping scanner to accept an `IAgentEventQueue` (0d) @ilija-lazoroski 
- [x] Modify the ping scanner to generate and publish `PingScanEvent` (0d) @ilija-lazoroski 
- [x] Modify the Island to handle `PingScanEvent` - @VakarisZ @cakekoa 
    - [x] Update nodes (0d) @cakekoa 
    - [x] Update machines (OS) (0d) @cakekoa 
    - [x] Update report generation, or update reports to use `IEvenRepository` instead of `ScanTelem` or `VictimHost` or whatever they're using (0d)
