### ISSUE TITLE
Remove old Monkey/Agent registration logic

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2272]
# Refactor

## Component(s) to be refactored

- monkey_island.cc.resources.monkey.py
- infection_monkey.cc.monkey.py

## Explanation

At this point, everything in the Island should be using `Agent` instead of `Monkey`. The existing registration logic for the `Monkey` model is [super complicated](https://github.com/guardicore/monkey/blob/e690eb7c61985faecba500b3403006abc27f3f89/monkey/monkey_island/cc/resources/monkey.py#L28-L118). Good thing we're replacing it :)

Remove the old monkey registration logic as it has now been supplanted by the agent registration logic.

## Tasks
- [ ] Remove call to `ControlClient.wakeup()` in `monkey.py` - @shreyamalviya 
- [ ] Remove registration logic in `resources/monkey.py` - @shreyamalviya 
  - [ ] Remove `Monkey.*` from vulture allow list
- [ ] ...
