### ISSUE TITLE
Agent log storage

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2274]
# Refactor

## Component(s) to be refactored

- monkey_island.cc.resources.log
- agent

## Explanation

Agent log contents can now be stored in the `Agent` model.

## Tasks
- [x] Define `IAgentLogRepository` (0d) @mssalvatore 
- [x] Implement an FileAgentLogRepository (0d) - @shreyamalviya 
- [x] Remove `log_contents` field from `Agent` model (0d) @ilija-lazoroski 
- [x] Provide a new, better-named API endpoint for agents to push their logs to ("/api/agent-logs/{AGENT_ID}") (0d) @ilija-lazoroski 
    - [x] Implement `PUT`
    - [x] Implement `GET`
- [x] Push logs to the new endpoint (0d) - @shreyamalviya 
- [x] Subscribe `FileAgentLogRepository.reset() to `CLEAR_SIMULATION_DATA` (0d) - @shreyamalviya
