### ISSUE TITLE
Add IslandAPIClient to the agent

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2292]
# Refactor

## Component(s) to be refactored

- control.py
- control_channel.py
- network/relay/utils.py
- caching_agent_binary_repository.py
- monkey.py
- agent_event_forwarder.py

## Explanation

Lots of different components are communicating with the Island's HTTP API. They're all issuing HTTP requests using `requests`. Ideally, these components wouldn't be focused on such low-level details.

Add `IslandAPIClient` that wraps all of the API calls that are relevant to the agent. There should be a 1-to-1 mapping between the methods of `IslandAPIClient` and the Island's HTTP API. Refactor all other components that are communicating with the Island to use the `IslandAPIClient`

### Notes
1. The constructor of `IslandAPIClient` should accept a server and attempt to connect. If connection fails, it should raise some kind of `ConnectionError`. This will simplify `find_server()`.
2. `control_channel.py` will likely be just a thin wrapper around `IslandAPIClient`. That's fine, since ISP states that "clients should not be forced to depend upon interfaces that they do not use", then `IControlChannel` serves as a view to segregate `AutomatedMaster` from parts of `IslandAPIClient` it doesn't use. In time we can reevaluate this.
3. `control.py` will likely end up as another thin wrapper. That's fine, it's only still there to provide backwards compatibility with old components that still need it.
4. `register_agent()` doesn't belong in `ControlChannel`. Whatever is calling it now could just call `IslandAPIClient` instead.
5. Serialization/deserialization should be the responsibility of `IslandAPIClient`. All other components can think in terms of objects.

## Tasks
- [x] Define a set of Errors/Exceptions that `IslandAPIClient` can raise. (0d) @ilija-lazoroski @VakarisZ 
- [x] Define the `IslandApIClient` (0d) @VakarisZ @shreyamalviya 
    - [x] Define a constructor that takes a server string and raises an exception if it cannot connect
- [x] Modify `find_server()` logic to use the new `IslandAPIClient` (0d) @ilija-lazoroski 
- [x] Refactor control.py - @shreyamalviya 
     - [x] Implement `send_agent_log()` and modify ControlClient.send_log() to use `IslandApiClient` (0d)
     - [x] Implement `get_pba_file()` and modify ControlClient.get_pba_file() to use `IslandApiClient` (0d)
- [ ] Refactor control_channel.py @cakekoa 
    - [x] Implement `register_agent()` and remove it from `ControlChannel`. Use `IslandAPIClient.register_agent()` in monkey.py instead of `control_channel.register_agent()` (0.25d)
    - [x] Implement `should_agent_stop()` and modify `ControlChannel` to use `IslandAPIClient` (0.25d)
    - [x] Implement `get_config()` and modify `ControlChannel` to use `IslandAPIClient` (0.25d)
    - [x] Implement `get_credentials_for_propagation()` and modify `ControlChannel` to use `IslandAPIClient` (0.25d)
- [x] Implement `get_agent_binary()` and modify `CachingAgentBinaryRepository` to use `IslandAPIClient` (0d) - @shreyamalviya 
- [x] Implement `send_events()` and modify `AgentEventForwarder` to use `IslandAPIClient` (0d) @ilija-lazoroski
