### ISSUE TITLE
Rename EventSerializers to AgentEventSerializers

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2293]
# Refactor

## Component(s) to be refactored

- event_serializers
- EventSerializerRegistry
- IEventSerializer
- PydanticEventSerializer

## Explanation
The Island handles both Island events and Agent events. To avoid confusion, rename event serializer components to include "agent" in their names. Don't forget to also rename the unit test files.

## Tasks
- [x] Rename `IEventSerializer` to `IAgentEventSerializer` (0d)
- [x] Rename `EventSerializerRegistry` to `AgentEventSerializerRegistry` (0d)
- [x] Rename `PydanticEventSerializer` to `PydanticAgentEventSerializer` (0d)
- [ ] Rename `event_serializers` package to `agent_event_serializers` (0.25d)
