### ISSUE TITLE
Use SocketAddress to represent servers

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2323]
# Refactor

## Component(s) to be refactored

- infection_monkey.InfectionMonkey
- infection_monkey.network.relay
- infection_monkey.i_island_api_client

## Explanation

A more specific data type is needed to define an IP/Port combination representing the Island server. We'll define a new type called `common.types.SocketAddress`. It should look something like:

```
class SocketAddress(InfectionMonkeyBaseModel):
    ip: IPv4Address
    port: conint(ge=1, le=65535)

    def __str__(self):
        return f"{self.ip}:{self.port}"
```

## Tasks
- [x] Implement `common.types.SocketAddress` (0d) @ilija-lazoroski 
- [x] Parse the contents of the `--servers` cli argument into `Sequence[SocketAddress]` (0d) @cakekoa 
- [x] Refactor `IIslandAPIClient` and `HTTPIslandAPIClient` to use `SocketAddress` instead of `str` (0d) @cakekoa 
- [x] Refactor `_running_on_island()` to use `SocketAddress` (0.0d) @cakekoa 
- [x] Refactor TCPRelay to use `SocketAddress` (0d) - @shreyamalviya 
    - [x] `TCPRelay.__init__()`
    - [x] `TCPPipeSpawner.__init__()`
    - [x] `sent_remove_from_waitlist_control_message_to_relays()`
    - [x] `notify_disconnect()`
- [x] Refactor `AgentRegistrationData` to use `SocketAddress` for `cc_server` (0d) - @shreyamalviya

**Comment by VakarisZ** [comment]
This is what I've done already: 
```
from ipaddress import IPv4Address

from common.base_models import InfectionMonkeyBaseModel


class SocketAddress(InfectionMonkeyBaseModel):
    """
    Combination of IP address and port

    Attributes:
        :param ip_address: IP address
        :param port: Port
    """
    ip_address: IPv4Address
    port: int
```
