### ISSUE TITLE
Return IPv4Addresses from get_my_ip_addresses()

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2325]
# Refactor

## Component(s) to be refactored

- get_my_ip_addresses()
- monkey_island.cc.server_setup
- monkey_island.cc.resources.ip_addresses
- monkey_island.cc.services.run_local_monkey.py

## Explanation

`get_my_ip_addresses()` should return `IPv4Address` instead of `str`

## Tasks
- [x] Rename `get_my_ip_addresses() -> str` to `get_my_ip_addresses_legacy() -> str` (0d) - @VakarisZ 
- [x] Add `get_my_ip_addresses() -> IPv4Address` (0d) @mssalvatore 
- [x] Refactor `monkey_island.cc.server_setup` (0d) @mssalvatore 
    - [x] `_collect_system_info()` calls new function
    - [x] `_start_island_server()` expects `IPv4Addresses`
    - [x] `_log_init_info()` expects `IPv4Addresses`
    - [x] `_log_web_interface_access_urls()` expects `IPv4Addresses`
    - [x] `_initialize_di_container()` registers a convention for `IPv4Addresses`
- [x] Refactor `monkey_island.cc.resources.ip_addresses` to use `Sequence[IPv4Address]` (0d) @mssalvatore 
- [x] Refactor `monkey_island.cc.services/run_local_monkey` to use `Sequence[IPv4Address]` (0d) @mssalvatore 
- [x] Refactor `monkey.py` to pass `Sequence[IPv4Address]` to `_build_master()`. Convert to string and pass strings to `AutomatedMaster` (0d) @cakekoa
