### ISSUE TITLE
Refactor the infection map graph to use new endpoints/data structures

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2334]
# Refactor

## Component(s) to be refactored

- Infection Map

## Explanation

New data structures/models have replaced older ones. New endpoints are available to retrieve the data. Use the new endpoints and data models instead of the old ones when building the infection map and preview pane.

The map will rely on `GET /api/agents`, `GET /api/machines`, `GET /api/nodes`, `GET /api/agent-events`, and `GET /api/agent-logs`. The frontend components can manipulate this data and combine it in whatever way they need. For example, the map component can query for machines, nodes, and agents and combine the data into a structure like this:
```
Map Node:
    machine_id: int,
    operating_system: OperatingSystem,
    hostname: str
    network_interfaces: Sequence[IPv4Interface],
    agent_id: Optional[UUID],
    agent_is_running: bool,
    parent_id: Optional[UUID],
    island: bool
    propagated_to: bool
    connections: {machine_id: int, [ConnectionTypes]}
```

It can then use this structure to populate the map.

## Tasks
- [x] Implement`GET /api/nodes` (0d) @ilija-lazoroski 
- [x] ~Implement `GET /api/agents`~ Done in #2362
- [x] ~Implement`GET /api/machines`~ Done in #2362
- [x] Remove the map from the security report (0d) @ilija-lazoroski 
- [x] Define the UI's `MapNode` data structure (0d) @ilija-lazoroski 
- [x] Update ReactiveGraph.js to take the new `MapNode` structure, transform it, and draw the graph (0d) @cakekoa
- [ ] Update the UI (MapPage) to use new endpoints - @VakarisZ, @cakekoa  (0.75d)
    - [ ] Call `GET /api/machines` and update the UI's Node data structure
    - [ ] Call `GET /api/agents` and update in the UI's Node data structure
    - [ ] Call `GET /api/nodes` and populate the UI's Node data structure 
    - [ ] Call `GET /api/agent-events?type=PropagationEvent&success=true`
