### ISSUE TITLE
Setup new zoo for @ybasford

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2366]
## Description

@ybasford will be helping improve Infection Monkey's documentation. She'll need here own Monkey Zoo to be able to run Infection Monkey. Set up a new Monkey Zoo and get @ybasford access. Take this opportunity to improve Monkey Zoo setup. It should be as close to a 1-touch setup as possible.

## Tasks

- [x] Follow the [MonkeyZoo setup documentation](https://github.com/guardicore/monkey/blob/develop/envs/monkey_zoo/docs/zoo_setup.md) to set up a new MonkeyZoo project.
- [x] Run the black box tests on the new zoo (0d) @ilija-lazoroski 
- [x] Get @ybasford access to the new zoo (0d) @ilija-lazoroski 
- [x] Give @ybasford support through the journey of running Infection Monkey in the zoo. (0d) @ilija-lazoroski
