### ISSUE TITLE
Spike: Quick zoo setup

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2372]
# Spike

## Objective
We need to be able to quickly and easily create monkey zoo environments.

- [x] Setup process is well-documented
- [x] Setup is quick and easy

## Scope
Estimated 0d @ilija-lazoroski 

## Output
Add tasks to #2366

## Tasks Remaining

- [ ] Ensure machines are configured to have external IPs. (0.25d) @ilija-lazoroski 
- [ ] Ensure the resources (cpu,memory,etc) for each machine in the terraform scripts matches what's in the guardicore-monkey environment (0.25d) @ilija-lazoroski

**Comment by mssalvatore** [comment]
Reopening, as some details in the terraform scripts are not correct.
