### ISSUE TITLE
Publish `AgentShutdownEvent`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2399]
## Description

The `Agent` models need to be updated with a `stop_time` when agents shut down.

## Goals/Epic/Context

Replace legacy `Monkey` model with new `Agent` model
Replace legacy `NodeService` and "node" models and endpoints with new `Machine`/`Agent`/`Node` models

## Tasks

- [x] Add an `AgentShutdownEvent` that has `stop_time` (0d) - @shreyamalviya 
- [x] Modify the agent to publish `AgentShutdownEvent` (Leave shutdown telem for now) (0d) - @shreyamalviya 
- [x] Subscribe to `AgentShutdownEvent` events in the Island and update the `Agent` models (0d) - @shreyamalviya 
- [ ] Update the UI's "clear data"/reset functionality to use "/api/agents" instead of "/api/root" (0.25d) - @shreyamalviya 
- [x] Add `AgentEventForwarder.flush()` (0d) - @mssalvatore
