### ISSUE TITLE
Use `PasswordRestorationEvent` in Zerologon BB test

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2405]
# Refactor

## Component(s) to be refactored

- ZerologonAnalyzer
- TelemetryBlackboxEndpoint

## Goals/Epic/Context

Replace telemetry with events.

## Tasks

- [ ] Modify the Zerologon analyzer to use `PasswordRestorationEvents` instead of telemetry to determine if password was successfully reset. (0.25d) @ilija-lazoroski 
    - [x] Add `GET api/agent-events` 
- [ ] Remove disused code: (0.25d)
    - [x] TelemetryBlackboxEndpoint
    - [x] MonkeyIslandClient.find_telems_in_db()
