### ISSUE TITLE
Refactor map side pane

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2430]
# Refactor map side pane according to new data models

## Tasks

- [x] Update the `Download Log` buttons to use the agent ID and call `GET /api/agent-logs/{AGENT_ID}` (0d) [waiting for #2334] - @shreyamalviya 
- [x] Update the `PreviewPaneComponent` with details from the `Agent` and `Machine` - @shreyamalviya 
    - [x] Remove "accessible from" (0d)
    - [x] Display info: OS display with version, IP addresses (0d) [waiting for #2334] @cakekoa
    - [x] Remove "services" (0d)
- [x] build `exploitsTimeline` by requesting `ExploitationEvents` from the API (0.25d) - @shreyamalviya 
- [x] Make sure there's a scrollbar and it works (0d) - @VakarisZ 
- [x] Aggregate identical events and display a number (0d) @shreyamalviya 
    The events should be sorted by date and aggregate as long as the next one matches the previous one
    Failure/success are different events
- [x] Fix island node to display log download buttons (0d) - @VakarisZ
