### ISSUE TITLE
Remove deprecated map related documents/collections

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2437]
# Refactor

Remove all legacy infrastructure related to map generation.

## Tasks
- [ ] Remove legacy code in `services/node.py`
- [ ] Remove the whole `monkey/monkey_island/cc/services/edge` folder
- [ ] Remove the whole `monkey/monkey_island/cc/services/netmap`

**Comment by mssalvatore** [comment]
@VakarisZ Can you update 2237 and close this as a duplicate?
