### ISSUE TITLE
Remove the Zero Trust report

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2441]
## Explanation

Infection Monkey's mission has changed. The existing Zero Trust report is not designed to work well with the new mission. It will be removed and rebuilt using the new infrastructure that is being built to support our new mission.

## Tasks
- [x] Remove the Zero Trust report (0d)
  - [x] Remove Zero Trust report from the UI @cakekoa
  - [x] Remove Zero Trust endpoint @cakekoa 
  - [x] Remove zero trust documentation @mssalvatore 
- [x] Review GitHub issues related to this report and close them as necessary (0d) @mssalvatore 
- [x] Update confluence documentation (0d) @cakekoa
