### ISSUE TITLE
Remove Post Breach actions

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2442]
## Explanation

Infection Monkey's mission has changed. The Post Breach Actions are not designed to work well with the new mission. They will be removed and rebuilt using the new infrastructure that is being built to support our new mission.

## Tasks
- [x] Remove Post Breach Actions (0d) - @VakarisZ 
  - [x] Code @VakarisZ
  - [x] Docs @mssalvatore
- [x] Review GitHub issues related to this report and close them as necessary (0d) @cakekoa 
- [x] Remove PBA from the confluence documentation (0d) @cakekoa
