### ISSUE TITLE
Replace FileEncryptionTelem with FileEncryptionEvent

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2496]
# Refactor

## Component(s) to be refactored

- Ransomware payload
- `FileEncryptionTelem`

## Explanation

Telemetries are being replaced by events. Replace `FileEncryptionTelem` with `FileEncryptedEvent`.

## FileEncryptedEvent
```python
class FileEncryptedEvent(AbstractAgentEvent):
    file_path: PurePath
    success: bool
    error_message: str = Field(default="")
```

## Tasks
- [x] Create `FileEncryptedEvent` (0d) @ilija-lazoroski 
- [x] Publish `FileEncryptedEvent` from the ransomware payload (0d) @ilija-lazoroski 
    - [x] Tag with the appropriate MITRE attack technique (T1486? Others?)
- [x] Modify the ransomware report to use events instead of telemetry (0d) - @shreyamalviya 
- [x] Remove `FileEncryptionTelem` (0d) @mssalvatore 
  - [x] Remove `BatchingTelemetryMessenger`
