### ISSUE TITLE
Replace `TelemetryPageComponent` with a similar page that shows events

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2501]
# Refactor

## Component(s) to be refactored

- `TelemetryPageComponent`

## Explanation

The agent no longer publishes telemetry; it publishes events instead. Reimplement/refactor the `TelemetryPageComponent` to use events instead of telemetry.

# Tasks
- [x] Rename `TelemetryPageComponent` - @shreyamalviya 
- [x] Replace all reference to "telemetry" with "event" - @shreyamalviya 
- [x] Query "/api/events" instead of telemetries - @ilija-lazoroski 
- [x] Modify columns to show fields from `AbstractAgentEvent` @shreyamalviya 
   - [x] Resolve `AgentID`s to IP/hostname or something human readable
   - [x] Resolve target IPs to hostname if possible
- [x] Modify final column to show type-specific fields @ilija-lazoroski 
- [x] Enable filtering on all fields from `AbstractAgentEvent` @ilija-lazoroski 
- [x] Add a loading icon while waiting for API response @ilija-lazoroski 
- [x] Fix code duplication for getting hostname from AgentID @ilija-lazoroski
