### ISSUE TITLE
Remove the security report's dependency on the `Monkey` model

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2507]
# Refactor

## Component(s) to be refactored

- `monkey_island.cc.services.reporting.ReportService`

## Explanation

The `Monkey` model has been superseded by the `Agent` model. Various parts of the `Monkey` model have been broken out into other components, such as events or signals. Decouple the `ReportService` from the `Monkey` model.

## Tasks

- [x] Understand the slowest part of report generation and how it scales (0d) @ilija-lazoroski 
- [x] Either remove caching or cache based on latest event (0d) @ilija-lazoroski 
- [x] Remove `aws_instance_id` from report generation (0d) - @shreyamalviya 
- [ ] Refactor the "tunnel issue" report component in the UI (0.5d) - @shreyamalviya 
    - [x] Pull machines and node communications and determine if any tunneling was used
    - [x] Display the "tunnel issues"
    - [x] Remove "tunnel issue" generation from the backend
- [x] Refactor the UI to use the logic from #2509 to get "manual monkeys" (0d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
Test 1: 
 1. Removed encryption/decryption
 2. Added index for event type field
 3. No caching
<img width="861" alt="image" src="https://user-images.githubusercontent.com/15820737/199925718-b856b126-2b98-4654-acef-c7bf7866003d.png">
<img width="836" alt="image" src="https://user-images.githubusercontent.com/15820737/199925772-a2b98d4c-4e67-4390-9818-3557d240f373.png">

Test 2:
 1. Removed encryption/decryption
 2. Added index for event type field
 3. Caching 
First time generating the report:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/15820737/199929640-b524521a-3fc0-4464-a49a-357ee8954c49.png">

Every other time:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/15820737/199929770-5d3ac49f-4917-4c04-b017-da5f137c5cbe.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/15820737/199929825-6c561771-498e-4904-aa39-c968123fe608.png">

It is safe to say that saving the report in the database and retrieving it if it is the latest saves more time then regenerating it again. It is good enough mechanism for now.
