### ISSUE TITLE
Agent Heartbeat

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2518]
### Problem
Agents may crash due to errors in code or be shutdown by EDR systems. In these cases, the agent may not have the opportunity to publish a "shutdown" event to the Island to let it know the agent will shutdown. This can lead to inaccurate maps/reports and prevent the user from clearing simulation data.

### Solution

Agents should periodically send a heartbeat to the Island. If the Island doesn't receive a heartbeat within a predetermined period of time, the Island should mark the agent as stopped.

## Tasks
- [x] Add an `AGENT_HEARTBEAT" _island_ event. - @shreyamalviya 
- [x] Create an endpoint `POST /api/agents/{AGENT_ID}/heartbeat` that allows an agent to send a heartbeat - @shreyamalviya 
    - [x] Heartbeats should include a timestamp set by the agent
    - [x] Publish the `AGENT_HEARTBEAT` _island_ event
- [x] Add a thread to the agent that sends a heartbeat every ?30? seconds (0d) - @shreyamalviya 
- [x] Create a subscriber that tracks agent heartbeats @ilija-lazoroski  (0d)
    - [x] Subscribe to `AGENT_HEARTBEAT` events and track heartbeats
    - [x] Create a thread that wakes every ?30? seconds and determines if agents have died prematurely
        - [x] If heartbeat not received in ?3 x 30? seconds, mark the stop time on the agent as the timestamp of the last heartbeat
- [x] Modify `AgentSignalsService` to respond with a terminate signal if an agent's stop time is not `None` (0d) - @shreyamalviya 
- [x] Modify `infection_monkey.network.relay.consts.SOCKET_TIMEOUT` to be 2x the heartbeat period. This should resolve #2635. (0d) @mssalvatore 
- [x] Shorten "heartbeat_timestamp" to "timestamp" @shreyamalviya (0d)
- [x] Improve/simplify timestamp validation @shreyamalviya (0d)
