### ISSUE TITLE
Pass Agent ID to child agents as `parent` parameter

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2530]
# Refactor

## Component(s) to be refactored

- Exploiters

## Explanation

When an agent successfully exploits a machine and spawns a new agent, it should pass its Agent ID to the child's `--parent` parameter.

## Tasks
 - [x] Modify `build_monkey_commandline()` to use `get_agent_id()` instead of GUID (0d) - @shreyamalviya 
     - [x] Remove GUID
     - [x] Test that agent records are being properly populated with the parent ID
     - [x] Test that the map displays the wrench icon only on agents run manually 
- [ ] Map is tested but is broken. Fix Map Nodes logic about the group. (0.25d) - @shreyamalviya
