### ISSUE TITLE
Prototype a plugin architecture

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2541]
# Spike

## Objective

Building off of what was learned in #2512, create a prototype plugin architecture.

## Output
A prototype plugin architecture that demonstrates plugins that can have different versions of the same dependency.

## Time remaining

Remaining time: 0d

## Tasks
- [x] Run custom finder only on imports for that plugin (using the `globals`) in the custom importer
- [x] Handle `from a import b` style imports (using the `fromlist`) in the custom importer
- [x] Handle `from . import x` style imports
- [x] Handle importing of extension modules
  - Update the CustomFinder to identify extension modules and use the ExtensionFileLoader to load them
  - Alternatively, find a way to replace the CustomFinder with one of the standard Finders
- [ ] Investigate pkg_resources (tracked in #2566)
- [ ] Investigate extension modules
  - [x] Determine if any of our dependencies use extension modules
- [ ] Test with the packages that we currently use
