### ISSUE TITLE
Investigate multiprocessing IPC

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2564]
# Spike

## Objective

Investigate using multiprocessing for running plugins. Specifically, we need to understand the capabilities and limitations of IPC when using multiprocessing.

## Scope
Answer the following questions:

* [x] How will logging be handled?
* [x] Can multiprocessing processes return values? How? What are the limitations
* [x] Can multiprocessing processes call a function on another process?
* [x] Can pydantic objects be pushed into a multiprocessing queue? What are the limitations/requirements?
* [x] Any other considerations?

## Output

Provide a small writeup for each of the above questions, along with a code example that shows how things will work or what is required.

**Comment by cakekoa** [comment]
That means that when you unpickle, it will attempt to import the item using the fully-qualified name. Both the producer and consumer of the serialized data need to be able to retrieve the same version of the object or problems may occur.

It may not end up being a problem, depending on what needs to be serialized, but it's good to be aware of this limitation.

**Comment by ilija-lazoroski** [comment]
One really cool and massive [blog post about multiprocessing](https://superfastpython.com/multiprocessing-in-python)

**Comment by ilija-lazoroski** [comment]
2. Can processes return values? 
Yep processes can return values using the `multiprocessing.Value` class.
How? Below is an example of how processes can return values.

```python
# SuperFastPython.com
# example of extending the Process class and adding shared attributes
from time import sleep
from multiprocessing import Process
from multiprocessing import Value
 
# custom process class
class CustomProcess(Process):
    # override the constructor
    def __init__(self):
        # execute the base constructor
        Process.__init__(self)
        # initialize integer attribute
        self.data = Value('i', 0)
 
    # override the run function
    def run(self):
        # block for a moment
        sleep(1)
        # store the data variable
        self.data.value = 99
        # report stored value
        print(f'Child stored: {self.data.value}')
 
# entry point
if __name__ == '__main__':
    # create the process
    process = CustomProcess()
    # start the process
    process.start()
    # wait for the process to finish
    print('Waiting for the child process to finish')
    # block until child process is terminated
    process.join()
    # report the process attribute
    print(f'Parent got: {process.data.value}')
```

**Comment by mssalvatore** [comment]
> Yep processes can return values using the multiprocessing.Value and multiprocessing.Array classes

@ilija-lazoroski What about if we want to return a custom class?

**Comment by ilija-lazoroski** [comment]
> > Yep processes can return values using the multiprocessing.Value and multiprocessing.Array classes
> 
> @ilija-lazoroski What about if we want to return a custom class?

I am still reading through that massive blog post, but I think [this](https://superfastpython.com/multiprocessing-share-object-with-processes/) is how we can do that.

**Comment by ilija-lazoroski** [comment]
1. How will logging be handled?

There are three ways how logging can be handled when we have multiple processes:

  1.  Use `logging` module separately in each Process (not recommended)
  This requires that you configure the logger in each processing, including the target (e.g stream or file) and log level. It is an easy approach that it does not require anything more. Its cons are that you have to duplicate code for each new process and the major limitations of this approach is that the log messages may be lost or corrupted (if multiple processes attempts to write log messages to the same stream or file)

  2. Use `multiprocessing.get_logger` (not recommended)
  Multiprocessing has its own logger which we can use to do the same as the `logging` module. This logger is used within objects and functions within the multiprcessing module. Same to the `logging` module is not process-safe and log messages can be lost or corrupted and it needs to be configured for each process.

  3. Use Custom Process-Safe logging (recommended)
  Effective logging from multiple processes requires some custom code to be written. Some [examples from the official python loggin](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes)g module explains how it can be done. We have few approach which we can follow:
    - Use a socket handler and send messages to a logging process
    - Use a custom handler that internally uses a shared mutex to ensure on process logs at a time
    -Use a queue handler that uses a shared queue to send messages to a logging process

Below is an example of how to do multiprocessing using a queue handler.

```python
# example of logging from multiple processes in a process-safe manner
from random import random
from time import sleep
from multiprocessing import current_process
from multiprocessing import Process
from multiprocessing import Queue
from multiprocessing import set_start_method
from logging.handlers import QueueHandler
import logging

# executed in a process that performs logging
def logger_process(queue):
    # create a logger
    logger = logging.getLogger('app')
    # configure a stream handler
    logger.addHandler(logging.StreamHandler())
    # log all messages, debug and up
    logger.setLevel(logging.DEBUG)
    # run forever
    while True:
        # consume a log message, block until one arrives
        message = queue.get()
        # check for shutdown
        if message is None:
            break
        # log the message
        logger.handle(message)

# task to be executed in child processes
def task(queue):
    # create a logger
    logger = logging.getLogger('app')
    # add a handler that uses the shared queue
    logger.addHandler(QueueHandler(queue))
    # log all messages, debug and up
    logger.setLevel(logging.DEBUG)
    # get the current process
    process = current_process()
    # report initial message
    logger.info(f'Child {process.name} starting.')
    # simulate doing work
    for i in range(5):
        # report a message
        logger.debug(f'Child {process.name} step {i}.')
        # block
        sleep(random())
    # report final message
    logger.info(f'Child {process.name} done.')

# protect the entry point
if __name__ == '__main__':
    set_start_method('spawn')
    # create the shared queue
    queue = Queue()
    # create a logger
    logger = logging.getLogger('app')
    # add a handler that uses the shared queue
    logger.addHandler(QueueHandler(queue))
    # log all messages, debug and up
    logger.setLevel(logging.DEBUG)
    # start the logger process
    logger_p = Process(target=logger_process, args=(queue,))
    logger_p.start()
    # report initial message
    logger.info('Main process started.')
    # configure child processes
    processes = [Process(target=task, args=(queue,)) for i in range(5)]
    # start child processes
    for process in processes:
        process.start()
    # wait for child processes to finish
    for process in processes:
        process.join()
    # report final message
    logger.info('Main process done.')
    # shutdown the queue correctly
    queue.put(None
```

For more examples refer to [Python Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes).
And for more explanation on logging using multiprocessing refer to [this post](https://superfastpython.com/multiprocessing-logging-in-python/).

**Comment by ilija-lazoroski** [comment]
4. Can pydantic objects be pushed into a multiprocessing queue? What are the limitations/requirements?

As far as I have noticed there are not any limitations or requirements to store a pydantic objects, pydantic dataclass, dataclasses.dataclass, and so on, in a `multiprocessing.Queue`. An example that I have tried:

```python
import multiprocessing

import pydantic
from pydantic import dataclasses

class AnotherClass:
    def __init__(self):
        self.b = 2

    def get_b(self):
        return self.b

class SomeClass:
    def __init__(self, other_object: AnotherClass):
        self.a = 1
        self.other_object = other_object

    def get_a(self):
        return self.a

    def get_other_object(self):
        return self.other_object


@dataclasses.dataclass()   # using pydantic.dataclasses.dataclass() works
class Foo:
    bar: int


class SomeModel(pydantic.BaseModel):
    baaz: int
    foo: Foo
    some_object: SomeClass

    class Config:
        arbitrary_types_allowed = True



def do_it(q: multiprocessing.Queue):
    model = q.get()
    print(model)
    model_object = model.some_object
    print(type(model_object), model_object.get_a(), model_object.get_other_object(), model_object.get_other_object().get_b())
    dataclass = q.get()
    print(dataclass)

    object_class = q.get()
    print(object_class)

def main():
    multiprocessing.set_start_method(method="spawn")
    q = multiprocessing.Queue()
    p = multiprocessing.Process(target=do_it, args=(q,))
    p.start()
    other_object = AnotherClass()
    some_object = SomeClass(other_object)
    model = SomeModel(baaz=0, foo=Foo(bar=42), some_object=some_object)
    dataclass = Foo(bar=1)
    q.put(model)
    q.put(dataclass)
    q.put(some_object)
    q.put(None)
    p.join()

if __name__ == '__main__':
    main()
```

**Comment by ilija-lazoroski** [comment]
Can multiprocessing processes call a function on another process?

The answer is no. The child process is the one that is going to call the function.

```python
# example of getting the main process from a child of the main process
import os
from multiprocessing import Process
from multiprocessing import parent_process
from multiprocessing import set_start_method

def some_callable():
    print(f"\tGreat - pid={os.getpid()}")

# function executed in a child process
def task(callable_arg):
    print(f"Child process pid - {os.getpid()}")
    print()
    # get the parent process instance
    print("Calling `callable_arg()`")
    callable_arg()
    print("Calling `some_callable()`")
    some_callable()

# entry point
if __name__ == '__main__':
    print(f"Parent process pid - {os.getpid()}")
    set_start_method('spawn')
    # create a new process
    process = Process(target=task, args=(some_callable, ))
    # start the new process
    process.start()
    # wait for the new process to terminate
    process.join()
```

Output is:

![image](https://user-images.githubusercontent.com/15820737/201936183-3aef8ff8-f2db-4fd6-990a-4ff5ef0939ee.png)

**Comment by mssalvatore** [comment]
@ilija-lazoroski Can we somehow use this? https://superfastpython.com/multiprocessing-pool-callback/

**Comment by ilija-lazoroski** [comment]
> @ilija-lazoroski Can we somehow use this? https://superfastpython.com/multiprocessing-pool-callback/

I guess it is possible but the limitation of it is that we have callbacks only when using `multiprocessing.Pool` and there are certain relations regarding the callbacks. That blog post has everything that we need but the example below shows from where the callback is run and how to share data with the callback.

```python
# example of a callback function for apply_async()
import os
from random import random
from time import sleep
from multiprocessing.pool import Pool
from multiprocessing import set_start_method
from random import random

# result callback function
def result_callback(result):
    # global variable data
    global data
    print()
    print(f"Callback PID: {os.getpid()}", flush=True)
    print(f'Callback got: {result}', flush=True)
    # change the value of data
    data = random()

    print(f"Method data is: {data}")

# task executed in a worker process
def task(identifier):

    print()
    print(f"Child process PID: {os.getpid()}", flush=True)
    # generate a value

    value = random()
    # report a message
    print(f'Task {identifier} executing with {value}', flush=True)
    result_callback(1.1111)
    # block for a moment
    sleep(value)
    # return the generated value
    return value

# protect the entry point
if __name__ == '__main__':
    set_start_method('spawn')
    print(f"Parent process PID: {os.getpid()}")
    # create and configure the process pool
    with Pool() as pool:
        # issue tasks to the process pool
        result = pool.apply_async(task, args=(0,), callback=result_callback)
        # close the process pool
        pool.close()
        # wait for all tasks to complete
        pool.join()

    # print the global changed data
    print(f"Callback data is: {data}")
```

![Screen Shot 2022-11-15 at 3 32 07 PM](https://user-images.githubusercontent.com/15820737/201945290-ecd86de9-3fa6-4a2c-bd8a-90d3b86632e3.jpg)

**Comment by ilija-lazoroski** [comment]
What are some of the limitations or considerations we need to look at?

1. We [can't use `print` in any of the child processes](https://superfastpython.com/multiprocessing-print/) that run without setting `flush=True`. 
2. Use context managers when using locks.
3. Use `Pipes` and `Queue` to send and receive.
4. Be certain that all attributes which are sent to a child process are pickable. What is pickable and what is not can be found [here](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled).
5. Be aware that we are `spawning` processes and not `forking`.
