### ISSUE TITLE
Query the IslandAPI for unknown plugins

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2579]
## Description

If the `PluginRegistry` does not have the requested plugin, it should load it from the Island.

## Goal/Context

Agents will request plugins from the Island at runtime. Between now and when plugins are fully implemented, we can begin to implement the infrastructure for passing them from the Island to the agent.

## Tasks
- [x] Add a method to `HTTPIslandAPIClient` that requests agent plugins from the API (0d) - @VakarisZ 
- [x] Use dependency injection to pass the `PluginRegistry` to the `Puppet`'s constructor (0d) - @shreyamalviya 
- [x] If `PluginRegistry` does not have the plugin, query `HTTPIslandAPIClient`. Raise `UnknownPluginError` if the endpoint returns 404. Raise `NotImplementedError` if the endpoint returns a 2xx (0d) - @shreyamalviya
