### ISSUE TITLE
Resolve warnings in unit tests

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2580]
# Refactor

## Component(s) to be refactored

- Unit tests/dependencies

## Explanation

A number of warnings appear when running unit tests. Resolve these warnings. Run with a newer version of Python (3.10.0+) to see all warnings.

![image](https://user-images.githubusercontent.com/19957806/201728952-bf21de0d-d077-434d-8a5a-f4851190e105.png)

## Tasks
- [x] Resolve `PytestCollectionWarnings` (0d) @ilija-lazoroski 
- [x] Resolve `distutils`/`mongomock` deprecation warning (0d) @ilija-lazoroski 
- [x] Resolve `botocore`/`urllib3.contrib.pyopenssl` deprecation warning (0.25d) @cakekoa 
- [x] Resolve flask `propagate_exceptions` warning (0d) @ilija-lazoroski

**Comment by mssalvatore** [comment]
https://github.com/flask-restful/flask-restful/issues/957
