### ISSUE TITLE
Empty log file downloaded if file does not exist anymore

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2586]
## Describe the bug
If an Agent's log file is deleted, the download log button on the Map page's preview pane doesn't update (it should be gray if a log file doesn't exist), and when clicked, downloads an empty file of the same name.

## To Reproduce
1. Run the Island and an Agent. Go the Map page and click on the machine on which the Agent was run. See that the download Agent log button is yellow and click on it to verify that the file gets downloaded.
2. Delete that Agent's log file.
3. Go to the Map page. The button is still yellow and clicking on it download's an empty file with the same name.

## Expected behavior
The island should return a 404 error if a log doesn't exist. The user should get some kind of notification.

## Tasks
- [x] Ensure that the Island returns a 404 if the log doesn't exist (0d) - @shreyamalviya 
- [ ] Notify the user that the requested log file doesn't exist. (0.25d) - @shreyamalviya 
    - [ ] Preferably, always handle 404 errors in the UI the same way
