### ISSUE TITLE
Map boundaries

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2590]
## Description

**Is your feature request related to a problem? Please describe.**

Map page UI could be improved in the following ways:
 - Map should take up the whole page (except header)
 - Items like legend and side panes should be an overlay

As it stands now map has annoying "invisible" boundaries:
![image](https://user-images.githubusercontent.com/36815064/202197082-5106fc4b-2347-4bf5-ab21-c3c0194c431e.png)

## Tasks

- [ ] Make the map take up the whole screen except the header and menu pane (0.25d)
   - [x] The legend should go on top - @cakekoa 
   - [ ] The right side pane should go on top - @cakekoa
