### ISSUE TITLE
Add firewall rules around 10.2.3.48 to speed up depth_3_a test

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2597]
## Description

The depth_3_a test wastes 15-22 seconds waiting for 10.2.3.48 to shutdown. The cause is that 10.2.3.48 can successfully exploit other machines, but firewall rules prevent other machines from informing .48's relay that they don't need it. .48's relay is preventing the agent from shutting down quickly because it is waiting for child agents that will never be able to contact it.

![image](https://user-images.githubusercontent.com/19957806/202269798-1c9689e4-8d99-46b8-ad22-b8fa511bad98.png)

## Solution

Add firewall rules to prevent .48 from exploiting other machines.

## Tasks
- [x] Modify the guardicore-monkey environment with the firewall rules (0d) @ilija-lazoroski 
- [x] Add firewall rules to the terraform scripts to prevent .48 from exploiting other machines (0d) @ilija-lazoroski 
- [x] Rebuild the guardicore-infec-monkey-test-1 environment (0d) @ilija-lazoroski 
- [x] Rebuild the guardicore-infec-monkey-test-2 environment (0d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
The added firewall rule is `block-powershell-48-to-depth-3`:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/15820737/203773595-f2db80b9-f637-4d71-a637-39c21f1be77b.png">

All monkeys are dead after 13 seconds instead of the 22 seconds above:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/15820737/203773639-26dd107e-dc6a-4392-a0da-b96a42fabd46.png">

This required a network tag to be added to the `mimikatz-15`.

**Comment by ilija-lazoroski** [comment]
Test-1 zoo:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/15820737/203974285-48af1818-26e0-4f11-929b-b1cc8eeb760b.png">
