### ISSUE TITLE
Improve nightly test reliability

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2601]
## Problem

Presently, we think nightly tests are unreliable because certain VMs and services are slow to boot/start.

## Solutions
1. Run the SSH credentials reuse test first. This will give slower VMs more time to start
2. Improve boot times for the powershell machines
3. Improve startup time for the Linux Solr service.

## Tasks
- [x] Change test order (0d) @cakekoa 
- [x] Improve windows boot times (0d) @cakekoa 
- [ ] ~~Improve Solr startup time (1.25d)~~ @cakekoa #2609
- [x] Rebuild test environments (0d) @cakekoa 
  - [x] Re-generate the images @cakekoa 
  - [x] Run terraform to rebuild the environments
