### ISSUE TITLE
Solr service fails to start on Linux Solr VM  

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2609]
## Describe the bug
Occasionally, the solr will fail to start. Looking at the service logs (via `journalctl -u solr`) shows that port 8983 is already in use. Further inspection reveals that the process ID that is using that port is the same process ID of the solr process prior to "Reboot".

## To Reproduce
This issue not easily reproducible. Currently, the way to reproduce it is to reboot the log4j-solr-49 instance until the service has failed to start (`systemctl status solr` shows the service as "failed").

## Expected behavior
Port 8983 should not be in use when solr tries to start up, and the solr service should not fail to start.

## Screenshots
```
Nov 14 23:56:03 log4j-solr-49 systemd[1]: Starting "Runs a solr server with vulnerable log4j version"...
Nov 14 23:56:03 log4j-solr-49 bash[1094]: *** [WARN] *** Your open file limit is currently 1024.
Nov 14 23:56:04 log4j-solr-49 bash[1094]:  It should be set to 65000 to avoid operational disruption.
Nov 14 23:56:04 log4j-solr-49 bash[1094]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Nov 14 23:56:04 log4j-solr-49 bash[1094]: *** [WARN] ***  Your Max Processes Limit is currently 15534.
Nov 14 23:56:04 log4j-solr-49 bash[1094]:  It should be set to 65000 to avoid operational disruption.
Nov 14 23:56:04 log4j-solr-49 bash[1094]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Nov 14 23:56:04 log4j-solr-49 bash[1094]: Warning: Available entropy is low. As a result, use of the UUIDField, SSL, or any other features that require
Nov 14 23:56:04 log4j-solr-49 bash[1094]: RNG might not work properly. To check for the amount of available entropy, use 'cat /proc/sys/kernel/random/entropy_avail'.
Nov 14 23:56:10 log4j-solr-49 bash[1094]: [194B blob data]
Nov 14 23:56:10 log4j-solr-49 bash[1094]: Started Solr server on port 8983 (pid=1261). Happy searching!
Nov 14 23:56:10 log4j-solr-49 bash[1094]: [14B blob data]
Nov 14 23:56:10 log4j-solr-49 systemd[1]: Started "Runs a solr server with vulnerable log4j version".
Nov 15 00:04:15 log4j-solr-49 systemd[1]: Stopping "Runs a solr server with vulnerable log4j version"...
Nov 15 00:04:16 log4j-solr-49 systemd[1]: solr.service: Main process exited, code=exited, status=143/n/a
Nov 15 00:04:16 log4j-solr-49 systemd[1]: solr.service: Failed with result 'exit-code'.
Nov 15 00:04:16 log4j-solr-49 systemd[1]: Stopped "Runs a solr server with vulnerable log4j version".
-- Reboot --
Nov 15 00:15:59 log4j-solr-49 systemd[1]: Starting "Runs a solr server with vulnerable log4j version"...
Nov 15 00:16:00 log4j-solr-49 bash[1091]: *** [WARN] *** Your open file limit is currently 1024.
Nov 15 00:16:00 log4j-solr-49 bash[1091]:  It should be set to 65000 to avoid operational disruption.
Nov 15 00:16:00 log4j-solr-49 bash[1091]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Nov 15 00:16:00 log4j-solr-49 bash[1091]: *** [WARN] ***  Your Max Processes Limit is currently 15534.
Nov 15 00:16:00 log4j-solr-49 bash[1091]:  It should be set to 65000 to avoid operational disruption.
Nov 15 00:16:00 log4j-solr-49 bash[1091]:  If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Nov 15 00:16:00 log4j-solr-49 bash[1091]: Port 8983 is already being used by another process (pid: 1261)
Nov 15 00:16:00 log4j-solr-49 bash[1091]: Please choose a different port using the -p option.
Nov 15 00:16:00 log4j-solr-49 systemd[1]: solr.service: Control process exited, code=exited status=1
Nov 15 00:16:00 log4j-solr-49 systemd[1]: solr.service: Failed with result 'exit-code'.
Nov 15 00:16:00 log4j-solr-49 systemd[1]: Failed to start "Runs a solr server with vulnerable log4j version".
```

## Machine version (please complete the following information):
Ubuntu 18.04

## Tasks

 - [x] Recreate the machine's image (0.25d)
 - [x] Rebuild the guardicore-infec-monkey-test-1 environment (0.25d)
 - [x] Rebuild the guardicore-infec-monkey-test-2 environment (0.25d)

**Comment by mssalvatore** [comment]
The issue is that Solr checks whether or not the port is in use by checking a `.pid` file. Generally, `.pid` files are stored in `/run` or another location that is wiped clean on reboot. Adding the following lines to the systemd unit resolves this:

```diff
  [Service]
+ RuntimeDirectory=solr
+ Environment=SOLR_PID_DIR=/run/solr
```

At the present time, I'm not sure exactly why the `.pid` file wasn't removed on shutdown. Since we're not trying to run a solr instance for any purpose other than testing the exploiter, I'm not overly concerned.

The lines shown below have been added to the systemd unit file to address Solr's warnings about the open file and process limits. Perhaps these limits have something to do with why the original `.pid` file was not removed.


```diff
  [Service]
+ LimitNPROC=65000
+ LimitNOFILE=65000
  RuntimeDirectory=solr
  Environment=SOLR_PID_DIR=/run/solr
```

**Comment by VakarisZ** [comment]
My guess is that sometimes the VM doesn't shutdown gracefully. When starting/stopping the service directly or through systemctl the bug doesn't happen.
