### ISSUE TITLE
Create a Plugin class

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2638]
## Description

Create a new class that will contain all of the information about a plugin, including the plugin itself. This will be used by the Island to store/retrieve agent plugins, as well as by the agent to load and use plugins in the puppet.

Suggestion:

```python

class PluginManifest:
    name: str
    supported_operating_systems: Tuple[OperatingSystem, ...]
    type: PluginType
    

class Plugin:
    plugin_manifest: PluginManifest
    config_schema: JSONSerializable
    src_archive: bytes
````

### Note

Consider this class to be a first draft. We want to get it reasonably close, but we don't need to agonize over every decision. We can improve and modify it as our plugin framework develops.

## Tasks
- [ ] Evaluate current exploiters and add determine if the `PluginManifest` proposed above is missing any necessary fields
- [ ] Implement the `PluginManifest` class as a pydantic model
- [ ] - [ ] Implement the `Plugin` class as a pydantic model

**Comment by VakarisZ** [comment]
## Plugin configurations and manifests

### Manifest
We need a manifest to describe the plugin. 
This includes, but is not limited to
- Name
- Title (like name, but human readable. We could parse it from name, but probably not worth it)
- Description
- Link to the documentation
- Is it safe?
- Supported operating systems
- Plugin type

This base manifest can then be expanded per plugin type, it can have additional fields like
- Default port
- Supported stealth levels
- Attack technique tags? 

The source of the manifest can be in any format. It's probably best if it's defined in python. The creator of the plugin can import the `AgentPluginManifest` and build it with his own parameters, validating it as it's being defined.

### Config schema
Each plugin might contain options. These options need to be defined. Metainformation, like description, title are needed as well as validation rules. Configuration schema should be in jsonschema format, as it's easier to display and common.

### Configuration values
Each plugin might contain options. The default value for options needs to be defined. The default values from the schema can be used to generate this, but that's [not the purpose of the default values in jsonschema](https://python-jsonschema.readthedocs.io/en/stable/faq/#why-doesn-t-my-schema-s-default-property-set-the-default-on-my-instance). It's probably better to have this.

## Data, loaded into class

Definition of classes required:

### Manifest 

```
from typing import Tuple, Optional

from common import OperatingSystem
from common.types import PluginType


class AgentPluginManifest:
    name: str
    title: str
    description: str
    link_to_documentation: Optional[str]
    supported_operating_systems: Tuple[OperatingSystem, ...] = [OperatingSystem.WINDOWS, 
                                                                OperatingSystem.LINUX]
    type: PluginType
    safe: bool
```

### Plugin

```
from common.types import JSONSerializable


class AgentPlugin:
    plugin_manifest: AgentPluginManifest
    config_schema: JSONSerializable
    default_config: JSONSerializable
    source_archive: bytes
```
