### ISSUE TITLE
Create a multiprocessing-safe wrapper for `AgentEventQueue`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2640]
## Description

Plugins running in different processes need to be able to publish their events to the same queue. In order to do this, a new component is needed that will handle the IPC. For this, we'll introduce `IAgentEventPublisher` which only provides a `publish()` method. An implementation of `IAgentEventPublisher` will push events onto a queue, while a thread within the agent will pull events off the queue and push them into the `IAgentEventQueue`.

![multiprocessing-event-publishing drawio](https://user-images.githubusercontent.com/19957806/204680780-2161a192-a1f1-41d4-8f84-a8120c10039d.png)

## Tasks
- [x] Create `IAgentEventPublisher` (0d) @ilija-lazoroski 
- [x] Create a `QueuedAgentEventPublisher` that implements `IAgentEventPublisher` and pushes events into a queue (0d) @ilija-lazoroski 
- [ ] Create a new threaded component in the agent that pulls events from the multiprocessing queue and publishes them to `IAgentEventQueue`. (0.75d) @ilija-lazoroski 
    - [ ] `start()` - starts the thread
    - [ ] `stop()` - flushes all events and stops the thread
