### ISSUE TITLE
Avoid Island data processing race conditions

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2653]
## Description

There are a number of potential race conditions in the Island when processing both Agent and Island events. There are many ways to solve them. For now, we should take the simplest approach. We can attempt more complicated approaches if performance becomes an issue. Note, however, that using multithreading has a minimal effect on performance because of the GIL, and because we use Gevent, we're not really using python's multithreading anyway (Gevent monkey patches stdlib's threading module). This also means that these race conditions are unlikely to manifest.

The solution for now is to prevent Island and Agent events from being processed concurrently.

## Tasks

- [x] Write an `IAgentEventQueue` decorator that acquires a lock while calling the decorated object's `publish()` (0d)
- [x] Write an `IIslandEventQueue` decorator that acquires a lock while calling the decorated object's `publish()` (0d)
- [ ] Decorate the Island's Agent and Island event queues at initialization (0.25d) - @cakekoa 
    - [x] Pass the same lock to both decorators so that Agent and Island events are processed serially
    - [ ] Use an RLock so that Island event handlers are able to publish new Island events

**Comment by mssalvatore** [comment]
Most of this was already done in https://github.com/guardicore/monkey/pull/2374
