### ISSUE TITLE
Create a simple plugin for testing

### ISSUE THREAD

**Issue by cakekoa** [guardicore/monkey#2675]
## The Problem
In order to test out the plugin architecture, it would be useful to have a simple plugin.

The objective is to create a basic exploiter plugin to exercise the following areas of the system:
- Plugin loading
- Plugin configuration
  - Default values
  - Schema validation
  - UI
- Passing the plugin from island to agent
- Exploitation/propagation events

## The Proposal
Create an exploiter plugin that reports exploitation and propagation success using a configurable success rate. It will therefore have at least two options:` propagation_success_rate` and `exploitation_success_rate`. Their default values should be 50%

The exploiter needs to do the following
1. Log the version of its dependency (vendored)
1. Publish an ExploitationEvent with a random success/failure
2. If exploitation is successful, publish a PropagationEvent with a random success/failure
3. Return an ExploiterResultData

### Plugin archive structure
```
my_plugin.tar
  plugin.yaml
  config-schema.json
  plugin.tar
    plugin.py
    vendor/
```

### Plugin structure in repo

```
monkey/tests/data/for/tests/mock_agent_plugin/
  build.sh
  plugin.yaml
  config-schema.json
  src/
    plugin.py
```

### plugin.py

For now, `plugin.py` can have a single method
```
run(
    host: VictimHost,
    servers: Sequence: str,
    current_depth: int,
    options: Dict[str, Any],
    interrupt: Event,
    agent_binary_repository: IAgentBinaryRepository,
    event_publisher: IAgentEventPublisher
)
```
This is the launching point for the plugin.

## Tasks
- [x] Define the manifest file (0d) - @shreyamalviya 
- [x] define the configuration schema (0d) - @cakekoa
- [x] Write plugin.py (nothing needs to run this yet, it just needs to be close) (0d) - @shreyamalviya 
- [x] Simple script to build plugin archives (0d) - @cakekoa 
    - [x]  Accept a version number and install that version of some dependency into a vendor/ directory
    - [x] Tar up the plugin and produce a `mock_plugin-exploiter.tar`
