### ISSUE TITLE
Load and run plugins in the Puppet using serpentarium

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2692]
## Description

We have all of the parts and pieces. It's time to start putting them together.

We have a mock exploiter plugin and the Island has an API endpoint that allows the Agent to request it. Serpentarium will allow the plugin to be run concurrently and with its own, isolated set of dependencies. Modify the Agent's `PluginRegistry` to load and run plugins returned by the Island.

## Tasks

- [x] Move `monkey_island.cc.server_utils.file_utils` (or some subset of it) into `common` (0d) - @shreyamalviya 
- [x] Use Pure DI to inject `serpentarium.PluginLoader` into the `PluginRegistry` (0d) - @cakekoa 
- [x] When the `PluginRegistry` receives a plugin from the Island it should:
    - [x] Extract the plugin's source `.tar` file contents to a secure location (0d) - @cakekoa, @mssalvatore 
        - [x] Watch out for [Zip Slips](https://security.snyk.io/research/zip-slip-vulnerability)!
        - [x] [This](https://salvatoresecurity.com/preventing-directory-traversal-vulnerabilities-in-python/) can help.
    - [x] Load the Plugin as `MultiprocessingPlugin` (0d) (See #2726) @mssalvatore 
        - [x] Return a **copy** of the plugin to the caller
- [x] Use `multiprocessing.Event()` for the interrupt in the Master instead of `threading.Event()` (0d) - @shreyamalviya 
    - [x] Change type hints to use `common.concurrency.Event`
    - [x] NOTE! You need to use a `multiprocessing.context.SpawnContext` object to generate the `Event`
- [x] Rename `ExploiterWrapper.exploit_host()` -> `run()` (0d) - @shreyamalviya 
    - [x] Use keyword arguments to call `run()` in the `Puppet`
- [x] Set `main_thread_name = threading.current_thread().name` (0d) - @mssalvatore  
- [x] Test the Agent with a custom configuration (include the mock exploiter plugin) and verify that the plugin system works end-to-end. (0d) @mssalvatore 
- [x] Configure the exploiter to sleep and test the stop/interrupt functionality (0d) @ilija-lazoroski 

## Notes
- It's important that the `PluginRegistry` return a _copy_ of the requested plugin. `MultiprocessingPlugin` objects are `SingleUsePlugins`, so the registry must return a unique copy of the plugin to every requestor.
