### ISSUE TITLE
Migrate to rjsf component

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2694]
**Is your feature request related to a problem? Please describe.**

We need to migrate because of multiple reasons. Main reasons are [easier styling](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-templates/#ObjectFieldTemplate) and bugs like https://github.com/rjsf-team/react-jsonschema-form/pull/3287
It also has better styling, allows us to migrate front end framework easily

More context in #2661 

## Tasks
- [x] Install rjsf components required (take a look at [plugin.json](https://github.com/guardicore/monkey/blob/2538-plugin-prototype/monkey/monkey_island/cc/ui/package.json) in prototype branch (0d) @cakekoa @VakarisZ 
- [ ] Migrate the components required and test the UI @cakekoa @VakarisZ 
    - [x] Fix array styles/button placement (0d) - @VakarisZ 
    - [x] Fix advanced select
    - [x] Field name placement 
    - [ ] Compare styles and fix (0.25d) - @VakarisZ 
    - [x] Error display (0d) @cakekoa 
- [ ] Remove legacy styles and packages (0.5d) - @VakarisZ
