### ISSUE TITLE
Complex mock plugin options

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2697]
**Is your feature request related to a problem? Please describe.**
For testing the UI of plugin configuration we need to mock some plugins with complex options. 

**Describe the solution you'd like**
The mock has to have some required fields, some with defaults and some without. There also needs to be some other validation rules in order to properly test the capabilities of the added plugin UI infrastructure. We have examples in the 2538-plugin-prototype, but ideally, we should fetch those from the island. Alternatively, we can fake the fetching process on the UI. The purpose of this task is to simulate that we get complex plugins from the back end in a way the back end provides them (global schema, global config instance, plugin schemas, plugin manifests).

More context in #2661

Examples of complex fields and validations can be found [here](https://rjsf-team.github.io/react-jsonschema-form/)

Examples of plugin data required can be found [here](https://github.com/guardicore/monkey/tree/2538-plugin-prototype/monkey/monkey_island/cc/ui/src/components/plugin-prototype)

## Tasks
 - [x] Extend the plugin options defined in the prototype (0d) - @shreyamalviya 
     - [x] Add a List of strings
     - [x] an SSH keypair object
     - [x] Add a boolean
     - [x] Add an floating number of seconds to sleep (default 0)
    - [x] Modify the mock plugin to
        - [x] log the list of strings
        - [x] log the SSH keypair
        - [x] log some statement if boolean is true
        - [x] Sleep for the configured number of seconds (interruptible!)
- [ ] Copy the mock plugin and make some small modifications to it (0.25d) @ilija-lazoroski 
  - [ ] Name
  - [ ] Title
  - [ ] Default config values
  - [ ] Add or remove 1 config field
