### ISSUE TITLE
Plugin selector with options

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2698]
**Is your feature request related to a problem? Please describe.**
The plugins we're adding support options. We need to be able to show the options specified in the plugin configuration schema.

**Describe the solution you'd like**
Please describe the desired behavior.

## Tasks

- [ ] Create a function that would generate a UI schema for the configuration. `rjsf` doesn't know where the plugins are in the schema. We need to figure out the paths to all plugins and specify that they need to be displayed with a specific template. One way this could be achieved is to pull the whole schema (which includes plugins) and to pull all plugins. Then go through each plugin, find it in the schema and mark the path in the UI schema to display the specific template. [Example UI schema](https://github.com/guardicore/monkey/blob/2538-plugin-prototype/monkey/monkey_island/cc/ui/src/components/plugin-prototype/proto-ui-schema.tsx) (1.25d)
- [ ] Modify the prototype selector UI, to have checkmarks indicating the selection of the plugin. Take a look at [prototype template](https://github.com/guardicore/monkey/blob/2538-plugin-prototype/monkey/monkey_island/cc/ui/src/components/plugin-prototype/proto-ui-schema.tsx) and [prototype selector component](https://github.com/guardicore/monkey/blob/2538-plugin-prototype/monkey/monkey_island/cc/ui/src/components/plugin-prototype/proto-selector.tsx). Instead of dropdown selector it should be something like in advanced selector (maybe we can reuse it?) (1.25d)
- [ ] Add safety check and a warning for unsafe options (0.5d)
