### ISSUE TITLE
Improve the plugin selection style

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2700]
**Is your feature request related to a problem? Please describe.**
The plugin selector style could be improved to better suit the overall theme of the configuration

More context in #2661

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/36815064/207627200-f70f028a-e806-4f63-b886-3e9940ae3922.png)

## Tasks
- [ ] Modify/stylize the prototype selector to more closely resemble the mock provided (timeboxed) (0.75d)
    - [ ] Disable the options if the plugin is not selected - @VakarisZ 
    - [x] Add border to indicate that plugin options are part of plugin selector (cherry pick relevant commit from 2698-plugin-selector-component) - @VakarisZ 
    - [x] Highlight the selected exploiter (it's unclear for which exploiter the options are being shown) @ilija-lazoroski 
    - [x] Add a default options pane/text @ilija-lazoroski 
    - [x] Add a link (cherry pick from 2698-plugin-selector-component)
