### ISSUE TITLE
Configure plugin logging

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2703]
## Description

Pass a `ConfigureLoggerCallback` to the `PluginLoader's` constructor so that `MultiprocessingPlugins` spawned by the `Puppet`/`PluginRegistry` have properly configured logging.

## Tasks
- [ ] ~Update the `serpentarium` dependency to 0.3.0 or later.~
- [ ] Pass the same `Queue` from #2691 from main.py to `InfectionMonkey's` constructor @ilija-lazoroski 
- [ ] Configure `InfectionMonkey's` `PluginLoader` from issue #2692 to configure logging using the `Queue` from the previous task @ilija-lazoroski
