### ISSUE TITLE
Upgrade to MongoDB 6.0

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2706]
## Description

MongoDB 4.2 goes EOL in April 2023. We need to upgrade to the latest stable version of MongoDB (6.0).

## Notes
Tarballs available at https://www.mongodb.com/try/download/community

Xenial is not supported, ~so we'll need to upgrade our island machines to at least bionic in our test environments.~

Need to update:
- `install_mongo.sh` script
- `install_mongo.ps1` script
- docker documentation
- windows build
- Update pymongo dependency to 4.x

Note: Commit c94880f111225a121ad6be101ec440ef99582d1f passes ETE tests for AppImage with the following log message:
>2023-02-14 19:36:33,884 - INFO - mongo_setup.py:88 - _assert_mongo_db_version() - Mongo DB version OK. Got ('6', '0', '4')

## Tasks
- [x] Update `install_mongo.sh` script (0d) @mssalvatore 
- [x] Update `install_mongo.ps1` script (0d) @mssalvatore 
- [x] Update docker documentation (0d) @mssalvatore 
- [x] Update docker ETE test scripts (0d) @mssalvatore 
- [x] Update pymongo dependency to 4.x (0d) @mssalvatore
