### ISSUE TITLE
Refactor `VictimHost`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2707]
# Refactor

## Component(s) to be refactored

- `infection_monkey.model.VictimHost`

## Explanation

`VictimHost` needs to be prepared for use with plugins. Many of the assumptions, uses, and decisions around `VictimHost` are obsolete or deprecated. For example, the `VictimHostFactory` exists solely to populate `VictimHost.default_server`. Exploiters no longer use this field, so it and the `VictimHostFactory` can be removed.

The new `VictimHost` should look something like:

```python
class TargetHost(InfectionMonkeyBaseModel):
    ip: IPv4Address
    operating_system: Optional[OperatingSystem]
    services: Dict[str, Any]  # This is deprecated!!! Don't use it
    port_scan_results: Dict[NetworkPort, PortScanData]
    icmp_scan_results: Optional[PingScanData]
```

## Tasks

- [x] Rename `VictimHost` -> `TargetHost` (the term "victim" makes the assumption that exploitation is successful) (0d) @ilija-lazoroski 
- [x] Remove disused `default_server` (0d) - @shreyamalviya 
  - [x] Remove dependencies on `VictimHostFactory`
  - [x] Remove `VictimHostFactory`
  - [x] Remove `default_server` field from `VictimHost`
- [x] Remove disused `domain_name` field from `VictimHost` (0d) @ilija-lazoroski 
- [x] Redefine `PortScanData` using `pydantic` (0d) @ilija-lazoroski 
- [ ] Redefine `PingScanData` using `pydantic` (0.25d) - @shreyamalviya 
    - [x] Move this back to `infection_monkey/i_puppet/ping_scan_data.py`
- [ ] Redefine `TargetHost` using `pydantic` (0.5d) - @shreyamalviya 
  - [ ] Change `TargetHost.ip` to an `IPv4Address` 
  - [ ] Change `operating_system` to an `Optional[OperatingSystem]
  - [ ] Add a comment deprecating `TargetHost.services`
- [ ] Remove `TargetHost.is_windows()` and modify everything that uses it (0.25d) - @shreyamalviya
