### ISSUE TITLE
Plugins in schema

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2710]
**Is your feature request related to a problem? Please describe.**
If the island expects configuration with plugins it should provide schema to validate against

## Tasks
- [x] Add `IFileRepository.get_all_file_names() -> Sequence[str (file name)]` (0d) @mssalvatore 
    - [x] Modify all `IFileRepository` implementations
- [x] Add `IAgentPluginRepository.get_plugin_catalog() -> Sequence[Tuple[AgentPluginType, str (plugin name)]]` (0d) @ilija-lazoroski 
    - [x] Implement `FileAgentPluginRepository.get_plugin_catalog()`
- [x] Check whether or not the UI can support using references in JSON schema (0d) - @cakekoa (**see comment below**)
- [x] Implement `ConfigSchemaService` (0d) - @cakekoa 
    - [x] Transform `AgentConfiguration` into JSON schema (https://docs.pydantic.dev/usage/schema/)
    - [x] Loop through all plugins and insert their schemas into the larger `AgentConfigurationSchema`
- [x] Add `/api/agent-configuration-schema` endpoint that uses `ConfigSchemaService` to return the JSON schema (0d) - @shreyamalviya

**Comment by cakekoa** [comment]
Local references are supported by react-jsonschema-form (rjsf). See:
https://react-jsonschema-form.readthedocs.io/en/latest/usage/definitions/
https://rjsf-team.github.io/react-jsonschema-form/
