### ISSUE TITLE
Fetch schema from the back end

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2750]
# Refactor

Schema in the `monkey/monkey_island/cc/ui/src/services/configuration/configSchema.js` is no longer needed, as it can be generated on the back end from pydantic models and sent to the UI.

## Tasks
- [x] Improve the back end schema with descriptions, titles. Descriptions should be moved from the schema that is defined in UI. By default descriptions are the comments left bellow classes, which is not acceptable (0d) - @VakarisZ 
- [ ] Change UI to use the back end schema (0.75d) - @VakarisZ 
- [ ] Replace the pydantic hacks with descriptions for all schema fields
- [ ] Remove vulture allowlist entries
