### ISSUE TITLE
Add new propagation credentials repository

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2773]
# Refactor

## Component(s) to be refactored

- `infection_monkey.credential_repository`
- `infection_monkey.credential_repository.i_propagation_credentials_repository`

## Explanation

New exploiter plugins should use the `Credentials` objects, instead of the legacy credentials dictionary provided by `IPropagationCredentialsRepository`. Rename `IPropagationCredentialsRepository` and create a new `IPropagationCredentialsRepository` that returns `Credentials` objects.

## Tasks
- [x] Rename the `credential_repository` package to `propagation_credentials_repository` @cakekoa
- [x] Rename `IPropagationCredentialsRepository` to `ILegacyPropagationCredentialsRepository` @cakekoa 
- [x] Create a new `IPropagationCredentialsRepository` that returns `Credentials` instead of a `dict` @cakekoa 
- [x] Implement the new `PropagationCredentialsRepository` (0d) @cakekoa 
    - [x] Use the same caching strategy/logic as `AggregatingPropagationCredentialsRepository`
    - [x] Make sure caching is multiprocessing-safe (see #2771)
    - [x] Ensure duplicate credentials are not stored in the repository
- [x] Construct the new `PropagationCredentialsRepository` (0d) @cakekoa 
- [x] Modify `add_stolen_credentials_to_repository` to accept the new repository and add credentials to it when `CredentialsStolenEvent` is received. (0d) @cakekoa 
    - [x] Pass the repository to the event handler on construction 
- [x] Modify the `PluginRegistry` to accept an `IPropagationCredentialsRepository` and pass it to any plugins upon construction. (0d) @cakekoa 
- [x] Modify any plugins (i.e. `MockPlugin`) to accept an `IPropagationCrededentialsRepository` (0d) @cakekoa 
    - [x] Modify the mock plugin to request credentials from the repository and log them.
- [ ] Fix crash (see comment) (1.0d) @cakekoa

**Comment by mssalvatore** [comment]
@cakekoa Here's an crash from a docker ETE test:


```
2023-01-06 15:02:33,875 [2081:MainThread:INFO] main.main.47: writing log file to /tmp/infection-monkey-agent-2023-01-06-15-02-33-1y1mdm4k.log
2023-01-06 15:02:33,876 [2081:MainThread:INFO] main._run_agent.120: >>>>>>>>>> Initializing the Infection Monkey Agent: PID 2081 <<<<<<<<<<
2023-01-06 15:02:33,877 [2081:MainThread:INFO] main._run_agent.123: version: 1.13.0+1501
2023-01-06 15:02:33,877 [2081:MainThread:INFO] monkey.__init__.99: Agent is initializing...
2023-01-06 15:02:33,879 [2081:MainThread:INFO] monkey.__init__.102: Agent ID: 2b854c5a-b950-4001-bcbd-ec199b33e90a
2023-01-06 15:02:33,879 [2081:MainThread:INFO] monkey.__init__.103: Process ID: 2081
2023-01-06 15:02:33,882 [2081:MainThread:INFO] monkey._log_arguments.206: Agent started with arguments: parent: ffe3926c-cc1e-4c11-93c4-70d5f7f52ca6, servers: [SocketAddress(ip=IPv4Address('10.2.2.250'), port=5000), SocketAddress(ip=IPv4Address('10.2.2.250'), port=8080), SocketAddress(ip=IPv4Address('172.17.0.1'), port=8080)], depth: 1
2023-01-06 15:02:33,884 [2081:MainThread:DEBUG] monkey._connect_to_island_api.160: Trying to wake up with servers: 10.2.2.250:5000, 10.2.2.250:8080, 172.17.0.1:8080
2023-01-06 15:02:33,885 [2081:FindIslandServer-01:DEBUG] utils._check_if_island_server.62: Trying to connect to server: 10.2.2.250:5000
2023-01-06 15:02:33,889 [2081:FindIslandServer-02:DEBUG] utils._check_if_island_server.62: Trying to connect to server: 10.2.2.250:8080
2023-01-06 15:02:33,891 [2081:FindIslandServer-03:DEBUG] utils._check_if_island_server.62: Trying to connect to server: 172.17.0.1:8080
2023-01-06 15:02:33,937 [2081:FindIslandServer-02:DEBUG] utils._check_if_island_server.68: Successfully connected to the Island via 10.2.2.250:8080
2023-01-06 15:02:33,939 [2081:FindIslandServer-01:DEBUG] utils._check_if_island_server.68: Successfully connected to the Island via 10.2.2.250:5000
2023-01-06 15:02:38,898 [2081:FindIslandServer-03:DEBUG] http_client.connect.76: Connection to 172.17.0.1:8080 failed: HTTPSConnectionPool(host='172.17.0.1', port=8080): Max retries exceeded with url: /api?action=is-up (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0a046dc050>, 'Connection to 172.17.0.1 timed out. (connect timeout=5)'))
2023-01-06 15:02:38,898 [2081:FindIslandServer-03:ERROR] utils._check_if_island_server.71: Unable to connect to server/relay 172.17.0.1:8080: HTTPSConnectionPool(host='172.17.0.1', port=8080): Max retries exceeded with url: /api?action=is-up (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0a046dc050>, 'Connection to 172.17.0.1 timed out. (connect timeout=5)'))
2023-01-06 15:02:38,899 [2081:MainThread:INFO] monkey._connect_to_island_api.168: Using 10.2.2.250:5000 to communicate with the Island
2023-01-06 15:02:38,909 [2081:MainThread:CRITICAL] main.log_uncaught_exceptions.105:   File "infection_monkey/main.py", line 146, in <module>
  File "infection_monkey/main.py", line 48, in main
  File "infection_monkey/main.py", line 127, in _run_agent
  File "infection_monkey/monkey.py", line 132, in __init__
  File "infection_monkey/propagation_credentials_repository/propagation_credentials_repository.py", line 35, in __init__
  File "multiprocessing/context.py", line 56, in Manager
  File "multiprocessing/managers.py", line 563, in start
  File "multiprocessing/process.py", line 112, in start
  File "multiprocessing/context.py", line 284, in _Popen
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 72, in __init__
  File "multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "multiprocessing/popen_fork.py", line 17, in __init__
  File "multiprocessing/util.py", line 416, in _flush_std_streams

2023-01-06 15:02:38,909 [2081:MainThread:CRITICAL] main.log_uncaught_exceptions.106: <class 'BrokenPipeError'>: [Errno 32] Broken pipe
2023-01-06 15:02:38,910 [2081:MainThread:CRITICAL] main.log_uncaught_exceptions.105:   File "<string>", line 1, in <module>

2023-01-06 15:02:38,910 [2081:MainThread:CRITICAL] main.log_uncaught_exceptions.106: <class 'BrokenPipeError'>: [Errno 32] Broken pipe
```
