### ISSUE TITLE
Island: Validate `AgentConfiguration` objects against the JSONSchema

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2783]
## Description

Plugins are loaded dynamically at runtime, so the `AgentConfiguration` pydantic object cannot validate plugin options. Luckily, the `AgentConfigurationSchemaService` provides a JSONSchema which is built at runtime and is capable of validating plugin configurations. The goal is to guarantee that only valid configurations are stored in or retrieved from the `IAgentConfigurationRepository`.

This requires some refactoring of the `AgentConfigurationSchemaService` in order to avoid a circular dependency between the `repositories` and `services` packages.

## Tasks
- [x] Extract the logic in the `AgentConfigurationSchemaService` into a utility function in the `repository` package. `AgentConfigurationSchemaService` will be a thin wrapper around this utility. (0d) -@VakarisZ
- [x] Create a new `PluginValidationError` that will be raised if an invalid `AgentConfiguration` is submitted to the repository. (0d) - @VakarisZ 
- [x] Modify `IAgentConfigurationRepository.update_configuration()` docstring to include a "raises" entry for `PluginValidationError` (0d) - @VakarisZ 
- [x] Create a decorator that will decorate an `IAgentConfigurationRepository` (0d) @ilija-lazoroski 
    - [x] Use the new schema utility function to get the schema
    - [x] Validate an object retrieved from the decorated repository against the schema before passing it back to the caller. Raise a `RetrievalError` if the object is invalid.
    - [x] Validate an object that is submitted to the repository before passing it through to the decorated repository. Raise a `PluginValidationError` if the object is invalid
- [ ] Write tests for the endpoint that verify a 4xx error is returned if an Agent config with invalid plugin configs is submitted. Modify the endpoint to properly handle a `PluginValidationError`. (0.25d) @ilija-lazoroski
