### ISSUE TITLE
Agent: Validate `AgentConfiguration` objects against the JSONSchema`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2784]
## Description

Plugins are loaded dynamically at runtime, so the `AgentConfiguration` pydantic object cannot validate plugin options. Luckily, the `/api/agent-configuration-schema` endpoint provides a JSONSchema which is built at runtime and is capable of validating plugin configurations. The goal is to guarantee that only valid configurations are passed from the `IIslandAPIClient` to the Agent.

## Tasks
- [x] Modify `IIslandAPIClient.get_config()`'s docstring to include a "raises" entry for a generic `IslandAPIError` (0d) - @shreyamalviya 
- [x] Add `IIslandAPIClient.get_agent_configuration_schema()` and implement it in `HTTPIslandAPIClient` (0d) - @shreyamalviya 
- [ ] Create a decorator that will decorate an `IIslandAPIClient` (0.5d) - @shreyamalviya 
    - [x] Use the `get_agent_configuration_schema()` to retrieve the schema from the Island.
    - [x] Validate the object retrieved from the Island against the schema before passing it back to the caller. Raise a `IslandAPIError` if the object is invalid.
