### ISSUE TITLE
Improve config schema generation

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2785]
**Is your feature request related to a problem? Please describe.**
Hadoop plugin schema should end up in vulnerability exploiters. This means that we need to refactor the vulnerability exploiters' schema and append plugins to it. In the end, we should have a single `VulnerabilityExploiters` object in the schema that is composed both of plugins and of hard-coded exploiters.

## Notes

First do #2787. These changes will break UI, until #2698 is done, consider merging these changes into a separate branch

## Tasks

- [x] Refactor exploiters in `common.agent_configuration.agent_sub_configurations.ExploitationConfiguration` from `Tuple[PluginConfiguration, ...]` into an empty `Dict` (or similar). (0d) - @VakarisZ 
- [x] Refactor `monkey/monkey_island/cc/services/agent_configuration_schema_service.py` (probably the code in repository utils) to add the plugin schema to the exploiters' schema. - @VakarisZ 
    - [x] Define hard-coded exploiter "plugins" (0d)
        - [x] Define HadoopExploiter property
        - [x] Define Log4ShellExploiter property
        - [x] Define MSSQLExploiter property
        - [x] Define PowerShellExploiter property
        - [x] Define SSHExploiter property
        - [x] Define SMBExploiter property
        - [x] Define WmiExploiter property
        - [x] Define ZerologonExploiter property
    - [x] Modify the service to inject hard-coded "plugins" into the schema (0d)
- [x] Fix the logic in `infection_monkey.master.exploiter` to use the new schema (0d) - @VakarisZ 
- [ ] Modify BB test configurations (0.25d) - @VakarisZ
