### ISSUE TITLE
Merge brute force and vulnerability exploiters in the configuration

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2787]
## Description

The separation between brute force and vulnerability exploiters was based on the use case of "vulnerability scanning", which is no longer Infection Monkey's main goal. Ultimately, users should be able to configure the order that exploiters run in. While the UI doesn't allow this at the moment, the configuration can be manipulated manually to achieve this. However, vulnerability exploiters always run before brute force exploiters. In other words, this separation reduces the configurability of the system.

### Note

To avoid breaking `develop`, base all work off of [2787-merge-vulnerability-and-brute-force-exploiter-config](https://github.com/guardicore/monkey/tree/2787-merge-vulnerability-and-brute-force-exploiter-config).

## Tasks
- [x] Modify the `AgentConfiguration` object to contain only "Exploiters`  (0d) @mssalvatore 
    - [x] Pydantic object
    - [x] Unit tests
    - [x] Default configuration
- [x] Modify the UI to comply with the new configuration (0d) @ilija-lazoroski 
    - [x] UI Schema
    - [x] SafeOptionValidator 
- [x] Modify the logic in `infection_monkey.master.exploiter` to use the new configuration (0d) @mssalvatore 
- [x] Modify the logic in `monkey_island.cc.services.reporting.report` to use the new configuration (0d) @ilija-lazoroski 
- [ ] Modify the `path_in_schema` in the `AgentConfigurationSchemaService` (0.25d) @ilija-lazoroski 
- [ ] Fix BB tests (0.25d)
