### ISSUE TITLE
Perform OS compatability checks before running exploiter plugins

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2788]
## Description

The agent should not attempt to exploit a target machine if it knows the the target machine's OS is incompatible with the exploiter. For example, the Zerologon exploiter should never attempt to exploit a Linux machine.

Currently, this logic is in the `AutomatedMaster` and isn't able to handle plugins. This logic should be moved to the puppet and modified to handle exploiter plugins.

## Tasks
**Merge PRs to ﻿﻿[2788-agent-os-compatibility-checks](https://github.com/guardicore/monkey/tree/2788-agent-os-compatibility-checks) branch**
- [x] Create an `AgentPluginManifest` for all hard-coded "plugins" (0d) @ilija-lazoroski 
    - [x] Hadoop
    - [x] Log4Shell
    - [x] MSSQL
    - [x] PowerShell
    - [x] SSH
    - [x] SMB
    - [x] WMI
    - [x] Zerologon
- [x] Create new exceptions to allow the Puppet to reject the master's requests (0d) @ilija-lazoroski 
    - [x] Create RejectedRequestError
    - [x] Create IncompatibleOperatingSystemError(RejectedRequestError)
- [x] Add `PluginCompatabilityVerifier` (0d) @ilija-lazoroski 
    - [x] Accepts `IIslandAPIClient` in the constructor
    - [x] Accepts the hard-coded plugin manifests in the constructor
    - [x] Implement `verify_exploiter_compatibility(exploiter_name: str, target_host: TargetHost)` (See `test_exploiter.py` for some useful test examples`)
        - [x] Use the `IIslandAPIClient` to get and cache the plugin manifest
            - [x] Add method to `IIslandAPIClient` to retrieve plugin manifest 
        - [x] Return if target host's OS is `None` or target_host's OS is in the plugin manifest's list of supported operating systems, else raise `IncompatibleOperatingSystemError`
- [x] Modify the puppet (Add the `PluginCompatibilityVerifier`, modify `exploit_host()`) (0d) @ilija-lazoroski 
    - [x] Add unit tests
    - [x] Call `verify_exploiter_compatability()` before exploiting the target (or loading the plugin)
    - [x] Add a `":raises IncompatibleOperatingSystemError:"` entry to the `IPuppet`'s docstring
- [x] Modify the `master.exploiter` to allow puppet to determine OS compatibility (0d) @ilija-lazoroski 
    - [x] Add unit tests
    - [x] Remove the existing compatibility check
    - [x] Try/except `IncompatibleOperatingSystemError` and log a message about skipping the exploiter
