### ISSUE TITLE
Bulid OS-specific plugin objects

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2811]
## Description

Plugins that can be run from more than one host OS may require different dependencies. This is commonly the case with compiled/extension modules. When an agent requests a plugin from the Island, it needs to receive a plugin that is compatible with its OS.

To achieve this, plugins may be packaged with multiple `vendor/` directories. The Island will repackage the plugin when it is requested by the agent. A plugin's `source_archive` should contain `vendor/ XOR (vendor-linux/ or vendor-windows/)`. When the Island parses the plugin, it can repackage the `source_archive` so that it contains only the vendor directory for a single host OS.

To clarify: The agent expects the `source_archive` to contain `vendor/` only. The Island will need to parse the `source_archive` it's provided, rename OS-specific vendor directories, and produce multiple plugins whose source archives contain the correct vendor directory.

## Tasks
**Merge PRs to the [2811-os-specific-plugins](https://github.com/guardicore/monkey/tree/2811-os-specific-plugins) branch.**

- [x] Add `host_operating_systems: Tuple[OperatingSystem, ...]` to `AgentPlugin` (Refactor 2811-os-specific-plugins branch) - (0d)  @shreyamalviya 
- [x] Rework the plugin parser to return `Mapping[OperatingSystem, AgentPlugin]` (0d) @shreyamalviya 
    - [x] Produce new `TarFile` object(s) containing `plugin.py`, any other source code, and a single `vendor/` directory
    - [x] If `plugin.tar` contains `vendor/` return `Mapping[OperatingSystem, AgentPlugin]` where the `AgentPlugin` is the same instance
    - [x] If `plugin.tar` does not contain `vendor/`, return a dict with one `AgentPlugin` per `vendor-[OS]` where the `AgentPlugin` instances are OS-specific
- [x] Refactor `IAgentPluginRepository.get_plugin(self, host_operating_system: OperatingSystem, plugin_type: AgentPluginType, name: str)` (0d) @cakekoa 
    - [x] Return a plugin that matches `host_operating_system`
- [x] Refactor the `/api/agent-plugins/OS/TYPE/NAME` endpoint to accept an OS in URL(0d) @cakekoa 
- [x] Refactor `IIslandAPIClient` and `HTTPIslandAPIClient.get_agent_plugin()` to match `IAgentPluginRepository.get_plugin()` (0d) @mssalvatore 
- [x] Refactor the `PluginRegistry` to request the plugin for the host OS (0d) @mssalvatore 
- [x] Create a new mock plugin with OS-specific vendor directories and test everything end-to-end (0d) - @shreyamalviya
