### ISSUE TITLE
Agent leaves hanging child processes

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2820]
## Description

After the agent completes its task, it is unable to exit. It seems that the process is being kept open by its child processes. It's unclear why the child processes do not exit. This occurs intermittently but happens most frequently if the agent is run within a docker container.

The effects of this are:
1. The agent leaves processes hanging around and consuming some small amount of resources
2. Other agents cannot start on the machine since the `SystemSingleton` is never properly released. It would seem that maybe one of the child processes has a copy of the file descriptor for the unix socket, but it's not quite clear how that's possible since this occurs even of the child processes are spawned before the socket is opened.

## Tasks
- [ ] Fix it (0.5d) @cakekoa 
    - [ ] Rebase on develop
    - [ ] Run ETE tests

**Comment by mssalvatore** [comment]
It turns out the root cause was the Log4Shell exploiter's LDAP server was not being properly closed. This is resolved by a1a0f5571c8938112889e2b35095671843f74474.
