### ISSUE TITLE
Only pass legacy credentials to legacy exploiters

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2830]
# Refactor

## Component(s) to be refactored

- `infection_monkey.master.exploiter`

## Explanation

Exploiter plugins will use the agent's credentials repository to retrieve credentials if they need them. Legacy exploiters are passed credentials in their options [code](https://github.com/guardicore/monkey/blob/e796edf1b62cc18bee7c10751e6cf16bcf7bc35d/monkey/infection_monkey/master/exploiter.py#L77-L89)

Create a list of non-plugin exploiters that require credentials. Modify the agent so that legacy credentials are only passed to those exploiters.

https://github.com/guardicore/monkey/blob/73abd4d08193506008c49b798b90bee6ab01c678/monkey/infection_monkey/master/exploiter.py#L135-L164

## Tasks
- [ ] Fix it (0.75d) @cakekoa 
    - [ ] Create a list of non-plugin exploiters that require credentials
    - [ ] Modify the agent so that legacy credentials are only passed to those exploiters
