### ISSUE TITLE
Add a `version` field to `AgentPluginManifest`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2873]
## Description

Plugins should have their own versions so that they can be updated and versioned independently of the core system. Since plugins are not expected to be installable Python (pip) packages, they should use [semantic](https://semver.org/) versioning, **not** [PEP 440](https://peps.python.org/pep-0440/) versioning.

### Resources
https://python-semver.readthedocs.io/en/latest/advanced/combine-pydantic-and-semver.html

## Tasks

- [ ] Add a version field to the `AgentPluginManifest` (0.25d) @ilija-lazoroski 
- [x] Add version field to all manifests (0d) @ilija-lazoroski 
    - [x] hadoop plugin
    - [x] hard-coded exploiters
    - [x] mock plugins
