### ISSUE TITLE
Build Island's with the hadoop plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2886]
## Description

The hadoop plugin needs to be packaged with the Islands at build time, since we don't yet have a mechanism for downloading plugins from a public repository.

## Tasks
- [x] Add a jenkins job to build the hadoop plugin (0d) @cakekoa 
    - [x] Note: The plugin should be built using the same docker image as the Agent.
- [x] Modify the island build jobs to copy the plugin artifact into a predetermined location, such as `$WORKSPACE/monkey/monkey_island/plugins`
    - [x] MSI (0d) @cakekoa 
    - [x] AppImage (0d) @cakekoa 
    - [x] Docker (0d) @cakekoa 
- [x] Add code in the Monkey Island's server setup to copy the built-in plugins to `$data_dir/plugins` when it starts. (0d) @cakekoa @ilija-lazoroski
