### ISSUE TITLE
Write a custom component for SSHKeypair objects in UI

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#2950]
Write a custom component that will add `SensitiveText` widget to the UISchema for the private key of SSH keypair list

# Tasks
* [ ] Write a custom `SSHkeyPairComponent` that will display two textarea wdigets for `public_key` and `private_key`
    * [ ] `private_key` needs to be of type `SensitiveText`
    * [ ] Note: Verify that it works with a ssh keypair used from the UI
