### ISSUE TITLE
Address deprecation warnings

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2971]
## Description

Upgrading the Python version in #2705, will result in a number of deprecation warnings. Fix them!

## Tasks
- [x] Fix deprecation warnings (0d) - @shreyamalviya 
- [x] Remove dependency on `typing-extensions` (0d) - @shreyamalviya 
- [x] Rebase https://github.com/paramiko/paramiko/pull/2013 on the latest release and test (0d) @mssalvatore
