### ISSUE TITLE
Publish Monkey Island v2.0.0 to dockerhub

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3013]
## Description

Publish Monkey Island v2.0.0 to dockerhub

Release process is:
If `IS_RELEASE` checkbox is checked, the image gets uploaded to dockerhub tagged as `*-beta`
    MAKE SURE IT DOESN'T OVERWRITE THE `:latest` TAG
Modify the release documentation to modify the tag on the image as a final step.

## Tasks
- [x] Create a new dockerhub repository for Monkey Island (0d) @cakekoa 
  - We currently build an image named `guardicore/monkey-island`. An appropriate repository name would be `monkey_island`, and since our docker hub account name is `infectionmonkey` the image would be named `infectionmonkey/monkey_island`
  - We should update our docker build script to use the `infectionmonkey/` prefix instead of `guardicore` when building the image
- [x] Publish Monkey Island v2.0.0 to dockerhub (0d) @ilija-lazoroski 
- [x] Update docker installation documentation (0d) @ilija-lazoroski 
- [x] Update the jenkins job to work as described above (0d) @ilija-lazoroski 
- [x] Update release documentation to modify the `*-beta` tag to drop "beta" and overwrite `:latest` (0d) @ilija-lazoroski
