### ISSUE TITLE
Convert hard coded plugins in config to Dict type

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3028]
# Refactor

Some hard-coded plugins have a different format in the agent configuration schema from other plugins. This inconsistency results in a lot of needless code all over the place. 

## Tasks

- [ ] Refactor credential collectors to Dict
	- [ ] Change AgentConfigurationSchema
	- [ ] Change BB test configs
	- [ ] Change UT data
- [ ] Refactor fingerprinters to Dict
	- [ ] Change AgentConfigurationSchema
	- [ ] Change BB test configs
	- [ ] Change UT data
	- [ ] Change infection_monkey.master.propagator.Propagator._add_http_ports_to_fingerprinters
- [ ] Replace advanced selectors with PluginObjectFieldTemplate
- [ ] Change safe option validator

**Comment by mssalvatore** [comment]
In v2.3.0, there will be no more hard-coded plugins.
