### ISSUE TITLE
Generalizable plugin build scripts

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3040]
## Description
Make reusable/generalizable build scripts for plugins

## Tasks
- [ ] Make `hadoop/build.sh` generalizable and reusable (0.25d) @ilija-lazoroski 
    - [ ] Update hadoop jenkins job
- [ ] Make the Hadoop `build_plugin.sh` reusable/generalizable (0.5d)
