### ISSUE TITLE
Use Prettier for UI code formatting

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3070]
# Refactor

[Prettier](https://github.com/prettier/prettier) is like black, but for front-end code. Inluding it in the project would make front end code more readable because the whole codebase would contain consistent formatting. 

# Tasks

 - [ ] Reformat the codebase
 - [x] Add Prettier to the dev requirements
 - [x] Add a pre-commit hook
 - [x] Add a step in travis

## Explanation

UI has a lot of inconsistencies in the formatting (more so than back-end). Do we do `if(something){` or `if (something) {`? Do all lines end with `;`? These questions can be forgotten if we run prettier by default

**Comment by cakekoa** [comment]
I have verified that eslint is using prettier for the nextjs UI, and that it is run as part of the pre-commit hooks.
I have also verified that it is being run as part of the travis build as well.
