### ISSUE TITLE
Implement OTP compliance on the Agent

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3077]
## Tasks

- [x] Add methods to `IIslandAPIClient` and `HTTPIslandAPIClient` that: (0d) - @VakarisZ 
    - [x] Fetch new OTPs from the Island
    - [x] Trade OTPs for auth 
- [x] Adjust the agents to look for environmental variable with an OTP (0d) @VakarisZ 
    - [x] Get the OTP from the environment
    - [x] Clean up the OTP environmental variable
    - [x] Trade OTP for auth token
    - [x] `IIslandAPIClient` makes all future calls using the auth token
    - [x] Make sure to avoid unnecessary temporal coupling
    - [x] Write tests for HTTPClient or HTTPIslandAPIClient that verify an auth token in all calls 
- [x] Add `IOTPProvider` that will allow Exploiters to get OTPs (0d) - @shreyamalviya 
- [x] Add a concrete implementation of `IOTPProvider` that wraps an `IIslandAPIClient` (0d) - @shreyamalviya 
- [x] Construct exploiters with `IOTPProvider` (0d) - @shreyamalviya 
    - [x] Construct an `IOTPProvider` in `monkey.py`
    - [x] Pass it to the constructor of `PluginRegistry` and construct plugins with the component
    - [x] Pass it to hard-coded exploiters on construction
- [ ] Adjust propagation to add OTP to agent execution commands (0.25d) - @shreyamalviya 
    - [x] hadoop
    - [x] log4shell
    - [x] mssql
    - [x] powershell
    - [x] ~smbexec~ (moved to #2952)
    - [x] sshexec
    - [x] wmiexec
- [x] Make sure we're not logging (leaking) OTPs (0d) - @shreyamalviya
