### ISSUE TITLE
Implement OTP/AgentAuthentication in the Island

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3078]
## Tasks
- [x] Investigate the OTP generation methods used and improve OTP infrastructure (0d) @cakekoa:
    - [ ] ~Remove unused endpoints~
    - [x] Make sure the secrets are properly generated
        - Use our `secure_generate_random_string()` utility, with at least the 62 alphanumeric, preferably with known command-line safe chars as well
        - 32 characters
    - [x] Define a reasonable timeout
        - 2 minutes
    - [x] Rate limit token fetching API (preferably we just generate very large (32 bytes or larger) OTPs)
        - Still want to do this, to prevent DOS. Can we do this on a per-user level? Look at Flask's offerings
    - [x] Prevent OTP reuse: Make sure used OTPs cannot be reused
- [x] Implement the endpoint for authenticated agents to fetch an OTP. (0d) - @shreyamalviya 
- [x] Implement the endpoint where the agent could submit the OTP to get an authentication token. (0d) - @shreyamalviya 
    - [x] Create agent user/role
    - [x] Invalid token if it has been used.
- [x] Secure relevant endpoints for the agent user roles. All endpoints should require authentication by the island user and/or the agent user, except login and registration. (0d) - @shreyamalviya 
- [x] Make sure tokens/session are cleaned up properly on timeout or on agent shutdown. (0d) @cakekoa 
    - [x] Delete agent users 
    - [x] Delete any agent users that do not exist in the agent repository (watch out for race conditions)
- [ ] Change the manual run UI to generate commands with OTP's. (0.5d) @cakekoa 
    - [ ] ~(optional) Add a BB test for manual runs~
    - [ ] ~Make OTP all *~ @ilija-lazoroski 
    - [x] Add a refresh button to refresh the OTP
    - [x] Refresh automatically every time the "copy to clipboard" button is pushed
    - [x] Refresh automatically on `ctrl-c`
    - [x] Display a countdown @cakekoa  
        - [ ] ~Better display?~
- [x] Change the "Run from island" button to generate and execute an OTP (0d) @cakekoa 
- [x] Update documentation for the manual run page (0d) - @shreyamalviya 
- [x] Make sure we're using the OTP objects everywhere and not strings. @mssalvatore 
- [x] Make the Token type a SecretStr and move it to common (use in the Agent as well) (0.25d) @cakekoa 
- [x] Agent logs out after cleanup (0d) @cakekoa 
- [x] Invalidate all OTPs on startup. @cakekoa 
- [x] Rate limit the login endpoint (3/second should be plenty for an interactive login, yeah?) @mssalvatore 
    - [ ] ~Add BB test~ Not worth the struggle ATM.
- [x] Fix agent otp rate limiting key (user, not ip) @cakekoa 
- [x] Remove the `AGENT_OTP_FLAG` feature flag (agent)

**Comment by ilija-lazoroski** [comment]
`passlib` as a whole doesn't have OTP generation algorithms, but it has `otp` wrapper for the  `oath` library which provides a TOTP class for generating TOTP (Time-based One-Time Password) tokens, and a HOTP class for generating HOTP (HMAC-based One-Time Password) tokens.

Regarding the OTP itself, I would suggest that we use alphanumeric OTPs, because a 6-digit numeric OTP can have 1 million possible combinations (10^6), whereas a 6-character alphanumeric OTP using upper and lowercase letters and numbers can have over 2 billion possible combinations (62^6).

For the length itself, based on some research I would suggest somewhere between 8-10 alphanumeric chars. I am keen on 10 alphanumeric chars as the possible combinations are 62^10 which is roughly 839 trillion combinations. So no place for brute-forcing.

**Comment by cakekoa** [comment]
The `Flask-Limiter` package will allow us to rate-limit our endpoints. We can specify a limit like "10/s" that will limit the endpoint to a maximum of 10 in a second. A `key_func` can be provided, which allows one to specify how keys are determined (the rate limit is applied per-key). It defaults to using the remote IP, but we can leverage it to specify users
