### ISSUE TITLE
Test for XSS vulnerabilities

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3081]
## Description

The two main vectors for XSS attacks are plugins (via the titles/descriptions in the manifest or config schema) and an imported configuration. Verify the Island UI is safe from XSS attacks from these two vectors.

Pay special attention to any uses of `dangerouslySetInnerHTML`.

## Tasks
- [x] Prove the Island UI is safe from XSS attacks if malicious plugins are loaded (0d)
    - [x] Manifest
    - [x] Config Schema
    - [x] Disallow malicious plugins in the backend
- [x] Prove the Island UI is safe from XSS attacks if a malicious config is imported (0d)
- [x] Prove that other inputs are safe from XSS attacks (0d)
