### ISSUE TITLE
Re-arrange UI sidebar

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3133]
# Refactor

## Component(s) to be refactored

The configuration should be the first step in the sidebar:

![image](https://user-images.githubusercontent.com/36815064/226922181-738a06ea-5745-427d-a5ef-88641e467ce6.png)

## Tasks

- [ ] Move configuration to be the first step in the navigation
- [ ] Make it "marked" if the configuration was modified (not default)
- [ ] Re-arrange the cards in the home page (move configuration to be first)
