### ISSUE TITLE
Generate refresh token

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3137]
## Generate our own refresh token:
We could generate a token that's exactly the same as the authentication token, but with an extended lifespan (we need to use a custom TimestampSigner that uses not the current time, but current time + REFRESH_TIMEDELTA as its timestamp). The only difference between the authentication token and the refresh token would be that the refresh token has a longer lifespan. Then, we would add another endpoint.

## Tasks:

 - [x] Create a refresh token (0d) @VakarisZ 
 - [x] Modify login and registration to return refresh token (0d) @VakarisZ 
 - [x] Add an endpoint that allows you to login with a refresh token
 - [x] Make a refresh token distinct from access token @VakarisZ 
 - [x] Add logic to the agent to use the refresh token (0d) - @shreyamalviya 
 - [x] Adjust the times for refresh and authentication token (0d) @VakarisZ 
 - [x] Redesign refresh strategy (1.25d)
    - [x] BB test to verify old tokens are invalid after refresh
    - [x] Add expiration time to all responses with tokens
    - [x] Modify the agent to use the new scheme
    - [x] Make the agent's HTTPIslandAPIClient to be multiprocessing-safe @cakekoa 
    - [x] Add logic to the UI to use the refresh token @ilija-lazoroski 
 - [ ] Cleanup vulture allowlist
