### ISSUE TITLE
Migrate the WMI exploiter to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3163]
## Description

Replace the hard-coded WMI exploiter with a new and improved, fully tested, WMI exploiter plugin with high code quality. Leverage the `BruteForceExploiter` to minimize code duplication.

Use the SMBExploiter as a template.

## Tasks
- [x] options (pydantic) - @shreyamalviya 
    - [x] determine what options WMI should have
    - [x] create a pydantic model for WMI options
- [x] Create plugin manifest - @shreyamalviya 
- [x] Create config schema - @shreyamalviya 
- [x] Create a Pipfile for dependencies - @shreyamalviya 
- [x] Add a jenkins job to build the plugin - @shreyamalviya 
- [x] plugin.py (0d) - @shreyamalviya 
- [x] command builder (0d)- @shreyamalviya 
- [x] exploit client (0d) @cakekoa 
    - [x] Don't forget to add MITRE tags
- [x] Update the island build jobs on Jenkins to copy the artifacts from the WMI plugin build job (0d) @mssalvatore 
- [x] Update ETE test configurations (0d) - @shreyamalviya 
- [x] Remove the hard-coded WMI plugin (0d) - @shreyamalviya 
- [x] Check preconditions in plugin.py (0d)
- [x] Extra and ETE testing (0d) @cakekoa 
- [x] Remove Vulture entries
