### ISSUE TITLE
Migrate the ZeroLogon exploiter to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3164]
## Description

Replace the hard-coded ZeroLogon exploiter with ZeroLogon exploiter plugin. 

Use the SMBExploiter and/or HadoopExploiter as templates.

## A note on scope
The ZeroLogon exploiter is large and complex. There's lots of room for improvement in its code quality, however, the time it would take to reimplement it is probably not worth the value on such an old vulnerability. We can make small improvements, but should avoid getting sucked into a large refactor of this exploiter. In other words, if we can simply wrap the existing exploiter with a `plugin.py`, let's do that (as much as is possible).

## Tasks
- [x] options (pydantic) (0d) @cakekoa 
    - [x] determine what options ZeroLogon should have
    - [x] create a pydantic model for ZeroLogon options
    - [x] Create plugin manifest
    - [x] Create config schema
- [x] Create a Pipfile for dependencies (0d) @mssalvatore 
- [x] Add a jenkins job to build the plugin (0.25d) @cakekoa 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the ZeroLogon plugin build job
- [x] exploiter (0d) @cakekoa 
    - [x] Check any preconditions
    - [x] Don't forget to add MITRE tags
- [x] Update ETE test configurations and run tests (0d) @cakekoa 
- [x] Remove the hard-coded ZeroLogon plugin (0d) @mssalvatore 
- [ ] Test and fix bugs (0.5d) @shreyamalviya
