### ISSUE TITLE
Migrate the PowerShell exploiter to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3165]
## Description

Replace the hard-coded PowerShell exploiter with a new and improved, fully tested, PowerShell exploiter plugin with high code quality. Leverage the `BruteForceExploiter` to minimize code duplication.

Use the SMBExploiter as a template.

## Tasks
- [x] Create plugin skeleton (0d) - @shreyamalviya 
    - [x] options (pydantic)
         - [x] determine what options PowerShell should have
         - [x] create a pydantic model for PowerShell options
    - [x] Create plugin manifest
    - [x] Create config schema
- [x] Create a Pipfile for dependencies (0d) - @shreyamalviya 
- [x] Create a credentials generator (0d) @mssalvatore 
- [x] plugin.py (0d) - @shreyamalviya 
    - [x] Check preconditions in plugin.py 
- [x] command builder (0d) @ilija-lazoroski 
- [x] exploit client (0.25d) @ilija-lazoroski 
    - [x] Don't forget to add MITRE tags
- [x] Update Jenkins (0d) - @shreyamalviya 
    - [x] Add a job to build the plugin
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the PowerShell plugin build job
- [x] Update ETE test configurations (0d) @cakekoa 
- [x] Remove the hard-coded PowerShell plugin (0.25d) @mssalvatore 
    - [x] Don't forget to remove the dependencies from the agent's Pipfile
- [x] Extra and ETE testing (0.5d)
