### ISSUE TITLE
Migrate Mimikatz credentials collector to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3168]
## Description

Migrate the Mimikatz credentials collector to a plugin.#3167 

## Tasks
- [x] Define config-schema.json, manifest, and options (0d) @ilija-lazoroski @ordabach 
- [x] Create pipfile for dependencies (0d) @ilija-lazoroski @ordabach 
- [x] Add A jenkins job to build the plugin (0d) @ilija-lazoroski @ordabach 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the Mimikatz plugin build job
- [x] Add a build script for building plugins on Windows. Modify the mimikatz jenkins job as necessary. (0d) @ilija-lazoroski, @shreyamalviya  
- [x] Convert the existing mimikatz collector to a plugin (0d) @mssalvatore 
    - [x] Update ETE test configuration
    - [x]  Reimplement unit tests
- [x] Remove the hard-coded mimikatz credentials collector plugin (0d) @mssalvatore 
- [x] Fix wmi_mimikatz and depth_1 smb mimikatz tests (see below) (0d) - @shreyamalviya 
    - [x] Remove wmi_mimikatz test
    - [x] Modify depth_1_a to call the stolen credentials endpoint and assert that expected credentials were stolen
- [x] Remove vulture entries
- [x] Fix logging (leaking credentials) (0d) @ilija-lazoroski 

## Broken tests

![image](https://user-images.githubusercontent.com/19957806/234954932-e9227d0f-8349-42ed-818b-5c3eb341c997.png)

This test is supposed to test that credentials are collected from mimikatz 14 and used to access mimikatz 15. It should be a depth 2 test and shouldn't include valid credentials for mimikatz 15 in the configuration.

Also check the depth_1_a test, as this has comments about mimikatz password stealing.  I'm not sure how this can be properly tested with a depth 1 test.
