### ISSUE TITLE
Migrate SSH credentials collector to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3169]
## Description

Migrate the SSH credentials collector to a plugin.#3167 

## Tasks
- [ ] Build a SSH credentials collector plugin
- [ ] Remove the hard-coded SSH credentials collector plugin
- [ ] Remove any references to hard-coded credentials collectors, their manifests, etc.
