### ISSUE TITLE
Migrate the SSH exploiter to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3170]
## Description

Replace the hard-coded SSH exploiter with a new and improved, fully tested, SSH exploiter plugin with high code quality. Leverage the `BruteForceExploiter` to minimize code duplication.

Use the SMBExploiter as a template.

## Tasks
- [x] Plugin skeleton (0d) - @shreyamalviya 
    - [x] options (pydantic)
        - [x] determine what options SSH should have
        - [x] create a pydantic model for SSH options
    - [x] Create plugin manifest 
    - [x] Create config schema
- [x] Create a Pipfile for dependencies (0d) - @shreyamalviya 
- [x] Update Jenkins (0.25d)
    - [x] Add a jenkins job to build the plugin - @shreyamalviya 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the SSH plugin build job
- [x] plugin.py (0d) - @shreyamalviya 
- [x] command builder (0d) - @shreyamalviya 
- [x] exploit client (0d) @ilija-lazoroski 
    - [x] Don't forget to add MITRE tags
    - [x] Check preconditions in plugin.py
- [x] Update ETE test configurations (0d) @cakekoa 
- [x] Remove the hard-coded SSH plugin (0d) @cakekoa 
    - [x] Remove vulture entries
    - [x] Fix command builder OS check (0d)
- [x] Extra and ETE testing (0d)

**Comment by shreyamalviya** [comment]
> Remove `cryptography.hazmat.primitives.padding` from hidden imports in `monkey.spec`; test and make sure nothing is broken

Removing `cryptography` from the Agent dependencies (which we need to do so that PowerShell doesn't use the Agent's `cryptography`) stops the Agent from running at all, it throws this error

```
Traceback (most recent call last):
  File “infection_monkey/main.py”, line 25, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/dropper.py”, line 15, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/utils/commands.py”, line 7, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/exploit/__init__.py”, line 2, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/exploit/caching_agent_binary_repository.py”, line 7, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/island_api_client/__init__.py”, line 12, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “infection_monkey/island_api_client/configuration_validator_decorator.py”, line 3, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “jsonschema/__init__.py”, line 17, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “jsonschema/validators.py”, line 19, in <module>
  File “<frozen importlib._bootstrap>“, line 1178, in _find_and_load
  File “<frozen importlib._bootstrap>“, line 1149, in _find_and_load_unlocked
  File “<frozen importlib._bootstrap>“, line 690, in _load_unlocked
  File “PyInstaller/loader/pyimod02_importers.py”, line 385, in exec_module
  File “jsonschema_specifications/__init__.py”, line 11, in <module>
  File “referencing/_core.py”, line 297, in __rmatmul__
  File “jsonschema_specifications/_core.py”, line 27, in _schemas
  File “pathlib.py”, line 931, in iterdir
FileNotFoundError: [Errno 2] No such file or directory: ‘/tmp/_MEIdptIST/jsonschema_specifications/schemas’
```

PR to update the comment in `monkey.spec`

**Comment by ilija-lazoroski** [comment]
Closed by https://github.com/guardicore/monkey/pull/3465
