### ISSUE TITLE
Migrate the MSSQL exploiter to a plugin 

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3171]
## Description

Replace the hard-coded MSSQL exploiter with a new and improved, fully tested, MSSQL exploiter plugin with high code quality. Leverage the `BruteForceExploiter` to minimize code duplication.

Use the SMBExploiter as a template.

## Tasks
- [x] Create plugin skeleton (0d) @ilija-lazoroski 
    - [x] options (pydantic)
         - [x] determine what options MSSQL should have
         - [x] create a pydantic model for MSSQL options
    - [x] Create plugin manifest
    - [x] Create config schema
- [x] Create a Pipfile for dependencies (0d) @mssalvatore 
- [x] plugin.py (0d) @ilija-lazoroski 
    - [x] Check preconditions in plugin.py (Verify that the port is `NetworkService.MSSQL` or `NetworkService.UNKNOWN` if it's open)
- [x] command builder (0d) - @shreyamalviya
- [x] Create MSSQL exploiter class (0d) @ilija-lazoroski 
- [x] exploit client (0d)  @ilija-lazoroski 
    - [x] Don't forget to add MITRE tags
- [x] Add a jenkins job to build the plugin (needs to build windows dependencies) @cakekoa (0d)
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the MSSQL plugin build job
- [x] Update ETE test configurations (0.25d) - @shreyamalviya 
- [x] Remove the hard-coded MSSQL plugin (0d) - @shreyamalviya 
    - [x] Don't forget to remove the dependencies from the agent's Pipfile
- [x] Extra and ETE testing (0d)
- [x] Remove vulture entries
