### ISSUE TITLE
Implement an SNMP exploiter

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3234]
## Description

Implement an exploiter that uses SNMP to propagate to Linux hosts.

Related: #3198 

## Tasks

- [x] Add a vulnerable machine to terraform/GCP (test2 environment) (0d) @cakekoa 
- [x] Figure out how to replicate the PoC commands with pysnmp (0d) @cakekoa @mssalvatore 
- [x] Create plugin manifest (0d) @cakekoa 
- [x] Create a Pipfile for dependencies (0d) @cakekoa 
- [x] plugin.py (0d) @cakekoa 
- [x] Generate community strings by getting all usernames and passwords (0d) @cakekoa 
- [x] command builder (0d) @cakekoa 
- [x] exploiter (0d) @cakekoa 
    - [x] Don't forget to add MITRE tags
- [x] Add a jenkins job to build the plugin (0d) @mssalvatore 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the SNMP plugin build job
- [x] options (pydantic) (0d) @cakekoa 
    - [x] determine what options SNMP should have
    - [x] create a pydantic model for SNMP options
    - [x] create a config schema
- [x] Update ETE test configurations (0d) @ilija-lazoroski 
- [x] Document the new exploiter (0d) @cakekoa 
- [x] Add Bash Dropper (0.5d) @mssalvatore 
- [x] Test (0d)
- [x] Fix InconsistentValueError (0d) @cakekoa

**Comment by cakekoa** [comment]
Proof-of-concept: https://github.com/mxrch/snmp-shell.git

**Comment by cakekoa** [comment]
Here's some example code showing how to create, execute, and delete a command via SNMP:
[snmp.txt](https://github.com/guardicore/monkey/files/11400107/snmp.txt)
