### ISSUE TITLE
Create AgentBinaryService

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3240]
# Refactor

## Component(s) to be refactored

- IAgentBinaryRepository
- AgentBinaryRepository
- resources.AgentBinaries

## Explanation
Consolidate components related to managing and retrieving agent binaries into `AgentBinaryService`. The `IAgentBinaryService` interface should match `IAgentBinaryRepository` (for now).

## Context

This change serves two purposes
1. Further the goal of improving cohesion throughout the Island
2. Support the "Malware Masquerade" feature #3241.

## Tasks
- [ ] Create `IAgentBinaryService` (0.25d) @mssalvatore 
- [ ] Implement `IAgentBinaryService` (0.25d) @mssalvatore 
- [ ] Make "local run" dependent on `IAgentBinaryService` instead of `IAgentBinaryRepository` (0.25d) @mssalvatore 
- [ ] Consolidate `AgentBinaryRepository` under the agent service (0.25d) @mssalvatore 
- [ ] Consolidate agent binary resources under the agent service (0.5d) @mssalvatore 
    - [ ] Provide a registration function that Allows endpoints to be registered
