### ISSUE TITLE
Malware Masquerade (backend)

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3241]
## Description
**Masquerade** - to assume the appearance of something one is not [[1](https://www.merriam-webster.com/dictionary/masquerade)]

A common way of detecting and identifying an executable as malware it to write a detection rule (for a tool like YARA) that checks for the existence of strings or unique byte sequences within the file. In order to improve the fidelity of Infection Monkey's malware emulation, users should be able to specify arbitrary data that will be injected into the agent binaries. This will enable Infection Monkey Agents to masquerade as specific types of malware. This may be particularly useful for a user who writes their own detection rules and needs a way to test them.

## Approach

A null byte (or a few null bytes) followed by the desired data (bytes) can be appended to Linux or Windows binaries with no ill effects. The appended data will not execute, but simply be present within the binary.

See [[2](https://github.com/guardicore/monkey/issues/3224#issuecomment-1516355028)] for a note on signed Windows binaries.

## Tasks
- [x] Create a `MasqueradeAgentBinaryRepositoryDecorator`. This will wrap `IAgentBinaryRepository` methods and append the masque data (supplied to the decorator's constructor) to the agent binaries when they are requested. (0d) @ilija-lazoroski 
    - [x] Don't forget caching
- [x] Add a `apply_{linux,windows}_masque(masque: Optional[bytes])` function to `IAgentBinaryService` (0d) @mssalvatore 
    - [x] Implement `AgentBinaryService.apply_{linux,windows}_masque(masque: Optional[bytes])`, It should apply the masque decorator to the repository if the `masque` is not `None`, or remove the decorator if `masque` is `None`.
- [x] Add flask resources for `GET/PUT  /api/agent-binaries/{linux,windows}/masque` (0d) - @shreyamalviya 
    - [x] The endpoint should accept raw bytes/octets 
    - [x] Don't forget unit tests
- [ ] Modify one or more ETE tests to apply a masque. (0.75d) - @shreyamalviya 
    - [x] Depth 1
    - [x] Depth 4
- [x] Remove vulture entries
