### ISSUE TITLE
Enable the user to add arbitrary strings to the agent's masque

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3242]
## Description

The web UI must enable users to set the agent's masque (see #3241). The simplest thing would be to provide string fields to users (similar to how users specify IP addresses in network configuration). The UI would transform the strings to bytes and separate them with null characters (0x00).

## Notes:
    On UI load:
        call GET /api/agent-binaries/{linux,windows}/masque and populate the tab
    On submit:
        if detection data is set:
            call SET /api/agent-binaries/{linux,windows}/masque=masque
        else:
            call SET /api/agent-binaries/{linux,windows}/masque = None

    On export:
        Add a new export section for masques and put the data in it.

    On import:
        If the masque section has data:
            call SET /api/agent-binaries/{linux,windows}/masque = masque
        else if data section is empty or missing:
            call SET /api/agent-binaries/{linux,windows}/masque = None

## Tasks
- [ ] Add the necessary fields to the UISchema
- [ ] Populate the field/data from the Island on config UI load
- [ ] On submit
  - [ ] strip the masque fields from the UI schema
  - [ ] call the appropriate endpoint(s) with the masque data
- [ ] Implement export
- [ ] Implement import
