### ISSUE TITLE
Leaking OTP in Hadoop plugin 

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#3296]
## Describe the bug
It seems that we are leaking OTP in Hadoop payload logging

## To Reproduce
1. Configure the Monkey with Hadoop plugin
2. Run the monkey on any hadoop machine
3. Observe logs

## Expected behavior
We shouldn't be logging OTP.

## Screenshots
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/15820737/235936996-9a4fc4d1-3598-439a-acdb-a63add6a42b3.png">

## Machine version (please complete the following information):
 - OS: Windows or Linux

## Tasks
- [ ] Fix up logging level in Hadoop plugin
   - [ ] Do not forget to rebuild the plugin
- [ ] Fix the regex in OTPFormatter
   - [ ] Store the OTP character set in `common` and use it in `OTPFormatter` and `AuthenticationFacade.generate_otp()`
   - [ ] Compile regexes as class variables so they don't need to be recompiled for every single log message

**Comment by shreyamalviya** [comment]
The regex in `OTPFormatter` needs to be fixed.

**Comment by mssalvatore** [comment]
We should also consider modifying the plugin to not leak this in the first place.

**Comment by mssalvatore** [comment]
> The regex in `OTPFormatter` needs to be fixed.

A few improvements that can be made:
1. Store the OTP character set somewhere in `common` so the regex and the `generate_otp()` function are kept in sync
2. Compile the regexes once as a class variables, instead of every time the `format()` function is called.
