### ISSUE TITLE
Ransomware AES256 Prototype

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3379]
## Description

We've received multiple requests for a real encryption algorithm in the ransomware module. Add AES256 encryption as an option. We need to get this out to a user quickly, so for the moment we'll keep things simple.

1. Use pyAesCrypt to encrypt the file (not in place)
2. Use "m0nk3y" as the pasword.
3. Provide the user with a dropdown in the UI that allows them to select the encryption algorithm

In the short term, this feature will only be available upon request. In other words, the release binaries will not be publicly available.

## Tasks
- [x] Create a new file encryptor that uses pyAesCrypt to encrypt files using the password "m0nk3y". @mssalvatore 
- [ ] Allow the user to select the encryption algorithm @mssalvatore 
    - [x] Add a new option (Enum) to `RansomwareOptions`
    - [x] Modify `build_ransomware()` to load the correct file encryptor  based on the options
    - [x] Modify the UI to give the user a dropdown to select the encryption algorithm. Make a note that AES256 is a less safe choice.
