### ISSUE TITLE
Add a recursive option to ransomware

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3380]
## Description

We've received multiple requests for recursive directory traversal in the ransomware module. Add AES256 encryption as an option. We need to get this out to a user quickly, so for the moment we'll keep things simple.

In the short term, this feature will only be available upon request. In other words, the release binaries will not be publicly available.

## Tasks
- [ ] Create a new `RecursiveTargetFileSelector`
- [ ] Allow the user to select whether or not file selection is recursive
    - [ ] Add a new boolean option to `RansomwareOptions`
    - [ ] Modify `build_ransomware()` to load the correct file selector based on the configuration
    - [ ] Modify the UI to give the user a checkbox for recursive encryption. Make a note that this is not a production-safe choice.

## Notes
This file selector should not follow symlinks or shortcuts. All selected files should be children of the specified directory. Consider using the method described [here](https://salvatoresecurity.com/preventing-directory-traversal-vulnerabilities-in-python/) to ensure encryption is confined to the specified directory.
