### ISSUE TITLE
Ransomware AES256 Prototype (stealth)

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3381]
## Description

We've received multiple requests for a real encryption algorithm in the ransomware module. It would be nice to have a stealthy AES256 encryption as an option. Since many ransomware detection techniques rely on certain system calls or instructions being used, a pure-python implementation is less likely to be detected.  We need to get this out to a user quickly, so for the moment we'll keep things simple.

1. Use pyaes to encrypt the file (not in place)
2. Use "m0nk3y" as the pasword.
3. Provide the user with a dropdown in the UI that allows them to select the encryption algorithm

In the short term, this feature will only be available upon request. In other words, the release binaries will not be publicly available.

## Tasks
- [ ] Create a new file encryptor that uses pyaes (CTR mode) to encrypt files using the password "m0nk3y".
- [ ] Allow the user to select the encryption algorithm
    - [ ] Add a new option (Enum) to `RansomwareOptions`
    - [ ] Modify `build_ransomware()` to load the correct file encryptor  based on the options
    - [ ] Modify the UI to give the user a dropdown to select the encryption algorithm. Make a note that Stealth AES256 is a less safe choice. Make a note about what makes Stealth AES256 "stealthy". Make a note that speed is greatly sacrificed.
