### ISSUE TITLE
Migrate the Log4Shell exploiter to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3388]
## Description

Replace the hard-coded Log4Shell exploiter with a new and improved, fully tested, Log4Shell exploiter plugin.

## Tasks
- [x] Create plugin skeleton (0d) @cakekoa  
    - [x] options (pydantic)
         - [x] determine what options Log4Shell should have
         - [x] create a pydantic model for Log4Shell options
    - [x] Create plugin manifest
    - [x] Create config schema
- [x] Create a Pipfile for dependencies (0d) @ilija-lazoroski 
- [x] Migrate the `LDAPServer` from multiprocessing to multithreading (0d) - @shreyamalviya 
- [x] migrate the log4shell exploiter to a plugin (0d)
    - [x] plugin.py - @shreyamalviya 
    - [x] command builder - @ilija-lazoroski 
    - [x] exploiter - @shreyamalviya 
    - [x] exploit client - @ilija-lazoroski 
    - [x] use `HTTPBytesServer` in place of `ExploitClassHTTPServer` - @shreyamalviya 
- [x] Update Jenkins (0d)
    - [x] Add a jenkins job to build the plugin (needs to build windows dependencies) - @shreyamalviya 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the Log4Shell plugin build job
- [x] Update ETE test configurations (0d) - @shreyamalviya 
- [x] Remove the hard-coded Log4Shell plugin (0d) - @shreyamalviya 
    - [x] Don't forget to remove the dependencies from the agent's Pipfile
    - [x] Remove WebRCE
    - [x] Remove vulture entries
- [ ] Extra and ETE testing (0.25d) @ilija-lazoroski 
- [ ] consolidate `from twisted.internet import reactor` imports and test; see [this](https://github.com/guardicore/monkey/pull/3439#pullrequestreview-1498345091)
