### ISSUE TITLE
Define payloads plugin interface

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3390]
## Description

In order to create payloads plugins, we must first define a plugin interface for payloads.

## Tasks
- [x] Define what should be passed to `Plugin.__init__()` for payloads (0d) @shreyamalviya 
- [x] Define what should be passed to `Plugin.run()` for payloads plugins and modify the puppet as necessary (0d) @shreyamalviya 
- [x] Define what should be returned from `Plugin.run()` (if anything) for payloads and modify the puppet as necessary (0d) @shreyamalviya 
- [x] Modify `PluginLoader._load_plugin_from_island()` to load payload plugins (0d) @shreyamalviya 
    - [x] Modify puppet to verify OS-compatibility before running payloads
- [x] Make the UI work for payload plugins (0d) @shreyamalviya 
- [x] Build a mock/test payload plugin and test the system end-to-end (0d) @shreyamalviya 
- [ ] Consolidate `build.sh` scripts in `data_for_tests/` (0.25d) @shreyamalviya

**Comment by shreyamalviya** [comment]
For `Plugin.__init__()`:

The ransomware payload currently requires `config`, `agent_event_queue`, and `agent_id` (along with other ransomware-specific parameters) in its constructor.

The payload plugin interface should pass have,

**Comment by shreyamalviya** [comment]
For `Plugin.__init__()`:

The ransomware payload constructor currently requires `config`, `agent_event_queue`, and `agent_id` (along with other ransomware-specific parameters) in its constructor.

The payload plugin constructor should have the name, `IAgentEventPublisher`, and `AgentID`.

**Comment by shreyamalviya** [comment]
For `Plugin.run()`:

The ransomware payload `run()` only accepts `interrupt`.

Payload plugins' `run()` functions should accept `options` and `interrupt`. OS compatibility will be checked in the puppet, so the plugin doesn't need to worry about it.

**Comment by shreyamalviya** [comment]
For `Plugin.run()` return value:

The ransomware payload `run()` always returns `None`.

Payload plugins' `run()` functions may return `PayloadResultData`, similar to what we have for exploiters. This would be used in the case where a payload couldn't run due to an unexpected error. A log and event would be published with that message.
