### ISSUE TITLE
Migrate the ransomware payload to a plugin

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3391]
## Description

Replace the hard-coded ransomware payload with a new and improved, fully tested, payload plugin.

## Tasks
- [x] Create plugin skeleton (0d) @shreyamalviya @mssalvatore 
    - [x] options (pydantic)
         - [x] determine what options ransomware should have
         - [x] create a pydantic model for ransomware options
    - [x] Create plugin manifest
    - [x] Create config schema
- [x] migrate the ransomware payload to a plugin (plugin.py) (0d) @mssalvatore 
- [x] Add a jenkins job to build the plugin (0d) @mssalvatore 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the ransomware plugin build job
- [x] Remove the hard-coded ransomware plugin (0d) @mssalvatore 
    - [ ] ~Update ETE test configurations~
    - [x] UI
    - [x] Island
    - [x] Agent
- [x] Final testing (0d)
    - [x] Linux
    - [x] Windows
- [x] Remove vulture entries
    - [x] Remove `PayloadPluginFactory`
    - [x] Remove `PayloadResultData`
