### ISSUE TITLE
gzip plugins' `source.tar`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3392]
## Description

Some plugins are on the order of 10's of megabytes. Infection Monkey's performance may be suboptimal on networks with low throughput, as large plugins could take a while to download. It could also lead to longer setup times when plugins are moved to a repository and downloaded to the Island after installation (instead of packaged with the Island). gzipping the plugins' `source.tar` file will lead to faster network transfers.

## Tasks
- [x] Modify the plugin build script to gzip the `source.tar` files (0d) @mssalvatore 
- [ ] Modify the agent's `PluginSourceExtractor` to expect a gzipped `source.tar` (0.25d) @mssalvatore 
- [x] Rebuild all plugins (0d) @mssalvatore
