### ISSUE TITLE
Filter events by timestamp

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3397]
## Description

Add the ability to filter events by timestamp. Queries should look like:
"/api/agent-events?timestamp=gt:1685640405"

Implement the following operators:

- gt
- lt

## Note
The current filtering approach is a simple solution that covers many, but not all use cases. Consider switching to GraphQL for advanced searching instead of using one of many poorly-defined "REST" approaches.

## Tasks
- [ ] Modify the `IAgentEventRepository` to guaranteed events are returned in order of timestamp ascending (0.5d) - @shreyamalviya 
    - [x] Modify the `MongoAgentEventRepository` to fulfill the new guarantee.
- [ ] Add the capability to filter events by timestamp (use python's `bisect()`) (0.5d) - @shreyamalviya
