### ISSUE TITLE
Remove Island modes

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3400]
## Description

The different modes (custom, ransomware) that can be selected when the Island starts may or may not be available once payloads are transformed into plugins (#3390, #3391). Furthermore, there really isn't any material difference between the two modes at the present time.

Remove "modes" from the Island.

This will be replaced at a later date by "scenarios". 

## Tasks

- [x] Remove mode-related endpoints (0d) - @shreyamalviya 
    - [x] Remove mode setting from BB tests
- [ ] Remove mode dependencies from any services/repositories/models/event-handlers (0.25d) - @shreyamalviya 
    - [x] Remove unnecessary ransomware default configuration and accompanying logic (0d) - @shreyamalviya     
- [x] Remove mode-related logic and components from the UI (0d) - @shreyamalviya 
- [ ] Close #2583 
- [x] Remove "Scenarios" from the documentation (0d)
