### ISSUE TITLE
Create agent plugin repository buckets and lambda

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3412]
## Context

Agent plugins will be stored in a repository and made available to the Island at runtime. See https://guardicore.atlassian.net/wiki/spaces/RES/pages/4281794663/Agent+Plugin+Repository for more context, as well as design and implementation details.

## Description

An AWS Lambda function that is triggered by an upload/overwrite of a \*.tar file to any of the S3 repository buckets will extract the plugin's manifest file and update the repository's index.yaml file (req 1.1).

The Lambda function must be configured to use "reserved concurrency" to avoid race conditions that would otherwise lead to an incorrect or incomplete index file. The number of concurrent Lambda jobs must be limited to 1.

## Warning
Since the lambda function is triggered on file upload and it will upload a new index.yaml to the repository bucket, special care must be taken to avoid recursive invocation. The lambda should only be triggered on the upload of \*.tar files. In addition to adding a check in the lambda's code, this can (and should) be configured in the trigger itself.

## A note on object locking
While object locking will prevent plugins from being overwritten, the lambda code should reject requests to  modify/overwrite plugins in release repositories.

## Tasks
- [x] Create an S3 bucket for the development repository. (0d)
     - [x] Add an `index.yaml` with no plugins in it
- [x] Create an S3 bucket for the v2.3.0 release repository. (0d)
    - [x] Add an `index.yaml` with no plugins in it
- [x] Create the lambda trigger (0d) - @VakarisZ 
    - [x] Create a placeholder, noop lambda in AWS
    - [x] Trigger the lambda by S3 upload of `.tar` files (watch out for recursive invocation)
    - [x] Use "Reserved concurrency" to ensure only one copy of the lambda is running at any given time
- [x] Implement the lambda: (0d) - @VakarisZ @cakekoa  
    - [x] Extract a plugin and read its manifest
    - [x] Read the repository's index.yaml and update it
    - [x] Add checks to skip/ignore any files that are not `.tar`
    - [x] If the bucket isn't the development bucket, reject all updates to existing plugins (security). Note: This is being done via object locking
        - [x] Prove that v2.3.0 plugins are not overwritable
    - [x] Audit the read/write policy to ensure this is secure
    - [x] Add staging bucket (0)
    - [x] Implement staging bucket processing logic (0)
    - [x] Update lambda policies (staging bucket left only) (0)
