### ISSUE TITLE
Update plugin jenkins jobs to upload plugins to development or release repositories

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3414]
## Description

Update the Jenkins build jobs for plugins to upload completed plugins to the appropriate repository.

## Tasks
- [x] Add a way to distinguish between release and development plugins (repository name field?) (0d) - @VakarisZ @mssalvatore 
  - [x] Add release version text field
  - [x] Add checkbox for whether or not to upload
- [x] Upload plugins to the correct location in the staging bucket (0d) - @VakarisZ
