### ISSUE TITLE
Consolidate the AgentPluginService

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3415]
# Refactor

## Component(s) to be refactored

- IAgentPluginRepository
- FileAgentPluginRepository
- PluginArchiveParser
- AgentPluginRepository*Decorator
- monkey_island.cc.resources/agent_plugin.py
- monkey_island.cc.resources/agent_plugin_manifest.py

## Explanation
Consolidate the above components into an `AgentPluginService`. Follow the examples set by `AgentConfigurationService` and `AgentBinaryService`

## Tasks
- [x] Define `IAgentPluginService` (thin wrapper round `IAgentPluginRepository)` (0d) - @shreyamalviya 
- [x] Implement `IAgentPluginService` (0d) - @shreyamalviya 
- [x] Move the `agent_plugin.py` and `agent_plugin_manifest.py` resource into the `agent_plugin_service` (0d) - @shreyamalviya 
- [x] Migrate components that will remain external to `monkey_island.cc.services.agent_plugin_service` to use the new `IAgentPluginService` (0d) @cakekoa
- [x] Migrate the `IAgentPluginRepository`, its implementations, its decorators, and required utilities into `agent_plugin_service`(0d) @cakekoa
