### ISSUE TITLE
Implement `MongoAgentPluginRepository`

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3416]
## Description

The `FileAgentPluginRepository` has outlived its usefulness. It is not capable of supporting repeated querying of certain plugin components in a performant way. This component should be replaced with a new `MongoAgentPluginRepository`. Note that most (all?) of the unit tests for `FileAgentPluginRepository` may be easily repurposed to test the new repository, since both repositories will share the same interface.

The new repository should store `AgentPlugin` objects as documents in MongoDB.

## Note

Unlike the current repository which will load the plugins from files and parse linux/windows-specific plugins from the plugin package, this repository will not need to do any parsing at retrieval time. Rather, this parsing should be done when the plugins are stored.

## Tasks
- [x] Implement `MongoAgentPluginRepository` from `IAgentPluginRepository` (0d) @cakekoa 
  - [x] Figure out the implications of storing binary data in mongo
  - [x] store_agent_plugin
  - [x] remove_agent_plugin
  - [x] get_plugin
  - [x] get_all_plugin_configuration_schemas
  - [x] get_all_plugin_manifests
- [x] Build the `AgentPluginService` with the mongo repository, instead of the file-based repository  (Do not use the caching decorator) (0d) - @shreyamalviya 
- [x] Remove disused code (0d) - @shreyamalviya 
  - [x] Remove the disused file-based repository
  - [x] Remove the disused caching decorator
- [ ] Update server setup to install (`IAgentPluginSevice.install_agent_plugin`) all plugins (0d) - @shreyamalviya 
  - [x] Use the data_dir convention (data_dir / PLUGIN_DIR_NAME)

**Comment by mssalvatore** [comment]
See https://pymongo.readthedocs.io/en/stable/examples/gridfs.html
