### ISSUE TITLE
Agent plugin upload API endpoint

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3417]
## Description

Add an API endpoint that allows a user to upload an agent plugins (**content-type application/octet-stream**): `PUT /api/agent-plugins`

## Tasks
- [x] Add `store_agent_plugin(self, host_operating_system: OperatingSystem, agent_plugin: AgentPlugin)` to `IAgentPluginRepository` (0d) @ilija-lazoroski 
   - [x] Remove anything from the vulture ignore list relating to the plugin parser
   - [x] Add a stub implementation in `FileAgentPluginRepository`
- [x] Add `remove_agent_plugin(self, host_operating_system: Optional[OperatingSystem], agent_plugin_name: str, agent_plugin_type: AgentPluginType)` (0d) @ilija-lazoroski 
  - [x] This should be idempotent
  - [x] If host_operating_system is None, delete plugin for all operating systems (add to docstring)
  - [x] Add a stub implementation in `FileAgentPluginRepository`
- [x] Add `install_agent_plugin_archive(self, agent_plugin_archive: bytes)` to `IAgentPluginService` and implement it in `AgentPluginService` (0d) @ilija-lazoroski 
   - [x] Unpack/parse the archive into an AgentPlugin (plugin_archive_parser.parse_plugin)
   - [x] Call IAgentPluginRepository.remove_agent_plugin() to remove the plugin for all operating systems
   - [x] Call IAgentPluginRepository.store_agent_plugin() for each host operating system supported by the plugin
   - [x] Make this method thread-safe
- [ ] Add a new endpoint with `PUT /api/agent-plugins` (0.25d) @ilija-lazoroski
