### ISSUE TITLE
Plugin installation screen

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3418]
## Description

As a user, I want to understand what Agent plugins are installed and what plugins are available, so that I can install/uninstall Agent plugins at will and customize my adversary emulation experience.

## Desired features

- View plugins that are available from the plugin repository
- View plugins that are already installed
- Install missing plugins from the repository
- ~Select the specific version of the missing plugin to be installed~
- Uninstall installed plugins
- Upload a plugin file
- Highlight an installed plugin if a newer version is available from the repository
- Force the UI to query the repository and refresh itself with the latest data

## Mockup
![image](https://github.com/guardicore/monkey/assets/19957806/f94a84e2-97bf-45bd-9ef2-240e7da5132c)

## Tasks
- [x] Create new plugins page with tabs (0d) @cakekoa 
- [x] Create plugins context (0d) @cakekoa 
- [x] Available plugins page @cakekoa 
    - [x] API requests (0d)
        - [x] Get available plugin list
        - [x] Get installed plugin list
        - [x] Install plugin
    - [x] Grid
        - [x] Action button (install) logic (API call) (0d) @cakekoa 
        - [x] Filtering logic (0d) - @VakarisZ 
    - [x] Implement refresh plugins refresh button (0d) @cakekoa 
- [x] Installed plugins page (0.25d)
    - [x] Available updates indicator (0d) @cakekoa 
    - [x] API requests (0d)
        - [x] Install/upgrade plugin
        - [x] Uninstall plugin
    - [x] Grid 
        - [x] Action buttons (upgrade/uninstall) logic (0d)
        - [x] Filtering logic (0d)
- [x] Search bar component (0d) @ordabach 
- [x] Plugin type dropdown filter component (0d) - @VakarisZ 
- [x] up-to-date vs. upgradable toggle (0d) @ordabach 
- [x] Tooltip component (0d) @ordabach 
- [x] Install all safe button (0d) @cakekoa 
- [x] Change the 'no rows' message in the grid to 'connection unavailable' when a request to the server is failed (0d) @ordabach 
    - Read in the MUI docs how to pass props into a custom slot of the data grid ([link](https://mui.com/x/api/data-grid/data-grid/#DataGrid-prop-slotProps))
- [ ] Improvements (0.25d)
    - [x] Add a column for safe/unsafe to plugin grid @ilija-lazoroski #3643 
    - [x] Populate "Author" field - @VakarisZ 
    - [x] Only search on displayed properties @cakekoa #3646
    - [x] Feedback for user actions (successful instalation/removal of a plugin), example below @cakekoa #3644 
    - [ ] ~~??? Better description of a plugin. User will likely want to read more about the plugin before downloading it. The small text with unclickable links in the tooltip is not great for this ( Try to use Collapsible component as in https://mui.com/material-ui/react-table/#collapsible-table). [Table is completely different component. To implement such thing in the data grid we need to override the "row" slot https://mui.com/x/api/data-grid/data-grid/#DataGrid-slots-null]~~
    - [x] Remove the "Search" title from searchbar. The icon already indicates that this is a search input - @shreyamalviya #3648 
    - [x] Make plugin table full-height @cakekoa #3645
    - [x] Add "Type" title and default value of "All" to the type filter. Right now it's doing a placeholder approach, which is worse
    - [x] Fix type column to display human readable values instead of using the underscore (now displays "Credential_Collector") - @shreyamalviya #3649
    - [x] Fix styling of the refresh button, make it spin to indicate to the user that something is actually happening once you click on it @ilija-lazoroski #3650 
    - [x] Add a loading icon for update/delete button @ilija-lazoroski 
    - [x] Refactor to use `IslandHTTPClient` - @shreyamalviya #3658 

### Example of feedback for successful actions

![downloaded_plugin_stays_ex](https://github.com/guardicore/monkey/assets/36815064/4b29c015-c1ee-4aec-8125-80927cfdb2e3)

![terminating_example](https://github.com/guardicore/monkey/assets/36815064/2e76e928-2b47-4ec4-8be3-07fe66090b58)

**Comment by ordabach** [comment]
I'm wondering if now it's the right time for this task, or make it once we have a more well-built UI.

**Comment by mssalvatore** [comment]
> I'm wondering if now it's the right time for this task, or make it once we have a more well-built UI.

That would be ideal, however, rebuilding the UI is a large project we haven't even started yet. In between now and when it's finished, users have no way to install and uninstall plugins.

**Comment by VakarisZ** [comment]
What's prohibiting us from implementing this in a way that rebuilt UI would be able to use this?

**Comment by ordabach** [comment]
> What's prohibiting us from implementing this in a way that rebuilt UI would be able to use this?

We've agreed on implementing it.

**Comment by cakekoa** [comment]
Since this has three tabs, we could do this in three parallel tasks

**Comment by cakekoa** [comment]
Should we just use [Quick Filter](https://mui.com/x/react-data-grid/filtering/quick-filter/) for all filtering?
