### ISSUE TITLE
Available plugins endpoint

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3420]
## Descriptions

Users will need to know what plugins are available so that they can choose which plugins to install. Add `GET /api/agent-plugins/repositories`, `GET /api/agent-plugin/repositories/<string:repository_url>` that allows users to query available plugins. This should return information about:

1. The source of the plugins (Repository)
2. Any information the user needs to make a decision (name, plugin type, description, version, safety, etc).

The endpoint should also accept a query parameter such as "?force_refresh=true" so that the user can instruct the Island to pull a fresh index file from the repository. This will ensure the user has the most up to date information.

## Tasks
- [x] Add a method to the AgentPluginService that allows the endpoint to query the plugin repository (s3 bucket) (0.75d) @ilija-lazoroski 
  - [x] Use hard-coded develop bucket URL for the repository
  - [x] Query the bucket, return the AgentPluginRepsitoryIndex
  - [x] Return the cached result, unless the force_refresh parameter is True or the data is older than some interval (1h?)
- [x] Add an endpoint (0d) - @shreyamalviya 
- [x] Add "force_refresh" parameter to the endpoint (0d) - @shreyamalviya
