### ISSUE TITLE
Agent plugin installation endpoint

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3421]
## Description
Add an API endpoint that allows a user to instruct the Island to install an agent plugin from the agent plugin repository (**content-type application/json**): `PUT /api/agent-plugins`.

The JSON document sent in the PUT should include, at a minimum:
1. ~The repository to install the plugin from (Download URL/path?)~
2. The plugin name, type, and version to install

## Security
The endpoint should not attempt to download the plugin from any repository specified by the user. The repository specified by the user must be validated against known/configured repositories.

## Notes
This endpoint may already exist for file upload (issue #3417). The PUT method and the URL are identical, but the content type  indicates file upload or repository fetch.

This endpoint should be idempotent.

## Tasks
- [ ] Add a method to `AgentPluginService` that can install a plugin from a repository - @shreyamalviya 
  - [x] Download the plugin (lookup the plugin in the AgentPluginRepositoryIndex)
  - [x] Install (call AgentPluginService. install_agent_plugin_archive())
- [ ] Implement `PUT /api/agent-plugins` for application/json content-type - @ilija-lazoroski 
- [ ] Add security checks
