### ISSUE TITLE
Agent plugin uninstall endpoint

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3422]
## Description
Add an API endpoint that allows a user to instruct the Island to uninstall an agent plugin from the Island: `DELETE /api/agent-plugins/<string:plugin_type>/<string:name>`.

## Tasks
- [x] ~Add a method to the `IAgentPluginRepository` that allows plugins to be removed~ done in #3417
- [ ] Add a method to the `AgentPluginService` that allows plugins to be uninstalled (0.25d) @ilija-lazoroski 
    - [x] Method should not accept operating system as a parameter
    - [x] Remove plugin from the repository
    - [ ] ~Unload any custom events~ moved to #2967
- [ ] Add DELETE verb to the `AgentPlugins` endpoint that calls `AgentPluginService.uninstall_agent_plugin(plugin_name: str, plugin_type: AgentPluginType)` (0.25d)
   - [x] We may want to create a new endpoint for this
