### ISSUE TITLE
Implement an RDP exploiter

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3425]
## Description

Implement an exploiter that uses RDP to propagate to Windows hosts.

Related: #3376, #3488

## Tasks

- [x] Add vulnerable 2 machines to terraform/GCP (0d) @ilija-lazoroski 
    - [x] Password authentication
    - [x] PTH
    - [x] Test depth
- [x] options (pydantic) @cakekoa 
    - [x] determine what options RDP should have (0d)
    - [x] create a pydantic model for RDP options (0d)
    - [x] create a config schema (0d)
- [x] Create plugin manifest (0d) @cakekoa 
- [x] Create a Pipfile for dependencies (0d) @cakekoa 
- [x] plugin.py (0d) @cakekoa 
- [x] command builder (0d) @cakekoa 
- [x] exploit client (0d) @ilija-lazoroski 
    - [x] Don't forget to add MITRE tags
    - [x] Copy agent binary do Desktop if that avoids administrator privilege dialogues.
- [x] Domain specification logic (0d)
- [x] Make RDP64->65 propagation use PTH (0d)
- [x] Add a jenkins job to build the plugin (0d) @ilija-lazoroski 
    - [x] Update the island build jobs on Jenkins to copy the artifacts from the RDP plugin build job @cakekoa 
- [x] Update ETE test configurations (add to depth 2) (0d)
    - [x] Test
    - [x] Fix the RDP machine hostnames in the ansible scripts
    - [x] Investigate Credentials pair issue from UI
- [x] Document the new exploiter (0d)
