### ISSUE TITLE
Steal credentials from Chrome

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3426]
## Description

Write a credentials collector that steals credentials from chrome-based browsers.

See #3398 for research.

## Tasks
- [x] Define config-schema.json, manifest, and options (0d) @ilija-lazoroski 
- [x] Create pipfile for dependencies (0d) @ilija-lazoroski 
- [x] Add A jenkins job to build the plugin (0d) - @shreyamalviya 
- [x] Define a strategy class that accepts a "credentials file selector" and a "credentials file processor" (0) @ilija-lazoroski, @shreyamalviya 
- [x] Write the credentials file selector (and processor?) for Windows for Chrome, Edge (0.75d)
    - [x] WindowsCredentialsDatabaseSelector - @shreyamalviya 
    - [x] WindowsCredentialsDatabaseProcessor - @shreyamalviya 
- [x] Write the credentials file selector (and processor?) for Linux for Chrome, Chromium (0.75d) - @ilija-lazoroski 
- [ ] ~Install `libglib2.0-dev`, `libdbus-1-3`, and `libdbus-1-dev` on Linux build machine in GCP (`dbus-python` on Linux requires these)~
- [x] Add machines to GCP for testing (or modify existing machines) 
    - [x] Windows (0.75d) - @VakarisZ 
    - [x] Linux (0.75d)
- [x] Add a BB test for testing this credentials collector (0.5d) - @shreyamalviya 
- [x] Document the new feature (0.25d) - @shreyamalviya
- [x] Reduce duplicated code
  - [x] consolidate windows, linux database readers
  - [x] consolidate the decrypt_v80 function
- [x] Add changelog entry

**Comment by ilija-lazoroski** [comment]
Because we use `dbus-python` for stealing credentials from chrome-based browsers on Linux we will need to install `libglib2.0-dev`,  `libdbus-1-3` and `libdbus-1-dev`

**Comment by cakekoa** [comment]
> Because we use `dbus-python` for stealing credentials from chrome-based browsers on Linux we will need to install `libglib2.0-dev`, `libdbus-1-3` and `libdbus-1-dev`

Do we need a task for updating our `agent-builder` image? It doesn't seem to be able to build the plugin
