### ISSUE TITLE
Packer leaves powershell remoting enabled

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3583]
**Is your feature request related to a problem? Please describe.**
Packer runs WINRM and uses powershell remoting ports to do its job. This means that we need to find workarounds to block powershell remoting with GCP firewall rules, but packer images should be independent of cloud environment.

**Describe the solution you'd like**
[Use a cleanup script to disable PowerShell remoting.](https://hodgkins.io/best-practices-with-packer-and-windows#disable-winrm-on-build-completion-and-only-enable-it-on-first-boot)

## Tasks

- [x] Merge #3925 @ilija-lazoroski 
- [x] Rebuild mimikatz-15 image @ilija-lazoroski 
- [x] Add packer script for mimikatz-14 that disables powershell remoting @ilija-lazoroski 
    - [x] It needs to have mimikatz-15 cached credentials, everything else is same as mimikatz-15 
- [x] Disable powershell remoting on all RDP machines in depth_2
    - [ ] Rebuild all RDP machines
- [x] Disable PowerShell Remoting on other machines that doesn't need it.  
- [ ] Disable RDP on  machines hadoop-3, log4j-50, log4j-52, log4j-56  and mssql-16 in depth_1

**Comment by cakekoa** [comment]
Similarly, RDP is also enabled on most if not all Windows machines. That means most if not all of them are exploitable via RDP. We could probably disable RDP on a per-user basis, so that it is closed to the accounts used in EtE tests, but open to developer accounts
