### ISSUE TITLE
Improve credential input UX

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3606]
**Is your feature request related to a problem? Please describe.**
Credentials input UX should be improved

**Describe the solution you'd like**
I suggest 3 changes to improve UX, but these are to be discussed. 
![image](https://github.com/guardicore/monkey/assets/36815064/f78c3dbf-6e71-47b3-a26d-961d12ee8a44)

1. Fix the title. The title should be **bold**, it should say "Credentials" and mouse pointer style should be "default", not "pointer". This change is required, because right now title looks like a poorly made button.
2. Plus button should add a row instead of actually saving the credentials. If it saves the credentials, it should have a save icon, not a + icon.
3. There's no need for a separate table of "saved" credentials. Credentials table should be a table of inputs. This saves clicks, since it allows editing without extra clicks, once you input you don't need to explicitly "save" your input, it should get saved on submit. If this is too much work, we should at least make it clear, that there are two fields, one is an input field and another is a display field for credentials.

## Tasks
- [x] Change the + button to "save" (0d) @ilija-lazoroski 
- [ ] Move the +/save  button to the bottom left under the row (0.25d) @ilija-lazoroski 
- [x] Change the title to not look like a button (0d) @ilija-lazoroski
