### ISSUE TITLE
Upload binary plugin UI

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3611]
## Description

Add the ability for a user to install a plugin archive in the UI.

## Tasks
- [x] Upload plugin page @ilija-lazoroski 
    - [x] Drag and drop zone component (0d)
    - [x] Implement upload logic (0d)
