### ISSUE TITLE
Integrate plugin installation UI

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3612]
## Description
Integrate the plugin installation UI into the rest of the platform

## Tasks
- [x] Document plugin installation (0d) 
- [x] Link/button/component on the main screen/nav bar (0d)
- [x] Modify advanced multiselect to provide a link to plugin installation if it's empty (0d) @shreyamalviya 
- [x] Sidebar available updates indicator (0d)
- [x] Update available vs installed state hourly (0.5d)
