### ISSUE TITLE
Download plugins from repositories

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3616]
## Description

The Island should download plugins from the plugin repository instead of including them in the Island package.

## Tasks

- [x] Add logic to detect whether or not the Island is a development or release version. Use the development repository if a development version, or the hardcoded release repository if it's not a dev version. Log which repository is being used to make testing simple. - @shreyamalviya 
- [x] Modify the jenkins Island build jobs to no longer include the plugins - @shreyamalviya 
- [x] Modify BB tests to install the latest version of each available plugins - @shreyamalviya
