### ISSUE TITLE
AgentPluginMetadata naming consistency

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3635]
## Description

Rename AgentPluginMetadata's fields to be consistent with AgentPluginManifest.

1. Rename name -> plugin_name
2. Rename type_ -> plugin_type

## Tasks
- [x] Fix the AgentPluginMetadata object in common (0d) - @shreyamalviya 
- [x] Copy the changes to the lambda (and monkey-build repo) (0d) - @shreyamalviya 
- [x] Rebuild the develop repository (0d) - @shreyamalviya 
- [x] Fix the plugin installation UI (0d) - @shreyamalviya
