### ISSUE TITLE
Upgrade to Node.js 20

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3711]
## Description

Node.js 16 is EOL as of 2023-09-11. Upgrade to Node.js 20 (latest version).

## Side efficts

Node.js 20 is not available on Ubuntu Bionic 18.04. We must upgrade our build system to Ubuntu Jammy 22.04 or Focal 20.04. This means that the Island AppImage may not be runable on certain other distributions. Use distrowatch.com to compare glibc versions and make a decision about which Ubuntu we should upgrade to.

In addition, the base container for our Island Docker image may need to be upgraded.

## Note

The current method of installing Node.js in the Linux deployment script is deprecated.
![image](https://github.com/guardicore/monkey/assets/19957806/ec70457f-68dd-427f-987d-9d2e6f5a7da0)

## Tasks

- [x] Choose a new version of Ubuntu for our build system
  - Ubuntu 20.04 is the minimum version supporting glibc 2.28+
  - All our previous supported OSs for Island should still work, with the exception of Ubuntu 18.04
- [x] Take a snapshot of the build instance
- [x] Upgrade the build instance to 20.04+
- [x] Upgrade node.js to v20
    - [x] Fix deployment scripts and get this running from source
    - [x] Upgrade node.js to v20 on the Windows build node
    - [x] Upgrade the linux island instances
    - [x] Test and fix the Docker build
    - [x] Test and fix the AppImage build
    - [x] Test and fix the MSI build

**Comment by cakekoa** [comment]
Steps taken:

    - Update NodeJS on the Windows build node
        - Simply download and install the new version
    - Update deployment scripts
    - Determine if a new glibc version is required. This was accomplished by first updating the build scripts, then attempting AppImage and Docker builds on the build machine, which resulted in a glibc warning message. There must be a better way
    - Determine what base images will work with the glibc version. AppImage is based off of the manylinux docker image, so one can check that for it’s supported glibc version. Docker is based off of a python base image, so that is what to check.
    - Check distrowatch and see if the supported OS versions need to change, based on the glibc version
    - Update the linux build scripts with the new version of NodeJS
    - Update the linux build scripts to use the correct AppImage and Docker base images
    - Update the linux build node if necessary
        - Save a snapshot
        - Have IT make the upgrade
    - Determine if npm packages need to be updated
        - Determine if any updates need to be made to the UI
    - Build the islands with the new NodeJS version
        - Test
    - Update the linux island machines, if necessary (it was)
        - Test
    - Run BB tests
