### ISSUE TITLE
Pass Agent OTP environment variable to plugins

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3741]
## Description
Currently, `AGENT_OTP_ENVIRONMENT_VARIABLE` is imported from `common.common_consts` in all plugins that require it. Instead, pass the value to each plugin's constructor. This is useful because:
1. Plugins depend on `common/common_consts/` for `AGENT_OTP_ENVIRONMENT_VARIABLE` and timeouts. This helps break that dependency, hence supporting #3725.
1. It's easier to change the Agent. Nothing in plugins needs to change if we change the environment variable in the Agent.

## Tasks
- [x] Modify `ExploiterPluginFactory.__init__()` to accept the environment variable argument and pass it to plugins when constructing them in `ExploiterPluginFactory.create()`. (0d)
- [x] Construct `ExploiterPluginFactory` with the environment variable argument in `monkey.py`. (0d)
- [x] Modify command builders to accept the argument and use it. (0d)
- [x] In exploiters that directly use `AGENT_OTP_ENVIRONMENT_VARIABLE`, remove the import, accept the environment variable argument in their `Plugin.__init__()`, and pass it to their command builder.
    - [x] Hadoop (0d)
    - [x] Log4Shell (0d)
    - [x] MSSQL (0d)
    - [x] PowerShell (0d)
    - [x] RDP (0d)
    - [x] SMB (0d)
    - [x] SNMP (0d)
    - [x] SSH (0d)
    - [x] WMI (0d)
- [x] Rebuild plugins and make sure EtE tests pass. (0d)
