### ISSUE TITLE
Add timeout options to plugins

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3742]
## Description
As of now, plugins import and use timeout constants from `common/`, but there's no reason for plugins to have the same timeouts. Each plugin runs and functions independently, and should therefore have its own timeouts.

This also helps break the dependency between plugins and `common/common_consts/timeouts`, hence supporting #3725.

## Tasks
- [ ] Remove the dependency for each plugin that imports from `common.common_consts.timeouts` by adding a new configuration option for each timeout (or hard-coding it?).
    - [ ] Log4Shell exploiter
        - [ ] Service exploiters' POST request timeout
        - [ ] `LDAPExploitServer.stop()` timeout
        - [ ] Server shutdown timeout (`SERVER_SHUTDOWN_TIMEOUT` in `log4shell_exploiter.py`)
    - [ ] SSH exploiter
        - [ ] `SSH_AUTH_TIMEOUT`
        - [ ] `SSH_BANNER_TIMEOUT`
        - [ ] `SSH_CHANNEL_TIMEOUT`
        - [ ] `SSH_EXEC_TIMEOUT`
    - [ ] Zerologon exploiter
        - [ ] RPC connection timeout (in `dc_utils.py`)
        - [ ] IP name query timeout (in `dc_utils.py`)
        - [ ] SMB connection timeout (in `dump_secrets.py`)
        - [ ] SMB connection timeout (in `wmiexec.py`)
    - [ ] Cryptojacker payload
        - [ ] Bitcoin mining POST request timeout
- [ ] Rebuild plugins and make sure EtE tests pass.

**Comment by mssalvatore** [comment]
I don't think these timeouts need to be configurable. At the present time, I see now reason to burden the user with such low-level options. Each plugin could define its own constants with relevant names. For example, instead of using "MEDIUM_REQUEST_TIMEOUT" (whose name really means nothing), Log4Shell could internally define a constant named "POST_REQUEST_TIMEOUT".
