### ISSUE TITLE
Pass host machine information to plugins

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#3751]
## Description

To run, some plugins require information about the host machine i.e. the machine on which they're running.
1. The Log4Shell exploiter needs information about (1) host machine interfaces that the victim machine can connect to (for starting HTTP and LDAP servers), and (2) a directory path on the host machine to store temporary artifacts.
2. PowerShell and RDP exploiters need host OS information to generate credentials for brute-forcing.
3. Chrome credentials collector, cryptojacker payload, and ransomware payload run locally and hence require host OS information.

For now, these plugins access this information on their own when they require it (using `get_interface_to_target()` in `infection_monkey/network/tools.py`, `get_monkey_dir_path()` in `infection_monkey/utils/monkey_dir.py`, and `get_os()` in `common/utils/environment.py`). This, however, generates a dependency (standing in the way of #3725). It is also not a plugin's responsibility to get information about the machine on which it is running. Plugins should simply be given instructions and all the data they need to run.

To fix these issues, create a structure (`AgentHostMachineInfo`?) that is passed to all plugins that contains all information that plugins may need about the host machine so they can run.

## Tasks
- [x] Define the model (think of a more descriptive name than `AgentHostMachineInfo`) (0d)
- [x] Modify the puppet to build the object and pass it to all plugins' `run()`. Note that the object depends on the victim host for exploiters. For the rest of the plugins, only the OS is needed (at the time of writing this). (0d)
- [ ] Modify all relevant plugins to accept this object and use it. Remove the dependency on `infection_monkey.network.tools` and `common.utils.environment`.
     - [x] Log4Shell exploiter (0.75d)
     - [x] PowerShell exploiter (0.25d)
     - [x] RDP exploiter (0.25d)
     - [x] Chrome credentials collector (0.25d)
     - [x] Cryptojacker payload (0.25d)
     - [x] Ransomware payload (0.25d)
- [ ] EtE and manual testing (0.5d)
