### ISSUE TITLE
Move HTTP Ports configuration option

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3769]
# Refactor

## Component(s) to be refactored

- HTTP Fingerprinter
- Config UI
- ExploitationOptionsConfig (remove)
- master.Propagator
- All exploiter plugins

## Explanation

The HTTP Ports option provided on the exploiter configuration page is a relic from before exploiters were plugins. This configuration option has no effect on exploiters and should be removed. Instead, the `HTTPFingerprinter` should allow the user to configure which ports to fingerprint.

## Tasks
- [x] Add hardcoded schemas for fingerprinters (all empty except HTTP FIngerprinter) - @shreyamalviya 
- [ ] Modify the configuration UI to display fingerprinters as plugins - @shreyamalviya 
- [x] Remove the `ExploitationOptionsConfiguration`, which only containes `http_ports` - @shreyamalviya 
    - [x] Remove the logic from `Propagator` that inserts http_ports into each exploiter's configuration
- [x] Ensure the master passes options to fingerprinters
- [x] Remove the logic to delete `http_ports` from options in all plugins - @shreyamalviya 
    - [x] hadoop
    - [x] log4shell
    - [x] mssql
    - [x] powershell
    - [x] rdp
    - [x] smb
    - [x] snmp
    - [x] ssh
    - [x] wmi 
    - [x] zerologon
    - [x] cryptojacker
    - [x] ransomware
- [ ] test

**Comment by ilija-lazoroski** [comment]
We decided to remove fingerprinters from the UI temporarily. We will add them as we rework the UI.
