### ISSUE TITLE
Refactor config generation from jsonschema

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3770]
# TBD
Things to be determined:
 - Do we want the users to be able to select UI components for configuration options? If so, we need to document our UI component library and allow users to add UI schema to the plugin. UI schema would be used to specify override the UI component at the specific path. This could also be done as a separate issue later.

# Refactor

Simplify code complexity for generating UI from jsonschema when refactoring the whole UI.

## Tasks

- [ ] Move jsonschema generation code to the back end (API gateway layer). This code is not in `monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js`
- [ ] Upgrade to the latest version of `rjsf`. See migration guide, keep in mind that the code is [not entirely migrated to react v18](https://github.com/rjsf-team/react-jsonschema-form/issues/3643)
- [ ] Remove the code that removes the defaults generated by rjsf (https://github.com/rjsf-team/react-jsonschema-form/issues/2980). This code is now in `monkey_island/cc/ui/src/components/configuration-components/UISchemaManipulators.tsx`
- [ ] (Optional) Create a facade for rjsf. This would make sure that we could exchange libraries or write our own without the need to change the interface
