### ISSUE TITLE
Deploy nextjs server

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3793]
# Description

We aim to use Next.js meta-framework. To utilize the full feature set Next.js offers we decided to run next.js server in production. This means we'll need to handle the server process, output and changes in the build.

# Tasks
- [x] Start/stop nextjs server with island startup/shutdown - @VakarisZ 
- [x] Configure nextjs logging to output to a file in the same directory as island logs - @VakarisZ 
- [x] Add configurable port - @VakarisZ 
- [x] Update the deployment scripts to install the node server @cakekoa 
- [ ] ~Duplicate the Island's jenkins jobs~
    - [ ] ~MSI~
    - [ ] ~AppImage~
    - [ ] ~Docker~
- [x] Edit duplicate jobs to use nextjs build commands and artifacts @cakekoa 
    - [x] MSI (need to update the MSI script in the build repo)
    - [x] AppImage (need to update build_scripts/common.sh in the monkey repo)
    - [x] Docker (same as appimage)
- [x] Smoke test the builds, make sure their size didn't increase dramatically
    - AppImage increased from 158 -> 199MB
    - Docker increased from 168 -> 208MB
- [x] Fix certificate configuration
- [x] Extend docs to explain where nextjs logs can be found
- [x] Extend the docs to explain how to configure the port
- [ ] Add ~development~ feature flag to not run the production during development OR configure dev script

**Comment by VakarisZ** [comment]
### Regarding the configurable port:
On linux non-root users can't open up a port below 1024.
The solution could be one of the following:
1. Keep the port 5000 as the default
2. Use 443. We'll need to throw an error message saying run the island as root OR run this command to allow port 443 for non-root users.
