### ISSUE TITLE
Barebones UI prototype

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3794]
# Description

Create a barebones UI prototype utilizing nextjs. This prototype will be a POC and will be used to alter build pipelines.

# Pre-requisite

If you take this task make sure to familiarize with #3678 

# Requirements

**Authentication** - use the same mechanism we currently use, don't use any libs. Fix up any obvious bugs if you want.
**Island communication** - UI needs to get a list of machines and be able to display a specific machine in a dynamic route. Page doesn't need too look good, the important part is to have a dynamic route that does real end-to-end communication.

Starting point for this feature should be code from [ui-prototypes branch](https://github.com/guardicore/monkey/tree/ui-prototypes). 

# Tasks

- [x] Implement registration - @VakarisZ 
- [x] Implement login - @VakarisZ 
- [x] Implement homepage that lists all machines - @VakarisZ 
- [x] Implement a dynamic route that provides information about specific machine based on its ID - @VakarisZ

**Comment by VakarisZ** [comment]
Prototype is in the [next-js-prototype](https://github.com/guardicore/monkey/tree/next-js-prototype) branch. It has state management, polling and dynamic routing, everything else is hacky and bare-bones
