### ISSUE TITLE
Remove unused bat and shell scripts

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3855]
# Refactor

## Component(s) to be refactored

`monkey_island/windows` and `monkey_island/linux` has a bunch of unused scripts. 

## Tasks

- [ ] Remove unused windows scripts
- [ ] Remove unused linux scripts
- [ ] Change the `monkey_island/readme.md` or remove it
