### ISSUE TITLE
Add Mirai simulation

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3876]
**Is your feature request related to a problem? Please describe.**
Simulate Mirai malware

**Describe the solution you'd like**
Monkey simulating the propagation methods Mirai uses

## Tasks

- [ ] Find a way to implement the behavior of Mirai and configure the IM to act like Mirai
    - [x] Create a script that can append wordlists into configuration and create a configuration file for Mirai
    - [ ] Create a test machine to assess what impact Mirai simulation will have on the IM and the victim machine
    - [ ] Make changes to the SSH plugin to make sure it can realistically simulate Mirai
- [ ] Document the way to run Mirai simulation
    - [ ] Create a page in the "Usage" section that describes how to configure the Mirai simulation
    - [ ] Upload configuration to S3 bucked and add a link to the documentation so users would be able to download it
- [ ] Release the new SSH plugin version
- [ ] Release the new documentation

**Comment by mssalvatore** [comment]
This whole thing might be as simple as producing a config for users to use. Hold off on this until @stiv-kupchik is back from his time off.

**Comment by ilija-lazoroski** [comment]
The machine created is `ssh-benchmark`. So far running the SSH exploiter that we have is 2293 set of credentials tried in 1h and 45m. 
![image](https://github.com/guardicore/monkey/assets/15820737/48a33323-e99c-4675-bfaa-a11a0a399df6)
