### ISSUE TITLE
Implement root UI template

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3897]
# Refactor

## Tasks

- [ ] Implement the navigation bar
    - [x] Change the navigation bar color scheme
    - [x] Implement empty pages for each button on a navigation bar

## Current proposal

![image](https://github.com/guardicore/monkey/assets/36815064/1e50b74e-1a32-4bb0-af30-426a299f8445)

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3133

**Comment by cakekoa** [comment]
- I vote we keep our original color scheme
- No more checkboxes to show monkey progress?
