### ISSUE TITLE
Remove legacy UI

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3898]
# Refactor

## Tasks

- [ ] Remove legacy UI codebase
- [ ] Change deployment/build scripts?
- [ ] Remove next.js feature flag
