### ISSUE TITLE
Finish up authentication

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3900]
# Refactor

### Tasks

- [ ] Agree upon new login/registration mocks
- [ ] Finish up login page
- [ ] Finish up registration page
- [ ] Implement/fix signout
- [ ] Finish up next-auth integration. Investigate if csrf tokens are properly sent, make sure that UI won't crash if we change token TTL, etc.
