### ISSUE TITLE
Add map page

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3901]
# Refactor

## Tasks

- [ ] Move the map component to the next.js
- [ ] Refactor node/edge generation and state management
- [ ] Add an end date to the exploit timeline to make sure long brute-force exploits still show some indication of progress

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/2519

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3221

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3148
