### ISSUE TITLE
Refactor configuration UI

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3919]
## Tasks

- [ ] Implement nested screens logic. Based on the current mockup clicking on exploiters would open up the exploiter screen, and then clicking on a specific exploiter would open up configuration settings for that specific exploiter. We need to handle the state management of passing child objects and propagating the state changes back to the parent (or global state)
    - [ ] Figure out and implement nested forms/screens state management
    - [ ] Implement different screens
        - [ ] Root configuration screen
        - [ ] Plugin selection screen
        - [ ] Plugin options screen
- [ ] Implement a breadcrumb component to navigate between the screens

**Comment by VakarisZ** [comment]
Related: #711

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/2598

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3147

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3752

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3704

**Comment by VakarisZ** [comment]
Related: #3703

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3489

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3853
