### ISSUE TITLE
Improve map readability

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3932]
## Tasks

Change the map in the following ways:

- [ ] When a map node is clicked, all edges and nodes not connected to it should fade out
- [ ] When a map node is clicked it should become highlighted to have a visual indication that it's the "active" element in the map.
- [ ] If an edge is clicked, the edge should become bald to indicate that it's the "active" element. All other map elements should fade out, except the edge itself and the nodes being connected by it. 

## Quick mockup

This mockup shows a view when `10.2.2.250/32` machine is selected/active

![image](https://github.com/guardicore/monkey/assets/36815064/906ac195-fc4d-49ca-893e-e0f436a11bd1)

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/2901

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/2627

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3721
