### ISSUE TITLE
Event timeline report

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3934]
**Is your feature request related to a problem? Please describe.**
There's no convenient way to investigate Infection Monkey's activity on the whole test network throughout time. 
There's no way to gauge simulation intensity on the network throughout time.

## Tasks

 - [ ] Find a graph library that can support dot graph. Example: https://observablehq.com/@d3/beeswarm/2?intent=fork
 - [ ] Use the library to plot events by time
 - [ ] Add zoom capability (maybe through choosing the timespan)
 - [ ] Make dot clickable. Upon getting clicked it should display basic information and have a button to link to more details.
 - [ ] Add filters
     - [ ] Event types filter
     - [ ] Source filter
     - [ ] Target filter
     - [ ] Tags filter

## Mock

As per @mssalvatore idea:

![image](https://github.com/guardicore/monkey/assets/36815064/8ca7938d-37cc-4c90-ace8-ca943b750179)
