### ISSUE TITLE
Implement event drilldown in the map

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3935]
**Is your feature request related to a problem? Please describe.**
Leverage the map page to enable a deeper understanding of what happened in a specific machine.

### Tasks

- [ ] Create an algorithm of grouping inbound events into chunks
- [ ] Implement a display component for inbound event chunk
- [ ] Display event chunks in the side panel 
- [ ] Implement inbound events chunk details view
- [ ] Implement a component for displaying agent activity brief in the side panel (probably the same component as event chunk)
- [ ] Implement agent activity details view

### Inbound traffic in the side pane
![image](https://github.com/guardicore/monkey/assets/36815064/afb9c311-eafe-4583-b0d5-d645b769fa69)

### Agent activity in the side pane
![image](https://github.com/guardicore/monkey/assets/36815064/fd09ebd0-c25b-4f7f-b4dd-87e736168e1c)

### Inbound activity details
![image](https://github.com/guardicore/monkey/assets/36815064/ff70d805-9968-4f9c-b214-5b0b1ac4c968)

### Agent activity details
![image](https://github.com/guardicore/monkey/assets/36815064/e58639cb-041d-406f-8c25-ae10b052b3be)

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/2718

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/3554
