### ISSUE TITLE
Add development flag

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3965]
**Is your feature request related to a problem? Please describe.**
We want different island behavior when we are developing than in production.

## Tasks

- [ ] Add development flag to the island cmd parameters
- [ ] Don't run next server on develop
- [ ] Token should have a longer TTL on develop
- [ ] OTP should be hard-coded on develop
