### ISSUE TITLE
Plugin selection screen

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#4013]
# Implement plugin selection screen

## Tasks

- [ ] Implement nested screen logic for plugins
- [ ] Implement breadcrumbs component
- [ ] Implement a selectable plugin card
- [ ] Implement mass select buttons
- [ ] Hook up plugin selection screens to plugin components / use them for all lists of objects

## Mockups

![image](https://github.com/guardicore/monkey/assets/36815064/0b89fc21-5ebd-49cf-8528-8e120e290005)
