### ISSUE TITLE
Reimplement configuration features

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#4014]
After configuration state refactoring and credential refactoring the configuration structure might've changed. This issue is meant to tie up any loose ends and make sure that configuration features work again.

## Tasks

- [ ] Fixup configuration export
- [ ] Fixup configuration import
- [ ] Test encryption
- [ ] Fixup configuration submit
- [ ] Fixup configuration reset
