### ISSUE TITLE
Refactor the `{build,get}_monkey_commandline{_linux,_windows,}()` debacle

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#4042]
# Refactor

## Component(s) to be refactored

- `{build,get}_monkey_commandline{_linux,_windows,}()`

## Explanation

There are too many functions with potentially unclear purposes used for building a command-line string for executing Agents. Furthermore, the responsibility of knowing how to build a command-line for executing Agents is shared among all components. Ideally, the Agent would be the only component that knows the specific details how it should be executed. We will attempt to refactor these methods to achieve this goal.

### Design note

The [builder pattern](https://refactoring.guru/design-patterns/builder) is likely a good way to implement this.

## Tasks

- [x] Analyze the existing functions and understand what they share in common, how these functions are used, and which, if any, should be "private".
- [ ] Define an interface that would allow plugins to generate agent command-line strings. It's goal is to insulate plugins from implementation-specific details that the Agent should be in charge of.
- [ ] Add the new interface to the [Agent plugin API](https://github.com/guardicode/agentpluginapi)
- [ ] Create a component that implements the interface in `common` (the Island will need to use this component).
- [ ] Modify the Agent to pass this component to exploiter plugins
- [ ] Modify each exploiter plugin to use the new interface
    - [ ] hadoop
    - [ ] log4shell
    - [ ] mssql
    - [ ] powershell
    - [ ] rdp
    - [ ] smb
    - [ ] snmp
    - [ ] ssh
    - [ ] wmi
    - [ ] zerologon
- [ ] Remove the now disused legacy functions
- [ ] Test thoroughly
