### ISSUE TITLE
Add light/dark mode

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#4049]
**Is your feature request related to a problem? Please describe.**
It would be nice for a user to be able to invert a theme and go from light-mode to dark-mode and vice-versa.

## Tasks

- [ ] Add assets for inverted theme (invert svg icon colours)
- [ ] Add theme selection switch button
- [ ] Add logic to load related assets based on theme selection
- [ ] Store theme selection in localstorage so that users don't have to toggle to their favorite theme every time they visit the website
