### ISSUE TITLE
Improve error page styles

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#4068]
# Refactor

We need to implement proper error pages in case the user encounters 500 or 404. 

## Tasks
- [ ] Style and improve 404 `monkey_island/cc/next_ui/src/app/not-found.tsx`
- [ ] Style and improve server error `monkey_island/cc/next_ui/src/app/error.tsx`
- [ ] Test the usages, make sure server error component is used properly
