### ISSUE TITLE
Add OpenSMTPD exploiter

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#4204]
**Is your feature request related to a problem? Please describe.**
[Remote code execution for OpenSMTPD](https://www.exploit-db.com/exploits/47984) can be incorporated into Infection Monkey

## Tasks

- [ ] Create OpenSMTP plugin (@VakarisZ)
- [ ] Add packer script to build vulnerable machine
- [ ] Change docs
- [ ] Change BB tests
