### ISSUE TITLE
ScoutSuite integration

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#519]
We'd like to use ScoutSuite to collect and present Cloud findings in our Zero Trust report. 

# PDR
## Problem statement
The problem currently is that we don't cover the Workloads and Orchestration pillars of Zero Trust and our report can generate more value to the users, especially enterprise ones.

The business value of this will be for the Enterprise cloud users and will be measured via download #s of this new version. 

### MH

* ScoutSuite findings show up in ZT report
* Minimal requirements added

### NTH

* Extra documentation/enrichment on ScoutSuite findings

### Out of scope

* Framework for integrating outside products (Infection Monkey as pen-testing framework)

## Reference materials

https://github.com/nccgroup/ScoutSuite

#### Functional requirements
Inputs: Collect Cloud info is configured. This will run ScoutSuite. The exact software boundaries between ScoutSuite and Infection Monkey will be discussed in the DDR including if and how to update our ScoutSuite fork. 
Outputs: Telemetry, how many checks were performed, how many resources were found.
Logs + error logs

#### Quality Requirements

The setup MUST BE very clearly defined and documented so users can use this feature by adding the relevant AWS role to their EC2 machines. THIS MIGHT BE INSECURE. 

#### Functional requirements

Inputs: Cloud data from Monkeys via telemetries. 
Outputs: Zero Trust Findings
Logs on telemetry parsing + errors

#### Quality Requirements

*Performance* must be unhindered with MANY findings. A 2000 findings report MUST be generated in under 7 seconds.

## Checklist: Requirements

The requirements checklist contains a list of questions to ask yourself about your project’s requirements.

Use the list as a sanity check at construction time to determine how solid the ground that you’re standing on is—where you are on the requirements Richter scale. Not all of the checklist questions will apply to your project. If you’re working on an informal project, you’ll find some that you don’t even need to think about. You’ll find others that you need to think about but don’t need to answer formally. If you’re working on a large, formal project, however, you may need to consider every one.

### Specific Functional Requirements

- [x] Are all the inputs to the system specified, including their source, accuracy, range of values, and frequency?
- [x] Are all the outputs from the system specified, including their destination, accuracy, range of values, frequency, and format?
- [x] Are all output formats specified for Web pages, reports, and so on?
- [x] Are all the external hardware and software interfaces specified?
- [x] Are all the external communication interfaces specified, including handshaking, error-checking, and communication protocols?
- [x] Are all the tasks the user wants to perform specified?
- [x] Is the data used in each task and the data resulting from each task specified? 

### Specific Nonfunctional (Quality) Requirements

- [x] Is the expected response time, from the user’s point of view, specified for all necessary operations?
- [x] Are other timing considerations specified, such as processing time, datatransfer rate, and system throughput?
- [x] Is the level of security specified?
- [x] Is the reliability specified, including the consequences of software failure, the vital information that needs to be protected from failure, and the strategy for error detection and recovery?
- [x] Are minimum machine memory and free disk space specified?
- [x] Is the maintainability of the system specified, including its ability to adapt to changes in specific functionality, changes in the operating environment, and changes in its interfaces with other software?
- [x] Is the definition of success included? Of failure?

### Requirements Quality

- [ ] Are the requirements written in the user’s language? Do the users think so?
- [x] Does each requirement avoid conflicts with other requirements?
- [x] Are acceptable tradeoffs between competing attributes specified—for example, between robustness and correctness?
- [x] Do the requirements avoid specifying the design?
- [x] Are the requirements at a fairly consistent level of detail? Should any requirement be specified in more detail? Should any requirement be specified in less detail?
- [x] Are the requirements clear enough to be turned over to an independent group for construction and still be understood? Do the developers think so?
- [x] Is each item relevant to the problem and its solution? Can each item be traced to its origin in the problem environment?
- [x] Is each requirement testable? Will it be possible for independent testing to determine whether each requirement has been satisfied?
- [x] Are all possible changes to the requirements specified, including the likelihood of each change? 

### Requirements Completeness

- [x] Where information isn’t available before development begins, are the areas of incompleteness specified?
- [x] Are the requirements complete in the sense that if the product satisfies every requirement, it will be acceptable?
- [x] Are you comfortable with all the requirements? Have you eliminated requirements that are impossible to implement and included just to appease your customer or your boss?

**Comment by ShayNehmad** [comment]
# DDR

TODO

**Comment by ShayNehmad** [comment]
DDR 1:
* Don't run all the tests - filter out interesting
* Finding per Cloud/Cloud service
* Display if any of the Monkeys were cloud (and which) - a single panel for both reports. 
* If there were no Monkeys on cloud X, don't display unexecuted tests from cloud X.
* We'll need to detect running in Azure.
* Check if scoutsuite works without super strong IAM role/if findings are different according to differing IAM permissions

**Comment by ShayNehmad** [comment]
# **WIP**

# ScoutSuite Exploratory Surgery for DDR

## Setup

I set up the following machines, and I'm debugging Directly from PyCharm using remote SSH shell:

* An AWS machine with Full Admin IAM role. i-05c3679394ad7c6d5
* An Azure machine with the Reader role b95047a4-b17a-4a39-8b03-901dc475c046

## Conclusions

### Installations

There are quite a lot of extra dependencies this bestows on the Monkey (mostly cloud stuff)).

### First execution - AWS

Went with AWS. Ran using Python 3.7 - `python3.7 scout.py aws`. This means we need to know ahead of time which provider we are planning to scan and pass the parameter accordingly.

Started debugging.

The main mechanism seems to be an asyncio event loop which uses a ThreadPool - they already thought about MultiThreading. Need to make sure I can run this async myself. I didn't debug the internals by accident, so let's start with analyzing the results (and the results FILE) for now and approach the internals + interesting parameters later.

#### Results analysis

##### Interesting categories

The "baseline" will be AWS (Azure equivilant will be provided later).

###### For sure

We'll have 4 categories:

* **Compute** - EC2 | Virtual machines
* **Identity** - IAM | Azure Active Directory
* **Storage** - S3 | Azure Blob Storage
* **Networking** - VPC | Virtual Network

###### Maybe list

Might fits in **Storage** category

* **RDS** - DB service
* **EFS** - Basically a file share
* **ElastiCache** - Redis
* **EMR** - Cloud native big data
* **RedShift** - Data warehouse, which means DBs for BI.

Might fit in general **Orchastration** category...

* **CloudTrail** - See actions. Good for complience. Seems like this + CloudWatch should be the same thing.
* **CloudWatch** - Orchastration and visibility, unified view all resources and apps.
* **CloudFormation** - Like TerraForm but worse since it's only for AWS?
* **Config** - Same as CloudTrail or CloudWatch but for configurations. What? Why isn't all of this in one service?

###### Nope

* **Lambda** - Serverless computing
* **Directconnect** - Connect to AWS through dedicated hardware + connection (not over Internet).
* **ELB** - Load balancer
* **ELBV2** - Load balancer
* **Route53** - Cloud DNS
* **SES** - Email
* **SNS** - PubSub
* **SQS** - MQ

### Second execution - Azure

`scout.py azure: error: one of the arguments -c/--cli -m/--msi -s/--service-principal --file-auth --user-account is required`.

**Comment by VakarisZ** [comment]
# Implementation Plan and other details

## SS findings -> ZT findings translation
1. Island receives SS findings
2. Island goes through each SS finding, that's relevant to ZT findings, and creates new ZT finding with SS finding in details or adds SS finding to the details of an already present ZT finding. For that we also need to define which SS findings map to which ZT findings (many to one). For example ZT finding "Scoutsuite found overly permissive firewall rules" would map to SS findings: "Security Group Opens All Ports to All", "Security Group Opens RDP Port to All", "Security Group Opens SSH Port to All" etc.
3. Island goes through each relevant service and saves it's resources in mongodb.

## UI 
1. UI receives ZT findings and cloud services info.
2. Based on ZT finding type it either renders events or resources button.
![image](https://user-images.githubusercontent.com/36815064/92132836-53bcf000-ee10-11ea-825c-31b2073d310e.png)
3. Resources button opens up a modal window with **dropdowns** of each SS finding. Dropdowns contain resources, relevant to SS finding. Below screenshot shows how resources would look(without dropdown)
![image](https://user-images.githubusercontent.com/36815064/92132623-0d679100-ee10-11ea-8baf-66faa643c1e6.png)

 ## Task list

### Setup

- [x] Setup AWS testing env **e/0.5**
- [ ]  Setup GCP testing env **e/0.5** ?
- [ ]  Setup Azure testing env **e/0.5** ?

### Infrastructure

- [ ] Modify Scoutsuite into an API **e/1**
- [ ]  Test API run and send telemetries from monkey **e/0.5**

### SS finding to ZT finding translation

- [ ] Change ZT document structure and related code (ZT finding needs to support subdocuments in details prop) **e/2**
- [ ] Parse SS data into ZT document **e/1**
- [ ] Decide which SS findings should be aggregated into which ZT findings, which ZT findings should be created for CSPM and if we need to add more ZTX principles, somehow map SS findings and ZT findings together **e/2** 
- [ ] Repeat above step for GCP and Azure ? **e/3**


### SS finding display

- [ ] Adapt ZT front end to display the changed ZT document structure **e/1**
- [ ] Create modal window to display SS resources **e/5**:
    - Either modify SS front end code (which is ugly/jquery based) and re-use it in modal window + dropdowns OR
    - Write our own JS that would map SS finding to cloud resource
    - Improve back-end data parsing to further ease SS finding <-> Cloud resources mapping

### Total estimate: **13 - 16 sp.**

**Comment by VakarisZ** [comment]
## ScoutSuite finding -> Infection monkey finding. 

Scoutsuite findings are ordered by **service**. Each service contains `regions` and `findings`.
![image](https://user-images.githubusercontent.com/36815064/92477292-0910ee80-f1e9-11ea-8cf9-cc7a993f0004.png)

`regions` contain service resources. We should make sure to only store relevant services, and only send regions to UI once per service, not with every finding.
![image](https://user-images.githubusercontent.com/36815064/92478151-6ce7e700-f1ea-11ea-9349-eb1080bdf741.png)

`findings` contain a variety of fields, but they are consistent throughout different findings. `description`, `path`, `level`, `display_path`, `dashboard_name` and `rationale` and some other fields seem to be present in all findings, whereas `remediation`, `compliance` and `references` might be 'None'.
![image](https://user-images.githubusercontent.com/36815064/92481677-5d1ed180-f1ef-11ea-9e5a-5de1ac4ef1bb.png)

Items contain a reference to relevant resources in `regions`. Basically, it's a path to value in object `regions`.
![image](https://user-images.githubusercontent.com/36815064/92481926-b129b600-f1ef-11ea-8dce-138b8380b339.png)

## Example data:

### Example monkey finding:

```
{
    "_id" : ObjectId("5f576dd1c62c74f8cde19244"),
    "_cls" : "Finding",
    "test" : "endpoint_security_exists",
    "status" : "Failed",
    "details" : {
        "_cls" : "MonkeyFindingDetails",
        "_ref" : {
            "$ref" : "monkey_finding_details",
            "$id" : ObjectId("5f576dd1c62c74f8cde19243")
        }
    }
}
```

### Example monkey finding details:

```
{
    "_id" : ObjectId("5f576dd1c62c74f8cde19243"),
    "events" : [ 
        {
            "timestamp" : ISODate("2020-09-08T14:41:05.791Z"),
            "title" : "Process list",
            "message" : "Monkey on ip-10-0-0-167 scanned the process list",
            "event_type" : "monkey_local"
        }, 
        {
            "timestamp" : ISODate("2020-09-08T15:05:06.774Z"),
            "title" : "Process list",
            "message" : "Monkey on ip-10-0-0-167 scanned the process list",
            "event_type" : "monkey_local"
        }
    ]
}
```

### Example scoutsuite finding:

```
{
    "_id" : ObjectId("5f576dd1c62c74f8cde19244"),
    "_cls" : "Finding",
    "test" : "scoutsuite_permissive_firewall_rules",
    "status" : "Failed",
    "details" : {
        "_cls" : "ScoutsuiteFindingDetails",
        "_ref" : {
            "$ref" : "scoutsuite_finding_details",
            "$id" : ObjectId("5f576dd1c62c74f8cde19243")
        }
    }
}
```


### Example scoutsuite finding details:

```
{
    "_id" : ObjectId("5f576dd1c62c74f8cde19244"),
    "_cls" : "ScoutsuiteFindingDetails",
    "regions" : {
        "_cls" : "ScoutsuiteRegions",
        "_ref" : {
            "$ref" : "scoutsuite_regions",
            "$id" : ObjectId("5f576dd1c62c74f8cde19243")
        }
    }
    "scoutsuite_findings" : [
    {{
        'description': 'Security Group Opens All Ports to All', 
        'path': 'ec2.regions.id.vpcs.id.security_groups.id.rules.id.protocols.id.ports.id.cidrs.id.CIDR', 
        'level': 'danger', 
        'display_path': 'ec2.regions.id.vpcs.id.security_groups.id', 
        'items': ['ec2.regions.eu-central-1.vpcs.vpc-00015526b6695f9aa.security_groups.sg-019eb67135ec81e65.rules.ingress.protocols.ALL.ports.1-65535.cidrs.0.CIDR'], 
        'dashboard_name': 'Rules', 
        'checked_items': 172, 
        'flagged_items': 1, 
        'service': 'EC2', 
        'rationale': 'It was detected that all ports in the security group are open, 
        and any source IP address could send traffic to these ports, 
        which creates a wider attack surface for resources assigned to it. Open ports should be reduced to the minimum needed to correctly operate and, 
        when possible, 
        source address restrictions should be implemented.', 
        'remediation': None, 
        'compliance': None, 
        'references': None
     }}
    ]
}
```
