### ISSUE TITLE
Automatic redirect to HTTP/S on HTTP request 

### ISSUE THREAD

**Issue by danielguardicore** [guardicore/monkey#590]
## Description

**Is your feature request related to a problem? Please describe.**
Monkey Island should listen to port 80 and 443 (if not taken) and redirect clients to the correct Island port.

**Describe alternatives you've considered**
We don't want to move the Island to port 443 because that loses us a ATT&CK technique for uncommon port, but many users accidentally browse to default http/https. 

## Tasks
- [ ] Research and pick:
    - [x] Redirect HTTP traffic to HTTPS without changing Island's port number (0d)
    - [x] Use `http.server` (or other mechanism) to redirect port 80 to port 443 (0d)
- [ ] Create new issue to replace this one (0.25d) @mssalvatore

**Comment by ilija-lazoroski** [comment]
Regarding binding gevent to port 80 or 443: https://flask.palletsprojects.com/en/2.2.x/deploying/gevent/#binding-externally

**Comment by mssalvatore** [comment]
Our research indicates that this is not practically achievable as written. This issue has therefore been superseded by #2695
