### ISSUE TITLE
Monkey to External system visibility

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#604]
Label machines as "Monkey X" on an external security system (like Centra)

Integrate as a Penetration Tester would ("machine is exploitable with SSH")

**Comment by ShayNehmad** [comment]
## DDR

Lingo:

- **Centra** - an external system which accepts labels on assets using API
- **Asset** - machine in the network

### High-Level Design

#### MH
To activate Centra integration, the user will enter the `integrations/centra` resource. There they will configure the integration. From that moment on every new scan/infection will be reported to Centra as well as an appropriate label, like `seen by Monkey`, `exploited by Monkey` and `vulnerable to CVE-XXX`.

#### NTH 
- Add a button to export all current info into labels as well.
- Add "remove all Monkey labels"
- See how many labels were created and other stats in Integration page?

### Detailed Design

#### Affected Components

##### Integrations page

We'll need to add a Centra integration to #605. This page will include two required fields: the API token and the server address, Page will also have documentation that explains how to generate that API token.

Once the user inputs the server and token, we will:

- test connection
- test API token validity

##### ExternalSecurityClientAPI class

We'll create a generic interface with rather basic methods:

- connect
- get_asset_from_ip
- label_asset

And two impls: One mock for UTs, one real for Centra.

A class for interacting with Centra's APIs. example usage:

```py
client = ClientManagementAPI(<ip>, port=<port>)
client.restapi.set_token(<plain-text token>)
# Continue as usual, e.g.:
client.test_connection()
```

##### Export label

Gets Edge and turns it into a label:

- if scan, add "seen by monkey" (might be useless?)
- if exploit, add "exploited by monkey" and "vulnerable to CVE-XXX"

by importing the ClientManagementAPI and using the following API calls:

```
def upsert_centra_label_from(edge: Edge):
    # First, find the asset:
    asset = client.Call https://{management_server}/api/v3.0/assets?status=on&search=edge.dst
    # Upsert labels for that asset
    asset_id = asset.id
    label = get_label_from_edge(edge)
    client.create_label(asset_id, label)
```

#### Testing

##### Whitebox

Use the Client mock to cover nearly everything with UTs.

##### Blackbox 

Manually in testdrive with v32. The tests will include the following cases:

###### Sanity
1. Run island
2. setup integration with a correct API token
3. Run monkey with some exploitable machines (different exploits) and some visible machines that aren't exploitable
4. see labels generated on Reveal map

###### Edge cases
- wrong API token
- API token revoked
- Centra stops answering


### Risks + Opportunities
Risk: Not making this generic enough for other systems as well.
Risk: API breaking? Seems to be versioned
Risk: Spamming labels

### Tasks

Low level task (scope: few hours to few days) | Owner | Time evaluation (buffers) | Resources + dependencies | Notes

- [ ] Run this with GC product | @ShayNehmad with product - 0.5
- [ ] Set up dev env | @ShayNehmad with Yonatan - 0.5
- [ ] API class | @ShayNehmad with Reyann - 1
- [ ] Develop integration + update label (given ClientAPI class) | @ShayNehmad - 1
- [ ] Integration page UI + content | @ShayNehmad (with product) - 1
- [ ] Testing + documentation (depends on #602) - 1

Total: 5 SPs

**Comment by itaymmguardicore** [comment]
Current status:
* Open PR near finish: #712 
* Open source API for centra: https://github.com/guardicode/centra-py-client

What needs to be done:
* Modify the code for the existing PR to directly use centra-py-client
* Consider implementing as part of an "integrations page"
