### ISSUE TITLE
Ship island mongodb with attack_mitigations already present

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#629]
Parsing mitre CTI to extract and save `attack_mitigations` on the database takes some time (~4 seconds to me). This needlessly prolongs setup of monkey island. We should ship island binaries with `attack_mitigations` already present in the database and save some time for the user.

# Tasks

- [ ] Write a Python utility to generate mongo dump/export for Attack Mitigations. (See [this](https://github.com/guardicore/monkey/issues/629#issuecomment-919056350))  (0.25d)  @mssalvatore 
    - [x] Clean/clear/setup database
    - [x] Read attack data submodule and populate mongo database 
    - [x] Export/dump mongo database
    - [x] Remove unused import code from Monkey Island
    - [x] Add metadata including git commit and origin url in `attack_metadata.json`
    - [x] Document this in ??developer documentation??
- [x] Remove attack-data submodule and store the mongo dump in `monkey_island/cc/setup/mongo/` (0d) @ilija-lazoroski 
  - [x] Modify pyinstaller hooks to include mongo dump file  
  - [x] Fix monkey_island.spec
- [ ]  Replace the code in Monkey Island that populates the attack section with code that imports a dump and test all installers. (0.25d) @ilija-lazoroski

**Comment by mssalvatore** [comment]
Resolving this issue is the first step towards resoloving #1428

**Comment by ilija-lazoroski** [comment]
As it is now the `attack_mitigations` collection if exported is around 140kB in size which we can easily export/import in the mongodb. It is used just `pymongo` and `bson` which is dependency of pymongo and we already use it in the monkey code.

 The snippet code for both export and import:

```
from os.path import join
import pymongo
from bson import json_util
import json


def export_collection(mongodb, backup_db_dir, collection_imported):

    collections = mongodb.list_collection_names()
    if collection_imported in collections:
        index = collections.index(collection_imported)
        col = getattr(database, collections[index])
        collection = col.find()
        jsonpath = collection_imported + ".json"
        jsonpath = join(backup_db_dir, jsonpath)
        with open(jsonpath, "wb") as jsonfile:
            jsonfile.write(json_util.dumps(collection).encode())


def import_collection(mongodb, collection_import, collection_exported):

    collection_currency = mongodb[collection_import]
    with open(collection_exported + ".json") as f:
        file_data = json.load(f)
    try:
        collection_currency.insert_many(file_data)
    except Exception as e:
        print(e)


if __name__ == "__main__":

    collection_name = "attack_mitigations"
    database_name = "monkeyisland"
    mongo_host = "localhost"
    mongo_port = 27017

    client = pymongo.MongoClient(host=mongo_host, port=mongo_port)
    database = client[database_name]

    export_collection(
        mongodb=database, backup_db_dir=".", collection_imported=collection_name
    )
    import_collection(
        mongodb=database,
        collection_import="attack_import",
        collection_exported=collection_name,
    )
```

We can save and ship the exported collection and then import the collection probably in `monkey_island/cc/setup/mongo/database_initializer` under `_store_mitigations_on_mongo` . The mitigations we store are of type `dict` which we can grab it from `import_collection`.

Exported collection as they are from the mongodb:
[attack_mitigations.txt](https://github.com/guardicore/monkey/files/7161363/attack_mitigations.txt)

Proof of importing the exported collection:
![image](https://user-images.githubusercontent.com/15820737/133247879-3b2b9e8e-0346-4ad9-bae2-d8d83d8ea3f9.png)
