### ISSUE TITLE
Add depth limit test to BB

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#640]
## Description

Make sure monkey obeys depth restrictions by adding depth test to BB env.

## Tasks
- [x] Create a function that checks that depth restrictions were obeyed (0d)
    - [x] Query for all agents
    - [x] Add treelib as a dev dependency of the Island
    - [x] Use treelib to build a tree of agents
    - [x] Assert that the tree (height - 1) is <= simulation depth setting
- [ ] Add this assertion to all tests (0.25d)

**Comment by ShayNehmad** [comment]
Related to #639

**Comment by mssalvatore** [comment]
This could be added to the depth_1_a test by getting all agents and verifying that `len(agents) == len(machines)`.
