### ISSUE TITLE
Make island HTTP port more easily configurable

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#649]
**Is your feature request related to a problem? Please describe.**
Currently we can't change default island port

**Describe the solution you'd like**
There should be a configuration value that allows to change island port or at least a value in `server_config.json` that contains the port.

## Tasks

 - [ ] Configure island to omit the `node_port` instead of port `5000` when providing socket callback addresses for the Island @shreyamalviya 
     - [x] In manual run
     - [x] In "run from island"
 - [ ] Change `aws_command_runner.py` @shreyamalviya 
 - [ ] Test @shreyamalviya @ilija-lazoroski
 - [ ] Update documentation

**Comment by ShayNehmad** [comment]
Current workaround: edit the `/var/monkey/monkey_island/cc/environment/__init__.py` file to change the default port (line 10) and then restart the monkey island service using `sudo service monkey-island restart`

**Comment by VakarisZ** [comment]
Bootloader has 5000 hardcoded, I'm not sure this workaround actually works.

**Comment by nicpenning** [comment]
This worked for me, but I think a different issue popped up while doing so.

That is the Run Monkey PowerShell script does not take into account the port it is actually running on.

Let's say I alter the port to 9005, I will still see this for the script:

`powershell [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}; (New-Object System.Net.WebClient).DownloadFile('https://192.168.1.10:5000/api/monkey/download/monkey-windows-32.exe','.\monkey.exe'); ;Start-Process -FilePath '.\monkey.exe' -ArgumentList 'm0nk3y -s 192.168.1.10:5000';`

Furthermore, this script on it's own provides this error:
(Is the encodedCommand living inside of the monkey.exe file?)
`-encodedCommand : The term '-encodedCommand' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:73
+ ... nager]::ServerCertificateValidationCallback = -encodedCommand JAB0AHI ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-encodedCommand:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

Please let me know if this should be broken out to it's own issue.

**Comment by VakarisZ** [comment]
@nicpenning You're right, Infection Monkey doesn't really support port configuration, but you can download a docker container and map to whichever port you want.
Regarding the second error, make sure to run the command in command prompt and not in powershell (as it has powershell at the start). Other than that I'm not familiar with this error. Let me know more info about reproducing it.

**Comment by nicpenning** [comment]
Sounds good! I will try that out.

**Comment by VakarisZ** [comment]
This could be solved by #3827 for the most part. We just need to configure the agents to send requests to the node.js api proxy, rather than straight to `:5000`.

**Comment by shreyamalviya** [comment]
b8fc06653a5d822f8fab9679329945dccf6f2d01
