### ISSUE TITLE
Add frontend test infrastructure

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#765]
## Problem
We only have unit tests for the backend as of now. We should create infrastructure for JS unit testing: add automatic unit test execution to travis and codecov, implement a few unit tests as an example for important parts of UI code

We investigated a handful of UI testing frameworks in #3685, and have settled on Jest for unit tests and Cypress for end-to-end testing. We currently have a branch, `3685-cypress`, which has some basic testing implemented.

## Tasks
- [x] Setup Jest (guardicore/monkey#4030)
    - [x] Add Jest dev dependencies
    - [x] Configure Jest to use typescript ~and webpack~
    - [x] Implement a unit test
    - [x] Add NPM script to run unit tests
- [ ] Setup Cypress (guardicore/monkey#4048)
    - [x] Add Cypress dev dependencies
    - [ ] Configure cypress to use react and webpack
    - [x] Implement a component test using Cypress (e.g., login page)
    - [x] Implement an e2e test using Cypress (e.g., registration)
    - [x] Add NPM scripts to run the component and e2e tests

**Comment by VakarisZ** [comment]
Related: https://github.com/guardicore/monkey/issues/1127
